/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 30 22:46:02 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.Configuration;
import java.util.Properties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Configuration_ESTest extends Configuration_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای قبل از اجرای هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String string0 = Configuration.accountPropertyFile();
      assertEquals("C:\\Users\\Shahriar/.iris/account.properties", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      Configuration configuration0 = new Configuration();
      Properties properties0 = configuration0.getProperties();
      assertEquals(16, properties0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Configuration configuration0 = null;
      try {
        configuration0 = new Configuration();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Could not open the configuration file default_provider.properties
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.Configuration", e);
      }
  }

  @Test(timeout = 4000)
  public void test3_overrideProviderNameFromAccountFile() throws Throwable {
      // حساب را با مقداردهی کلیدِ نامِ Provider می‌سازیم/می‌نویسیم
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_NAME + "=MyMail");
      Configuration cfg = new Configuration();
      Properties p = cfg.getProperties();
      assertEquals("MyMail", p.getProperty(Configuration.PROVIDER_NAME));
  }

  @Test(timeout = 4000)
  public void test4_accountPropertyFileRespectsUserHomeChange() throws Throwable {
      String old = java.lang.System.getProperty("user.home");
      try {
          java.lang.System.setProperty("user.home", "D:\\tmp");
          String expected = "D:\\tmp/.iris/account.properties";
          assertEquals(expected, Configuration.accountPropertyFile());
      } finally {
          java.lang.System.setProperty("user.home", old);
      }
  }

  @Test(timeout = 4000)
  public void test5_getProperties_isLiveReference() throws Throwable {
      // فایل حساب حداقل یک خط داشته باشد تا سازنده موفق شود
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_AUTH + "=true");

      Configuration cfg = new Configuration();
      Properties p1 = cfg.getProperties();
      p1.setProperty("k", "v");
      Properties p2 = cfg.getProperties();
      assertEquals("v", p2.getProperty("k"));
  }

  @Test(timeout = 4000)
  public void test6_allKnownKeysFromAccountAreLoaded() throws Throwable {
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      // هر کلید را با یک مقدار مشخص می‌نویسیم
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_AUTH + "=yes");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_NAME + "=XName");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_DESCRIPTION + "=XDesc");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_TRANSPORT_PROTOCOL + "=smtp");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_TRANSPORT_HOST + "=smtp.example.com");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_TRANSPORT_PORT + "=587");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_STORE_PROTOCOL + "=imap");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_STORE_HOST + "=imap.example.com");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_STORE_PORT + "=993");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_USER + "=userX");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_PASSWORD + "=passX");

      Configuration cfg = new Configuration();
      Properties p = cfg.getProperties();

      assertEquals("yes", p.getProperty(Configuration.PROVIDER_AUTH));
      assertEquals("XName", p.getProperty(Configuration.PROVIDER_NAME));
      assertEquals("XDesc", p.getProperty(Configuration.PROVIDER_DESCRIPTION));
      assertEquals("smtp", p.getProperty(Configuration.PROVIDER_TRANSPORT_PROTOCOL));
      assertEquals("smtp.example.com", p.getProperty(Configuration.PROVIDER_TRANSPORT_HOST));
      assertEquals("587", p.getProperty(Configuration.PROVIDER_TRANSPORT_PORT));
      assertEquals("imap", p.getProperty(Configuration.PROVIDER_STORE_PROTOCOL));
      assertEquals("imap.example.com", p.getProperty(Configuration.PROVIDER_STORE_HOST));
      assertEquals("993", p.getProperty(Configuration.PROVIDER_STORE_PORT));
      assertEquals("userX", p.getProperty(Configuration.PROVIDER_USER));
      assertEquals("passX", p.getProperty(Configuration.PROVIDER_PASSWORD));
  }

  @Test(timeout = 4000)
  public void test7_emptyAccountFileStillLoadsDefaults() throws Throwable {
      // فایل را خالی ایجاد می‌کنیم؛ پیش‌فرض‌های کلاس‌پس باید لود شوند
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, ""); // خالی

      Configuration cfg = new Configuration();
      Properties p = cfg.getProperties();
      // صرفاً اطمینان از این‌که چیزی لود شده (عدد دقیق به محتوای default_provider.properties بستگی دارد)
      assertTrue(p.size() > 0);
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  @Test(timeout = 4000)
  public void test8_accountPropertyFile_calledTwice_consistent() throws Throwable {
      String a = Configuration.accountPropertyFile();
      String b = Configuration.accountPropertyFile();
      assertEquals(a, b);
      assertTrue(a.endsWith("/.iris/account.properties"));
  }

  @Test(timeout = 4000)
  public void test9_overrideSameKey_lastWins() throws Throwable {
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_USER + "=first");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_USER + "=second"); // آخرین مقدار
      Configuration cfg = new Configuration();
      assertEquals("second", cfg.getProperties().getProperty(Configuration.PROVIDER_USER));
  }

  @Test(timeout = 4000)
  public void test10_unknownKey_isLoadedFromAccountFile() throws Throwable {
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, "custom.key=42");
      Configuration cfg = new Configuration();
      assertEquals("42", cfg.getProperties().getProperty("custom.key"));
  }

  @Test(timeout = 4000)
  public void test11_reconstructAfterAccountChange_reflectsNewValue() throws Throwable {
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_NAME + "=Before");
      Configuration a = new Configuration();
      assertEquals("Before", a.getProperties().getProperty(Configuration.PROVIDER_NAME));

      // تغییر فایل و ساخت نمونه جدید
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_NAME + "=After");
      Configuration b = new Configuration();
      assertEquals("After", b.getProperties().getProperty(Configuration.PROVIDER_NAME));
  }

  @Test(timeout = 4000)
  public void test12_commentsAreIgnored() throws Throwable {
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, "# this is a comment");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_DESCRIPTION + "=descV");
      Configuration cfg = new Configuration();
      assertEquals("descV", cfg.getProperties().getProperty(Configuration.PROVIDER_DESCRIPTION));
  }

  @Test(timeout = 4000)
  public void test13_whitespaceAroundEquals_isTrimmed() throws Throwable {
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, " " + Configuration.PROVIDER_TRANSPORT_HOST + "  =  smtp.host.local  ");
      Configuration cfg = new Configuration();
      assertEquals("smtp.host.local", cfg.getProperties().getProperty(Configuration.PROVIDER_TRANSPORT_HOST));
  }

  @Test(timeout = 4000)
  public void test14_providerAuth_false_isRespectedAsString() throws Throwable {
      EvoSuiteFile f = new EvoSuiteFile("C:\\Users\\Shahriar\\.iris\\account.properties");
      FileSystemHandling.appendLineToFile(f, Configuration.PROVIDER_AUTH + "=false");
      Configuration cfg = new Configuration();
      assertEquals("false", cfg.getProperties().getProperty(Configuration.PROVIDER_AUTH));
  }

  @Test(timeout = 4000)
  public void test15_accountPropertyFile_withTrailingUserHomeSlash() throws Throwable {
      String old = java.lang.System.getProperty("user.home");
      try {
          java.lang.System.setProperty("user.home", "E:\\home\\");
          String expected = "E:\\home\\/.iris/account.properties";
          assertEquals(expected, Configuration.accountPropertyFile());
      } finally {
          java.lang.System.setProperty("user.home", old);
      }
  }

}
