/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 22:33:49 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.DownloadMessagesConsoleCommand;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class DownloadMessagesConsoleCommand_ESTest extends DownloadMessagesConsoleCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست */
  private void delay() {
      try { Thread.sleep(500L); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      delay();
      DownloadMessagesConsoleCommand downloadMessagesConsoleCommand0 = new DownloadMessagesConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("Downloading messages from/to folder: ");
      downloadMessagesConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try {
        downloadMessagesConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.DownloadMessagesConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      delay();
      DownloadMessagesConsoleCommand downloadMessagesConsoleCommand0 = new DownloadMessagesConsoleCommand();
      // Undeclared exception!
      try {
        downloadMessagesConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.DownloadMessagesConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      delay();
      DownloadMessagesConsoleCommand downloadMessagesConsoleCommand0 = new DownloadMessagesConsoleCommand();
      String string0 = downloadMessagesConsoleCommand0.getCommandName();
      assertEquals("download", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      delay();
      DownloadMessagesConsoleCommand downloadMessagesConsoleCommand0 = new DownloadMessagesConsoleCommand();
      downloadMessagesConsoleCommand0.explain();
      assertEquals("download", downloadMessagesConsoleCommand0.getCommandName());
  }

  /** helper: گرفتن stdout با java.lang.System (جلوگیری از تداخل با org.evosuite.runtime.System) */
  private String captureStdout(final Runnable r) {
      PrintStream orig = java.lang.System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      java.lang.System.setOut(ps);
      try {
          r.run();
      } finally {
          java.lang.System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test4_handleExecute_printsDefaultFolder_thenThrows_NoClassDef() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();

      // پاس اول: خروجی را بگیر و استثناء را ببلع تا مطمئن شو پیام چاپ می‌شود
      String out = captureStdout(new Runnable() {
          @Override public void run() {
              try { cmd.handleExecute(); } catch (Throwable ignored) { }
          }
      });
      assertNotNull(out);
      assertTrue(out.contains("Downloading messages from/to folder: "));

      // پاس دوم: اجرای مستقیم و انتظار برای استثناء (زیرساخت ایمیل موجود نیست)
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.DownloadMessagesConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test5_handleExecute_withCustomFolderParam_printsParam() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("MyFolder");
      cmd.setParameters(params);

      String out = captureStdout(new Runnable() {
          @Override public void run() {
              try { cmd.handleExecute(); } catch (Throwable ignored) { }
          }
      });
      assertNotNull(out);
      assertTrue(out.contains("Downloading messages from/to folder: "));
      assertTrue(out.contains("MyFolder"));
  }

  @Test(timeout = 4000)
  public void test6_handleExecute_twoParams_usesFirstOnly() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("First");
      params.add("Second");
      cmd.setParameters(params);

      String out = captureStdout(new Runnable() {
          @Override public void run() {
              try { cmd.handleExecute(); } catch (Throwable ignored) { }
          }
      });
      assertNotNull(out);
      assertTrue(out.contains("Downloading messages from/to folder: First"));
      assertFalse(out.contains("Second"));
  }

  @Test(timeout = 4000)
  public void test7_explain_safe_noCrash_whenI18nMissing() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      String out;
      try {
          out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      } catch (Throwable ignored) {
          // اگر باندل i18n نباشد ممکن است استثناء بیاید؛ تست را مقاوم نگه می‌داریم
          out = "";
      }
      assertEquals("download", cmd.getCommandName());
      if (out != null && out.length() > 0) {
          assertTrue(out.contains("(download)"));
          // وجود کلید i18n اختیاری است؛ در برخی محیط‌ها خود کلید چاپ می‌شود:
          // assertTrue(out.contains("command.download.explain"));
      }
  }

  @Test(timeout = 4000)
  public void test8_handleExecute_withEmptyParamList_behavesLikeDefault() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      cmd.setParameters(new java.util.LinkedList<String>());

      String out = captureStdout(new Runnable() {
          @Override public void run() {
              try { cmd.handleExecute(); } catch (Throwable ignored) { }
          }
      });
      assertNotNull(out);
      assertTrue(out.contains("Downloading messages from/to folder: "));
  }

  @Test(timeout = 4000)
  public void test9_getCommandName_nonEmpty_andConstant() throws Throwable {
      delay();
      DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertFalse(name.isEmpty());
      assertEquals(DownloadMessagesConsoleCommand.COMMAND_NAME, name);
  }

  @Test(timeout = 4000)
  public void test10_explain_multipleCalls_consistentOutputIfAvailable() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      String out1, out2;
      try {
          out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      } catch (Throwable ignored) { out1 = ""; }
      try {
          out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      } catch (Throwable ignored) { out2 = ""; }

      if (out1.length() > 0 && out2.length() > 0) {
          assertTrue(out1.contains("(download)"));
          assertTrue(out2.contains("(download)"));
      }
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test11_handleExecute_twice_consistentPrinting() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(out1.contains("Downloading messages from/to folder: "));
      assertTrue(out2.contains("Downloading messages from/to folder: "));
  }

  @Test(timeout = 4000)
  public void test12_handleExecute_paramWithSpaces_printedAsIs() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("Inbox/Sub Folder");
      cmd.setParameters(params);

      String out = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(out.contains("Downloading messages from/to folder: "));
      assertTrue(out.contains("Inbox/Sub Folder"));
  }

  @Test(timeout = 4000)
  public void test13_handleExecute_threeParams_onlyFirstUsed() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("First");
      params.add("Second");
      params.add("Third");
      cmd.setParameters(params);

      String out = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(out.contains("Downloading messages from/to folder: First"));
      assertFalse(out.contains("Second"));
      assertFalse(out.contains("Third"));
  }

  @Test(timeout = 4000)
  public void test14_explain_output_noNullOrExceptionWords() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      String out;
      try {
          out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      } catch (Throwable ignored) { out = ""; }
      String lower = out.toLowerCase();
      if (!lower.isEmpty()) {
          assertFalse(lower.contains("null"));
          assertFalse(lower.contains("exception"));
      }
  }

  @Test(timeout = 4000)
  public void test15_commandName_stable_afterFailure() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      String before = cmd.getCommandName();
      try { cmd.handleExecute(); } catch (Throwable ignored) {}
      String after = cmd.getCommandName();
      assertEquals(before, after);
      assertEquals(DownloadMessagesConsoleCommand.COMMAND_NAME, after);
  }

  @Test(timeout = 4000)
  public void test16_handleExecute_withUnicodeParam_printsUnicode() throws Throwable {
      delay();
      final DownloadMessagesConsoleCommand cmd = new DownloadMessagesConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("پوشه-آزمایشی");
      cmd.setParameters(params);

      String out = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(out.contains("Downloading messages from/to folder: "));
      assertTrue(out.contains("پوشه-آزمایشی"));
  }
}
