/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Sep 01 11:21:08 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class ConsoleSearchCommand_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\Shahriar\\Desktop\\eclipse4.28.0committers-featureide3.11.1-win64_2\\workspace\\iris-delta-programming-master12"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\Shahriar\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ConsoleSearchCommand_ESTest_scaffolding.class.getClassLoader() ,
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.AbstractListMessagesCommand",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.i18n.MessageBundle",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.core.SystemFacade",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.core.exception.EmailException",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.core.exception.EmailUncheckedException",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.mail.IEmailClient",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.persistence.IEmailDAO",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.MailCommand",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.mail.EmailProvider",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.core.exception.EmailMessageValidationException",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.AbstractMailCommand"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ConsoleSearchCommand_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.AbstractMailCommand",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.AbstractListMessagesCommand",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand",
      "irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.i18n.MessageBundle"
    );
  }
}
