/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 20:19:23 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.reflect;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.reflect.ClassFinder;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Locale;
import java.util.Set;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import java.util.zip.ZipOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ClassFinder_ESTest extends ClassFinder_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست تا با timeout=4000 تداخلی نداشته باشد */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      ClassFinder classFinder0 = new ClassFinder(class0);
      String string0 = classFinder0.getClassName("PIa95qx1");
      assertEquals("PI", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<String> class0 = String.class;
      ClassFinder classFinder0 = new ClassFinder(class0, "6");
      classFinder0.addClassName("vw#^v45d3kLZ6R4yY");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Class<String> class0 = String.class;
      ClassFinder classFinder0 = new ClassFinder(class0);
      classFinder0.addClassName((String) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      classFinder0.classes = null;
      Set set0 = classFinder0.getClasses();
      assertNull(set0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      classFinder0.addClassName("QM\"GUvh@D");
      Set set0 = classFinder0.getClasses();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      String string0 = classFinder0.getClassName(".class");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      // Undeclared exception!
      try { 
        classFinder0.processZip((ZipFile) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.reflect.ClassFinder", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      // Undeclared exception!
      try { 
        classFinder0.isArchive((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      // Undeclared exception!
      try { 
        classFinder0.getClassName("vH");
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      // Undeclared exception!
      try { 
        classFinder0.getClassName((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.reflect.ClassFinder", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      Locale locale0 = Locale.CANADA;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      classFinder0.classes = set0;
      // Undeclared exception!
      try { 
        classFinder0.addClassName("obQkU:rlGT");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<String> class0 = String.class;
      ClassFinder classFinder0 = new ClassFinder(class0, "bD80\"K%");
      // Undeclared exception!
      try { 
        classFinder0.addClassName((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.reflect.ClassFinder", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      boolean boolean0 = classFinder0.isArchive("&'~PA^dTqNNu[V@6__d.zip");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ClassFinder classFinder0 = new ClassFinder();
      boolean boolean0 = classFinder0.isArchive("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Class<File> class0 = File.class;
      ClassFinder classFinder0 = new ClassFinder(class0, "T6<^wL/xM");
      Set set0 = classFinder0.getClasses();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Class<ZipEntry> class0 = ZipEntry.class;
      ClassFinder classFinder0 = new ClassFinder(class0, "irisdeltaj.simplerelational.br.unb.cic.iris.reflect.ClassFinder");
      classFinder0.addClassName("irisdeltaj.simplerelational.br.unb.cic.iris.reflect.ClassFinder");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Class<File> class0 = File.class;
      ClassFinder classFinder0 = new ClassFinder(class0, "T6<^wL/xM");
      classFinder0.addClassName("");
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Class<File> class0 = File.class;
      ClassFinder classFinder0 = new ClassFinder(class0, "T6<^wL/xM");
      String string0 = classFinder0.getClassName("T6<^wL/xM");
      assertEquals("T6<^w", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ClassFinder classFinder0 = new ClassFinder(class0);
      classFinder0.addClassName("irisdeltaj.simplerelational.br.unb.cic.iris.reflect.ClassFinder");
  }

  @Test(timeout = 4000)
  public void test19_addsWhenSubstringMatchesWithoutSuper()  throws Throwable  {
      ClassFinder cf = new ClassFinder((Class) null, "lang"); // فقط فیلتر مسیر
      cf.addClassName("java.lang.String");
      assertTrue(cf.classes.contains("java.lang.String"));
  }

  @Test(timeout = 4000)
  public void test20_doesNotAddWhenSubstringDoesNotMatch()  throws Throwable  {
      ClassFinder cf = new ClassFinder((Class) null, "x.y.notthere");
      cf.addClassName("java.lang.String");
      assertFalse(cf.classes.contains("java.lang.String"));
  }

  @Test(timeout = 4000)
  public void test21_addsWhenAssignableFromSuper()  throws Throwable  {
      ClassFinder cf = new ClassFinder(Object.class); // String زیرکلاس Object است
      cf.addClassName("java.lang.String");
      assertTrue(cf.classes.contains("java.lang.String"));
  }

  @Test(timeout = 4000)
  public void test22_notAddedWhenNotAssignableFromSuper()  throws Throwable  {
      ClassFinder cf = new ClassFinder(Number.class); // String زیرکلاس Number نیست
      cf.addClassName("java.lang.String");
      assertFalse(cf.classes.contains("java.lang.String"));
  }

  @Test(timeout = 4000)
  public void test23_unknownClassIsSafelyIgnored()  throws Throwable  {
      ClassFinder cf = new ClassFinder(Object.class);
      cf.addClassName("com.example.DoesNotExist___Class");
      assertTrue(cf.classes.isEmpty());
  }

  @Test(timeout = 4000)
  public void test24_getClassNameWindowsSeparators()  throws Throwable  {
      ClassFinder cf = new ClassFinder();
      String name = cf.getClassName("a\\b\\C.class");
      assertEquals("a.b.C", name);
  }

  @Test(timeout = 4000)
  public void test25_getClassNameUnixSeparators()  throws Throwable  {
      ClassFinder cf = new ClassFinder();
      String name = cf.getClassName("com/foo/Bar.class");
      assertEquals("com.foo.Bar", name);
  }

  @Test(timeout = 4000)
  public void test26_isArchiveJarUppercaseIsFalse()  throws Throwable  {
      ClassFinder cf = new ClassFinder();
      assertFalse(cf.isArchive("LIB.JAR")); // حساس به حروف بزرگ/کوچک
  }

  @Test(timeout = 4000)
  public void test27_isArchiveJarAndZipTrue()  throws Throwable  {
      ClassFinder cf = new ClassFinder();
      assertTrue(cf.isArchive("lib.jar"));
      assertTrue(cf.isArchive("lib.zip"));
  }

  // ========================= اضافه‌شده‌ها =========================

  @Test(timeout = 4000)
  public void test28_processZip_addsClassEntries() throws Throwable {
      ClassFinder cf = new ClassFinder();
      File zf = File.createTempFile("cf-", ".zip");
      zf.deleteOnExit();
      try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(zf))) {
          zos.putNextEntry(new ZipEntry("com/foo/Bar.class"));
          zos.write(new byte[0]);
          zos.closeEntry();
          zos.putNextEntry(new ZipEntry("com/foo/NotAClass.txt"));
          zos.write(new byte[0]);
          zos.closeEntry();
          zos.putNextEntry(new ZipEntry("com/foo/Inner$Nested.class"));
          zos.write(new byte[0]);
          zos.closeEntry();
      }
      try (ZipFile zip = new ZipFile(zf)) {
          cf.processZip(zip);
      }
      assertTrue(cf.classes.contains("com.foo.Bar"));
      assertTrue(cf.classes.contains("com.foo.Inner$Nested"));
      assertFalse(cf.classes.contains("com.foo.NotAClass"));
  }

  @Test(timeout = 4000)
  public void test29_getClassName_keepsInnerClassDollar() throws Throwable {
      ClassFinder cf = new ClassFinder();
      String name = cf.getClassName("x/y/Outer$Inner.class");
      assertEquals("x.y.Outer$Inner", name);
  }

  @Test(timeout = 4000)
  public void test30_addClassName_duplicateGoesToSetOnce() throws Throwable {
      ClassFinder cf = new ClassFinder(Object.class);
      cf.addClassName("java.lang.String");
      cf.addClassName("java.lang.String");
      assertEquals(1, cf.classes.size());
  }

  @Test(timeout = 4000)
  public void test31_filterSubstringBlocksAddition() throws Throwable {
      ClassFinder cf = new ClassFinder(Object.class, "allow.only.this.pkg");
      cf.addClassName("java.lang.String");
      assertFalse(cf.classes.contains("java.lang.String"));
  }

  @Test(timeout = 4000)
  public void test32_isArchive_jarWithTrailingSpaceFalse() throws Throwable {
      ClassFinder cf = new ClassFinder();
      assertFalse(cf.isArchive("lib.jar "));
      assertFalse(cf.isArchive(" lib.zip"));
  }

  @Test(timeout = 4000)
  public void test33_addClassName_NotAssignableEvenIfFilterMatches() throws Throwable {
      // فیلتر مسیر می‌خورد اما کلاس از نوع مورد انتظار نیست
      ClassFinder cf = new ClassFinder(Number.class, "java.lang");
      cf.addClassName("java.lang.String"); // String زیرکلاس Number نیست
      assertFalse(cf.classes.contains("java.lang.String"));
  }

  @Test(timeout = 4000)
  public void test34_getClassName_handlesDeepPath() throws Throwable {
      ClassFinder cf = new ClassFinder();
      String name = cf.getClassName("a/b/c/d/e/FooBar.class");
      assertEquals("a.b.c.d.e.FooBar", name);
  }

  @Test(timeout = 4000)
  public void test35_isArchive_mixedCaseZipFalse() throws Throwable {
      ClassFinder cf = new ClassFinder();
      assertFalse(cf.isArchive("MyLib.ZiP"));
  }
}
