/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 21:38:17 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleHelpCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class ConsoleHelpCommand_ESTest extends ConsoleHelpCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست */
  private void delay() {
      try { Thread.sleep(500L); }
      catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      delay();
      ConsoleHelpCommand consoleHelpCommand0 = new ConsoleHelpCommand();
      consoleHelpCommand0.handleExecute();
      assertEquals("help", consoleHelpCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      delay();
      ConsoleHelpCommand consoleHelpCommand0 = new ConsoleHelpCommand();
      consoleHelpCommand0.explain();
      assertEquals("help", consoleHelpCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      delay();
      ConsoleHelpCommand consoleHelpCommand0 = new ConsoleHelpCommand();
      String string0 = consoleHelpCommand0.getCommandName();
      assertEquals("help", string0);
  }

  /** هِلپر: گرفتن خروجی System.out بدون لامبدا (Java 8 سازگار) */
  private String captureStdout(final Runnable r) {
      PrintStream orig = System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      System.setOut(ps);
      try {
          r.run();
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test3_explain_printsUsageWithKey() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      String out = captureStdout(new Runnable() {
          @Override public void run() { cmd.explain(); }
      });
      // فرمت کلی: (help) - <message>
      assertTrue(out.contains("(help)"));
      // در نبود ResourceBundle، کلید i18n چاپ می‌شود:
      assertTrue(out.contains("command.help.explain"));
      assertEquals("help", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test4_handleExecute_runsWithoutException_evenIfRegistryEmpty() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      // اگر لیست فرمان‌ها خالی باشد، نباید چیزی چاپ کند و نباید استثنا بدهد
      String out = captureStdout(new Runnable() {
          @Override public void run() { cmd.handleExecute(); }
      });
      // یا خالی است یا شامل خروجی explain فرمان‌های ثبت‌شده (اگر وجود داشته باشند)
      assertNotNull(out);
  }

  @Test(timeout = 4000)
  public void test5_handleExecute_canBeCalledTwice_idempotentNoCrash() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      captureStdout(new Runnable() { @Override public void run() { cmd.handleExecute(); }});
      captureStdout(new Runnable() { @Override public void run() { cmd.handleExecute(); }});
      assertEquals("help", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test6_explain_multipleCalls_consistentOutput() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      assertTrue(out1.contains("(help)"));
      assertTrue(out2.contains("(help)"));
      // وجود کلید i18n در هر دو
      assertTrue(out1.contains("command.help.explain"));
      assertTrue(out2.contains("command.help.explain"));
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test7_explain_then_handleExecute_orderNoCrash() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.handleExecute(); }});
      assertNotNull(out);
      assertEquals("help", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test8_multipleInstances_independent() throws Throwable {
      delay();
      final ConsoleHelpCommand c1 = new ConsoleHelpCommand();
      final ConsoleHelpCommand c2 = new ConsoleHelpCommand();
      assertNotSame(c1, c2);
      captureStdout(new Runnable() { @Override public void run() { c1.explain(); }});
      captureStdout(new Runnable() { @Override public void run() { c2.handleExecute(); }});
      assertEquals("help", c1.getCommandName());
      assertEquals("help", c2.getCommandName());
  }

  @Test(timeout = 4000)
  public void test9_explain_outputDoesNotContainNullOrException() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String lower = out.toLowerCase();
      assertFalse(lower.contains("null"));
      assertFalse(lower.contains("exception"));
  }

  @Test(timeout = 4000)
  public void test10_getCommandName_isLowercaseAndNonBlank() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertTrue(name.trim().length() > 0);
      assertEquals("help", name);
      assertTrue(name.equalsIgnoreCase("HELP"));
  }

  @Test(timeout = 4000)
  public void test11_handleExecute_doesNotAlterCommandName() throws Throwable {
      delay();
      final ConsoleHelpCommand cmd = new ConsoleHelpCommand();
      String before = cmd.getCommandName();
      captureStdout(new Runnable() { @Override public void run() { cmd.handleExecute(); }});
      String after = cmd.getCommandName();
      assertEquals(before, after);
      assertEquals("help", after);
  }
}
