/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 21:09:03 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.junit.Before;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.TagManager;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.Tag;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TagManager_ESTest extends TagManager_ESTest_scaffolding {

  // 0.5s delay before each test
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      // Undeclared exception!
      try { 
        tagManager0.saveTags((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      // Undeclared exception!
      try { 
        tagManager0.getTagDAO();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      tagManager0.saveTags(",", ",");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      // Undeclared exception!
      try { 
        tagManager0.saveTags("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.exception.EmailException", "S,0");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      // Undeclared exception!
      try { 
        tagManager0.listMessagesByTag("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/EmailDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      // Undeclared exception!
      try { 
        tagManager0.findById("vL`^CS1^^+(']");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      Tag tag0 = new Tag();
      // Undeclared exception!
      try { 
        tagManager0.saveOrUpdate(tag0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      Tag tag0 = new Tag();
      // Undeclared exception!
      try { 
        tagManager0.delete(tag0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      // Undeclared exception!
      try { 
        tagManager0.findAll();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      TagManager tagManager0 = TagManager.instance();
      // Undeclared exception!
      try { 
        tagManager0.findByName("IKoar<Uebel-@h4i");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test10_instanceSingleton()  throws Throwable  {
      TagManager m1 = TagManager.instance();
      TagManager m2 = TagManager.instance();
      assertNotNull(m1);
      assertSame(m1, m2);
  }

  @Test(timeout = 4000)
  public void test11_saveTags_multipleTrimmed_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.saveTags("MSG-1", "  urgent , work , personal ");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test12_saveTags_trailingComma_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.saveTags("ID-1", "tag1,");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test13_delete_nullTag_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.delete((Tag) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test14_listMessagesByTag_null_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.listMessagesByTag((String) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test15_findById_null_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.findById((String) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test16_saveOrUpdate_null_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.saveOrUpdate((Tag) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test17_saveTags_onlySpaces_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.saveTags("M1", "   ");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test18_findByName_empty_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.findByName("");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test19_findAll_twice_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.findAll();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
      try {
          tagManager0.findAll();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  // ===== Added tests =====

  @Test(timeout = 4000)
  public void test20_instanceSingleton_multithreaded() throws Throwable {
      final TagManager[] arr = new TagManager[2];
      Thread t1 = new Thread(new Runnable() {
          @Override public void run() { arr[0] = TagManager.instance(); }
      });
      Thread t2 = new Thread(new Runnable() {
          @Override public void run() { arr[1] = TagManager.instance(); }
      });
      t1.start(); t2.start();
      t1.join();  t2.join();
      assertNotNull(arr[0]);
      assertSame(arr[0], arr[1]);
  }

  @Test(timeout = 4000)
  public void test21_getTagDAO_twice_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.getTagDAO();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
      try {
          tagManager0.getTagDAO();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test22_findByName_whitespace_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.findByName("   ");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test23_listMessagesByTag_whitespace_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.listMessagesByTag("   ");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test24_saveTags_unicode_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.saveTags("MSG-Ü", "پروژه,急ぎ,важно");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test25_saveOrUpdate_twice_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      Tag tag = new Tag();
      try {
          tagManager0.saveOrUpdate(tag);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
      try {
          tagManager0.saveOrUpdate(tag);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test26_delete_thenSaveOrUpdate_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      Tag tag = new Tag();
      try {
          tagManager0.delete(tag);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
      try {
          tagManager0.saveOrUpdate(tag);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test27_findById_empty_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.findById("");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test28_findByName_null_expectNoClassDef() throws Throwable {
      TagManager tagManager0 = TagManager.instance();
      try {
          tagManager0.findByName((String) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }
}
