/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 22:18:41 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;
import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleSendMessageCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ConsoleSendMessageCommand_ESTest extends ConsoleSendMessageCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست */
  private void delay() {
      try { Thread.sleep(500L); }
      catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      delay();
      ConsoleSendMessageCommand consoleSendMessageCommand0 = new ConsoleSendMessageCommand();
      String string0 = consoleSendMessageCommand0.getCommandName();
      assertEquals("send", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      delay();
      ConsoleSendMessageCommand consoleSendMessageCommand0 = new ConsoleSendMessageCommand();
      consoleSendMessageCommand0.explain();
      assertEquals("send", consoleSendMessageCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      delay();
      ConsoleSendMessageCommand consoleSendMessageCommand0 = new ConsoleSendMessageCommand();
      // Undeclared exception!
      try {
        consoleSendMessageCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleSendMessageCommand", e);
      }
  }

  /** helper: گرفتن خروجی stdout (بدون لامبدا) */
  private String captureStdout(final Runnable r) {
      java.io.PrintStream orig = java.lang.System.out;
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.lang.System.setOut(ps);
      try {
          r.run();
      } finally {
          java.lang.System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), java.nio.charset.StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test3_explain_printsUsageAndKey() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      // فرمت کلی: (send) - <پیام i18n>
      assertTrue(out.contains("(send)"));
      // در نبود ResourceBundle، کلید i18n چاپ می‌شود:
      assertTrue(out.contains("command.send.explain"));
      assertEquals("send", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test4_getCommandName_nonEmpty_constant() throws Throwable {
      delay();
      ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertFalse(name.isEmpty());
      assertEquals(ConsoleSendMessageCommand.COMMAND_SEND, name);
  }

  @Test(timeout = 4000)
  public void test5_handleExecute_throwsEarly_dueToMissingInfra() throws Throwable {
      delay();
      ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError due to mail/provider infra");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleSendMessageCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test6_handleExecute_withPreparedStdin_stillFailsEarly() throws Throwable {
      delay();
      // حتی اگر ورودی بدهیم، قبل از خواندن، در getProvider() شکست می‌خورد
      org.evosuite.runtime.util.SystemInUtil.addInputLine("to@x.com");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("cc@x.com");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("bcc@x.com");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("subject");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("content");

      ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleSendMessageCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test7_handleExecute_noStdoutPrintedBeforeFailure() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String out = captureStdout(new Runnable() {
          @Override public void run() {
              try { cmd.handleExecute(); } catch (Throwable ignored) { }
          }
      });
      // به‌طور معمول قبل از هر پرینتی در createMessage شکست می‌خورد
      assertTrue(out.trim().isEmpty());
  }

  @Test(timeout = 4000)
  public void test8_explain_multipleCalls_consistentOutput() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out1.contains("(send)"));
      assertTrue(out2.contains("(send)"));
      assertTrue(out1.contains("command.send.explain"));
      assertTrue(out2.contains("command.send.explain"));
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test9_handleExecute_twice_consistentFailure_noStdout() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(out1.trim().isEmpty());
      assertTrue(out2.trim().isEmpty());
  }

  @Test(timeout = 4000)
  public void test10_explain_then_handleExecute_outputsThenFails() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String outExplain = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String outExec = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(outExplain.contains("(send)"));
      assertTrue(outExplain.contains("command.send.explain"));
      assertTrue(outExec.trim().isEmpty());
      assertEquals("send", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test11_getCommandName_caseInsensitiveCheck() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      assertEquals("send", cmd.getCommandName());
      assertTrue(cmd.getCommandName().equalsIgnoreCase("SEND"));
  }

  @Test(timeout = 4000)
  public void test12_multipleInstances_independent() throws Throwable {
      delay();
      final ConsoleSendMessageCommand c1 = new ConsoleSendMessageCommand();
      final ConsoleSendMessageCommand c2 = new ConsoleSendMessageCommand();
      assertNotSame(c1, c2);
      assertEquals("send", c1.getCommandName());
      assertEquals("send", c2.getCommandName());
      String out1 = captureStdout(new Runnable() { @Override public void run() { c1.explain(); }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { try { c2.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(out1.contains("(send)"));
      assertTrue(out2.trim().isEmpty() || out2.contains("")); // فقط برای اطمینان از عدم NPE
  }

  @Test(timeout = 4000)
  public void test13_explain_noNullOrExceptionWords() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String lower = out.toLowerCase();
      assertFalse(lower.contains("null"));
      assertFalse(lower.contains("exception"));
  }

  @Test(timeout = 4000)
  public void test14_nameStable_afterException() throws Throwable {
      delay();
      final ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      String before = cmd.getCommandName();
      try { cmd.handleExecute(); } catch (Throwable ignored) {}
      String after = cmd.getCommandName();
      assertEquals(before, after);
      assertEquals(ConsoleSendMessageCommand.COMMAND_SEND, after);
  }

  @Test(timeout = 4000)
  public void test15_handleExecute_withEmptyInputs_alsoFailsEarly() throws Throwable {
      delay();
      // ورودی‌های خالی
      org.evosuite.runtime.util.SystemInUtil.addInputLine("");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("");
      org.evosuite.runtime.util.SystemInUtil.addInputLine("");

      ConsoleSendMessageCommand cmd = new ConsoleSendMessageCommand();
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleSendMessageCommand", e);
      }
  }
}
