/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 22:55:25 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.manager;

import org.junit.Test;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleSendMessageCommand;

import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleQuitCommand;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.manager.SimpleCommandManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class SimpleCommandManager_ESTest extends SimpleCommandManager_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست */
  private void delay() {
      try { Thread.sleep(500L); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      delay();
      SimpleCommandManager simpleCommandManager0 = new SimpleCommandManager();
      ConsoleQuitCommand consoleQuitCommand0 = new ConsoleQuitCommand();
      simpleCommandManager0.handleAddCommand(consoleQuitCommand0);
      assertEquals("quit", consoleQuitCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test1_addAndGet_sameInstance() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      ConsoleQuitCommand quit = new ConsoleQuitCommand();

      // add
      mgr.addCommand(quit);

      // get
      irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.MailCommand got = mgr.getCommand("quit");
      assertSame(quit, got);
  }

  @Test(timeout = 4000)
  public void test2_listAll_initiallyEmpty() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      assertNotNull(mgr.listAll());
      assertEquals(0, mgr.listAll().size());
  }

  @Test(timeout = 4000)
  public void test3_addTwoCommands_listAllGrows() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      int before = mgr.listAll().size();

      ConsoleQuitCommand quit = new ConsoleQuitCommand();
      ConsoleSendMessageCommand send = new ConsoleSendMessageCommand();

      mgr.addCommand(quit);
      mgr.addCommand(send);

      java.util.List<irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.MailCommand> all = mgr.listAll();
      assertTrue(all.size() >= before + 2);
      // هر دو نام باید قابل بازیابی باشند
      assertSame(quit, mgr.getCommand("quit"));
      assertSame(send, mgr.getCommand("send"));
  }

  @Test(timeout = 4000)
  public void test4_getUnknown_throwsEmailException() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      try {
          mgr.getCommand("nope");
          fail("Expected EmailException for unknown command");
      } catch (irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.exception.EmailException e) {
          // ok
      }
  }

  @Test(timeout = 4000)
  public void test5_addNull_throwsNPE() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      try {
          mgr.addCommand(null);
          fail("Expected NullPointerException when adding null command");
      } catch (NullPointerException e) {
          // ok
      }
  }

  @Test(timeout = 4000)
  public void test6_reload_noThrow() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      // در این کلاس reload در BaseCommandManager no-op است
      mgr.reload();
      // و همچنان لیست باید معتبر باشد
      assertNotNull(mgr.listAll());
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test7_handleAdd_thenGet_returnsSameInstance() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      ConsoleQuitCommand quit = new ConsoleQuitCommand();
      mgr.handleAddCommand(quit);
      assertSame(quit, mgr.getCommand("quit"));
  }

  @Test(timeout = 4000)
  public void test8_getCommand_wrongCase_throwsEmailException() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      mgr.addCommand(new ConsoleQuitCommand());
      try {
          mgr.getCommand("Quit"); // فرض: نام‌ها case-sensitive هستند
          fail("Expected EmailException for wrong-case command name");
      } catch (irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.exception.EmailException e) {
          // ok
      }
  }

  @Test(timeout = 4000)
  public void test9_addSend_listAllContainsInstance() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      ConsoleSendMessageCommand send = new ConsoleSendMessageCommand();
      mgr.addCommand(send);
      assertTrue(mgr.listAll().contains(send));
      assertSame(send, mgr.getCommand("send"));
  }

  @Test(timeout = 4000)
  public void test10_handleAddNull_throwsNPE() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      try {
          mgr.handleAddCommand(null);
          fail("Expected NullPointerException when adding null via handleAddCommand");
      } catch (NullPointerException e) {
          // ok
      }
  }

  @Test(timeout = 4000)
  public void test11_getCommand_withSpaces_throwsEmailException() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      mgr.addCommand(new ConsoleQuitCommand());
      try {
          mgr.getCommand(" quit "); // ورودی نامعتبر با فاصله
          fail("Expected EmailException for spaced command name");
      } catch (irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.exception.EmailException e) {
          // ok
      }
  }

  @Test(timeout = 4000)
  public void test12_reload_keepsExistingMappings() throws Throwable {
      delay();
      SimpleCommandManager mgr = new SimpleCommandManager();
      ConsoleSendMessageCommand send = new ConsoleSendMessageCommand();
      mgr.addCommand(send);
      mgr.reload(); // no-op
      assertSame(send, mgr.getCommand("send"));
  }
}
