/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 30 22:34:20 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model;

import org.junit.Test;
import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.EmailMessage;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.IrisFolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class FolderContent_ESTest extends FolderContent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0() throws Throwable {
      Thread.sleep(500);
      EmailMessage emailMessage0 = new EmailMessage("1*", "jg&g~dh", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", "", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent");
      String string0 = emailMessage0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1() throws Throwable {
      Thread.sleep(500);
      IrisFolder irisFolder0 = new IrisFolder("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent");
      irisFolder0.setId("$3wt#'`");
      String string0 = irisFolder0.getId();
      assertEquals("$3wt#'`", string0);
  }

  @Test(timeout = 4000)
  public void test2() throws Throwable {
      Thread.sleep(500);
      EmailMessage emailMessage0 = new EmailMessage("OUTBOX", "", "Q`1/=");
      emailMessage0.setId("");
      String string0 = emailMessage0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3_setId_null_then_value_onEmailMessage() throws Throwable {
      Thread.sleep(500);
      EmailMessage m = new EmailMessage();
      assertNull(m.getId());
      m.setId(null);
      assertNull(m.getId());
      m.setId("ID-1");
      assertEquals("ID-1", m.getId());
  }

  @Test(timeout = 4000)
  public void test4_newIrisFolder_hasNullId_untilSet() throws Throwable {
      Thread.sleep(500);
      IrisFolder f = new IrisFolder("INBOX");
      assertNull(f.getId());
      f.setId("F-001");
      assertEquals("F-001", f.getId());
  }

  @Test(timeout = 4000)
  public void test5_setId_twice_overwrites_onIrisFolder() throws Throwable {
      Thread.sleep(500);
      IrisFolder f = new IrisFolder("ANY");
      f.setId("A");
      assertEquals("A", f.getId());
      f.setId("B");
      assertEquals("B", f.getId());
  }

  @Test(timeout = 4000)
  public void test6_twoInstances_sameStringId_areNotEqualObjects() throws Throwable {
      Thread.sleep(500);
      IrisFolder f1 = new IrisFolder("X");
      IrisFolder f2 = new IrisFolder("Y");
      f1.setId("SAME");
      f2.setId("SAME");
      // برابری شیء به‌صورت پیش‌فرض بر اساس رفرنس است
      assertFalse(f1.equals(f2));
      assertEquals(f1.getId(), f2.getId());
  }

  @Test(timeout = 4000)
  public void test7_setId_whitespace_allowed() throws Throwable {
      Thread.sleep(500);
      EmailMessage m = new EmailMessage();
      m.setId("  ");
      assertEquals("  ", m.getId());
  }

  @Test(timeout = 4000)
  public void test8_setLongId_supported() throws Throwable {
      Thread.sleep(500);
      StringBuilder sb = new StringBuilder();
      for (int i = 0; i < 256; i++) { sb.append('x'); }
      String longId = sb.toString();

      IrisFolder f = new IrisFolder("Z");
      f.setId(longId);
      assertEquals(longId, f.getId());
  }

  @Test(timeout = 4000)
  public void test9_emailMessage_toString_usesIdFromFolderContent() throws Throwable {
      Thread.sleep(500);
      EmailMessage m = new EmailMessage("from@a", "to@b", "sub", "body");
      m.setId("MSG-42");
      String s = m.toString(); // قالب: "<id> - <from> - <subject> - <date>"
      assertTrue(s.startsWith("MSG-42 - "));
      assertTrue(s.contains("from@a"));
      assertTrue(s.contains("sub"));
  }

  // ---------------------- تست‌های افزوده شده ----------------------

  @Test(timeout = 4000)
  public void test10_setId_null_onIrisFolder() throws Throwable {
      Thread.sleep(500);
      IrisFolder f = new IrisFolder("INBOX");
      assertNull(f.getId());
      f.setId(null);
      assertNull(f.getId());
  }

  @Test(timeout = 4000)
  public void test11_emailMessage_setId_twice_overwrites() throws Throwable {
      Thread.sleep(500);
      EmailMessage m = new EmailMessage();
      m.setId("X");
      assertEquals("X", m.getId());
      m.setId("Y");
      assertEquals("Y", m.getId());
  }

  @Test(timeout = 4000)
  public void test12_emailMessage_toString_withoutId_safe() throws Throwable {
      Thread.sleep(500);
      EmailMessage m = new EmailMessage("a@a", "b@b", "S", "B");
      // بدون تعیین id
      String s = m.toString();
      assertNotNull(s);
      assertTrue(s.contains("a@a"));
      assertTrue(s.contains("S"));
  }

  @Test(timeout = 4000)
  public void test13_sameReference_isEqual() throws Throwable {
      Thread.sleep(500);
      IrisFolder f = new IrisFolder("N");
      f.setId("ID");
      assertTrue(f.equals(f)); // همان رفرنس باید برابر باشد
  }

  @Test(timeout = 4000)
  public void test14_setId_unicode_characters_supported_onEmailMessage() throws Throwable {
      Thread.sleep(500);
      EmailMessage m = new EmailMessage();
      String id = "شناسه-Δ-🔥";
      m.setId(id);
      assertEquals(id, m.getId());
  }

  @Test(timeout = 4000)
  public void test15_folder_setId_emptyString_allowed() throws Throwable {
      Thread.sleep(500);
      IrisFolder f = new IrisFolder("Z");
      f.setId("");
      assertEquals("", f.getId());
  }
}
