/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 23:25:27 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.exception;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.exception.EmailUncheckedException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class EmailUncheckedException_ESTest extends EmailUncheckedException_ESTest_scaffolding {

  // تاخیر نیم‌ثانیه‌ای قبل از هر تست (با timeout=4000ms کاملاً سازگار است)
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test0() throws Throwable {
      EmailUncheckedException emailUncheckedException0 = new EmailUncheckedException((String) null);
      assertNotNull(emailUncheckedException0);
  }

  @Test(timeout = 4000)
  public void test1() throws Throwable {
      MockThrowable mockThrowable0 = new MockThrowable("hy<)t@wr8g`d/5|");
      EmailUncheckedException emailUncheckedException0 = new EmailUncheckedException("hy<)t@wr8g`d/5|", mockThrowable0);
      assertEquals("hy<)t@wr8g`d/5|", emailUncheckedException0.getMessage());
      assertSame(mockThrowable0, emailUncheckedException0.getCause());
  }

  @Test(timeout = 4000)
  public void test2() throws Throwable {
      EmailUncheckedException emailUncheckedException0 = new EmailUncheckedException();
      EmailUncheckedException emailUncheckedException1 = new EmailUncheckedException("", emailUncheckedException0, true, false);
      assertFalse(emailUncheckedException1.equals((Object) emailUncheckedException0));
  }

  @Test(timeout = 4000)
  public void test3() throws Throwable {
      EmailUncheckedException emailUncheckedException0 = new EmailUncheckedException();
      EmailUncheckedException emailUncheckedException1 = new EmailUncheckedException(emailUncheckedException0);
      assertFalse(emailUncheckedException1.equals((Object) emailUncheckedException0));
  }

  @Test(timeout = 4000)
  public void test4_messageOnly_setsMessage_andNullCause() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException("boom");
      assertEquals("boom", ex.getMessage());
      assertNull(ex.getCause());
      String s = ex.toString();
      assertTrue(s.contains("EmailUncheckedException"));
      assertTrue(s.contains("boom"));
  }

  @Test(timeout = 4000)
  public void test5_causeOnly_setsCause_andMessageFromCauseToString() throws Throwable {
      Throwable cause = new Throwable("root");
      EmailUncheckedException ex = new EmailUncheckedException(cause);
      assertSame(cause, ex.getCause());
      assertEquals(cause.toString(), ex.getMessage());
  }

  @Test(timeout = 4000)
  public void test6_enableSuppression_false_preventsAddSuppressed() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException("m", null, false, true);
      try {
          ex.addSuppressed(new Exception("supp"));
          fail("Expected IllegalStateException when suppression disabled");
      } catch (IllegalStateException expected) {
          // ok
      }
  }

  @Test(timeout = 4000)
  public void test7_writableStackTrace_false_resultsEmptyStackTrace() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException("m", null, true, false);
      assertEquals(0, ex.getStackTrace().length);
      ex.fillInStackTrace();
      assertEquals(0, ex.getStackTrace().length);
  }

  @Test(timeout = 4000)
  public void test8_suppressed_default_isEmpty_andCanAddWhenEnabled() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException("x");
      assertNotNull(ex.getSuppressed());
      assertEquals(0, ex.getSuppressed().length);
      ex.addSuppressed(new Exception("s1"));
      assertEquals(1, ex.getSuppressed().length);
  }

  @Test(timeout = 4000)
  public void test9_fillInStackTrace_populatesWhenWritable() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException("m", null, true, true);
      ex.fillInStackTrace();
      StackTraceElement[] st = ex.getStackTrace();
      assertNotNull(st);
      assertTrue(st.length > 0);
  }

  @Test(timeout = 4000)
  public void test10_equals_basicObjectSemantics() throws Throwable {
      EmailUncheckedException a = new EmailUncheckedException("m");
      EmailUncheckedException b = new EmailUncheckedException("m");
      assertTrue(a.equals(a));
      assertFalse(a.equals(b));
      assertFalse(a.equals(null));
      assertFalse(a.equals("m"));
  }

  @Test(timeout = 4000)
  public void test11_nullMessage_constructorAllowed() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException((String) null);
      assertNull(ex.getMessage());
      assertNull(ex.getCause());
      assertTrue(ex.toString().contains("EmailUncheckedException"));
  }

  // ================= تست‌های افزوده‌شده =================

  @Test(timeout = 4000)
  public void test12_toString_containsClassName_evenWhenNoMessageAndNoCause() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException();
      String s = ex.toString();
      assertNotNull(s);
      assertTrue(s.contains("EmailUncheckedException"));
  }

  @Test(timeout = 4000)
  public void test13_constructor_messageAndCause_bothSet() throws Throwable {
      Throwable cause = new IllegalArgumentException("bad");
      EmailUncheckedException ex = new EmailUncheckedException("oops", cause);
      assertEquals("oops", ex.getMessage());
      assertSame(cause, ex.getCause());
  }

  @Test(timeout = 4000)
  public void test14_getLocalizedMessage_behaviour_withNullMessage() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException((String) null);
      assertNull(ex.getLocalizedMessage()); // معمولاً همان message است
  }

  @Test(timeout = 4000)
  public void test15_addSuppressed_multiple_whenEnabled() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException("x"); // suppression فعال
      ex.addSuppressed(new RuntimeException("s1"));
      ex.addSuppressed(new RuntimeException("s2"));
      Throwable[] sup = ex.getSuppressed();
      assertEquals(2, sup.length);
      assertEquals("s1", sup[0].getMessage());
      assertEquals("s2", sup[1].getMessage());
  }

  @Test(timeout = 4000)
  public void test16_hashCode_isCallable_andStableDuringLife() throws Throwable {
      EmailUncheckedException ex = new EmailUncheckedException("m");
      int h1 = ex.hashCode();
      int h2 = ex.hashCode();
      assertEquals(h1, h2);
  }

  @Test(timeout = 4000)
  public void test17_causeChaining_depthTwo() throws Throwable {
      Throwable inner = new RuntimeException("inner");
      Throwable outer = new RuntimeException("outer", inner);
      EmailUncheckedException ex = new EmailUncheckedException("top", outer);
      assertSame(outer, ex.getCause());
      assertSame(inner, ex.getCause().getCause());
  }
}
