/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 21:06:04 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.Main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.MainProgram;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MainProgram_ESTest extends MainProgram_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Thread.sleep(500);
      MainProgram mainProgram0 = new MainProgram();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Thread.sleep(500);
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        MainProgram.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.MainProgram", e);
      } catch (ExceptionInInitializerError e) {
         // acceptable for this environment
      }
  }

  // ---------------------- تست‌های افزوده‌شده ----------------------

  @Test(timeout = 4000)
  public void test2_main_withEmptyArgs_expectNoClassDefOrInitError() throws Throwable {
      Thread.sleep(500);
      String[] args = new String[0];
      try {
          MainProgram.main(args);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.MainProgram", e);
      } catch (ExceptionInInitializerError e) {
          // acceptable
      }
  }

  @Test(timeout = 4000)
  public void test3_main_withNullArgs_expectNoClassDefOrInitError() throws Throwable {
      Thread.sleep(500);
      try {
          MainProgram.main((String[]) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.MainProgram", e);
      } catch (ExceptionInInitializerError e) {
          // acceptable
      }
  }

  @Test(timeout = 4000)
  public void test4_main_withHelpFlag_handlesOrErrors() throws Throwable {
      Thread.sleep(500);
      String[] args = new String[] {"--help"};
      try {
          MainProgram.main(args);
          // اگر بدون وابستگی هم هندل شد، همین‌قدر که خطا ندهد کافی است
          assertTrue(true);
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.MainProgram", e);
      } catch (ExceptionInInitializerError e) {
          // acceptable
      }
  }

  @Test(timeout = 4000)
  public void test5_main_withVersionFlag_handlesOrErrors() throws Throwable {
      Thread.sleep(500);
      String[] args = new String[] {"--version"};
      try {
          MainProgram.main(args);
          assertTrue(true);
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.MainProgram", e);
      } catch (ExceptionInInitializerError e) {
          // acceptable
      }
  }

  @Test(timeout = 4000)
  public void test6_constructor_toString_notNull() throws Throwable {
      Thread.sleep(500);
      MainProgram mp = new MainProgram();
      assertNotNull(mp.toString());
  }

  @Test(timeout = 4000)
  public void test7_main_withUnknownFlags_expectNoClassDefOrInitError() throws Throwable {
      Thread.sleep(500);
      String[] args = new String[] {"-x", "-y"};
      try {
          MainProgram.main(args);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.MainProgram", e);
      } catch (ExceptionInInitializerError e) {
          // acceptable
      }
  }
}
