/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 20:46:02 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model;

import org.junit.Test;
import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.AddressBookEntry;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AddressBookEntry_ESTest extends AddressBookEntry_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای قبل از اجرای هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry((String) null, (String) null);
      String string0 = addressBookEntry0.getNick();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry("\"w$", "\"w$");
      String string0 = addressBookEntry0.getNick();
      assertEquals("\"w$", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry("", "HZ8oB'Gm,aD=Q2h");
      addressBookEntry0.setId("&iVTV9(\u007fX*l");
      addressBookEntry0.getId();
      assertEquals("", addressBookEntry0.getNick());
      assertEquals("HZ8oB'Gm,aD=Q2h", addressBookEntry0.getAddress());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry();
      addressBookEntry0.setId("");
      String string0 = addressBookEntry0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry((String) null, (String) null);
      addressBookEntry0.setAddress("");
      String string0 = addressBookEntry0.getAddress();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry("", "HZ8oB'Gm,aD=Q2h");
      String string0 = addressBookEntry0.getAddress();
      assertEquals("", addressBookEntry0.getNick());
      assertEquals("HZ8oB'Gm,aD=Q2h", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry();
      String string0 = addressBookEntry0.getAddress();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry("", "HZ8oB'Gm,aD=Q2h");
      addressBookEntry0.getId();
      assertEquals("HZ8oB'Gm,aD=Q2h", addressBookEntry0.getAddress());
      assertEquals("", addressBookEntry0.getNick());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry("", "HZ8oB'Gm,aD=Q2h");
      assertEquals("", addressBookEntry0.getNick());
      
      addressBookEntry0.setNick("");
      assertEquals("HZ8oB'Gm,aD=Q2h", addressBookEntry0.getAddress());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      AddressBookEntry addressBookEntry0 = new AddressBookEntry("", "HZ8oB'Gm,aD=Q2h");
      String string0 = addressBookEntry0.getNick();
      assertEquals("", string0);
      assertEquals("HZ8oB'Gm,aD=Q2h", addressBookEntry0.getAddress());
  }

  @Test(timeout = 4000)
  public void test10_setNickToNull_afterNonNull() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("ali", "ali@example.com");
      e.setNick(null);
      assertNull(e.getNick());
      assertEquals("ali@example.com", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test11_setAddressToNull_afterNonNull() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("n1", "addr");
      e.setAddress(null);
      assertNull(e.getAddress());
      assertEquals("n1", e.getNick());
  }

  @Test(timeout = 4000)
  public void test12_mutateNickAndAddress_multipleTimes() throws Throwable {
      AddressBookEntry e = new AddressBookEntry();
      e.setNick("a");
      e.setAddress("b");
      assertEquals("a", e.getNick());
      assertEquals("b", e.getAddress());
      e.setNick("c");
      e.setAddress("d");
      assertEquals("c", e.getNick());
      assertEquals("d", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test13_defaultIdIsNull_thenSetNonNull() throws Throwable {
      AddressBookEntry e = new AddressBookEntry();
      assertNull(e.getId());
      e.setId("UUID-1");
      assertEquals("UUID-1", e.getId());
  }

  @Test(timeout = 4000)
  public void test14_constructorNonNull_thenOverrideWithSetters() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("n", "a@b.com");
      e.setNick("newN");
      e.setAddress("new@addr.com");
      assertEquals("newN", e.getNick());
      assertEquals("new@addr.com", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test15_whitespaceValuesAreAcceptedAsIs() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("  ", "  ");
      assertEquals("  ", e.getNick());
      assertEquals("  ", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test16_longValuesAreStoredCompletely() throws Throwable {
      String longNick = new String(new char[256]).replace('\0', 'n');
      String longAddr = new String(new char[512]).replace('\0', 'a');
      AddressBookEntry e = new AddressBookEntry(longNick, longAddr);
      assertEquals(256, e.getNick().length());
      assertEquals(512, e.getAddress().length());
  }

  @Test(timeout = 4000)
  public void test17_unicodeValues() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("علی", "ایمیل");
      assertEquals("علی", e.getNick());
      assertEquals("ایمیل", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test18_twoInstancesAreIndependent() throws Throwable {
      AddressBookEntry e1 = new AddressBookEntry("a", "x");
      AddressBookEntry e2 = new AddressBookEntry("b", "y");
      e1.setNick("a1");
      e2.setAddress("y2");
      assertEquals("a1", e1.getNick());
      assertEquals("x", e1.getAddress());
      assertEquals("b", e2.getNick());
      assertEquals("y2", e2.getAddress());
  }

  @Test(timeout = 4000)
  public void test19_setIdNull_overwritesPreviousValue() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("n", "a");
      e.setId("ID-123");
      assertEquals("ID-123", e.getId());
      e.setId(null);
      assertNull(e.getId());
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  @Test(timeout = 4000)
  public void test20_setNickEmptyThenNonEmpty() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("", "addr");
      assertEquals("", e.getNick());
      e.setNick("Zed");
      assertEquals("Zed", e.getNick());
      assertEquals("addr", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test21_setAddressEmptyThenNullThenNonEmpty() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("nick", "");
      assertEquals("", e.getAddress());
      e.setAddress(null);
      assertNull(e.getAddress());
      e.setAddress("final@domain");
      assertEquals("final@domain", e.getAddress());
      assertEquals("nick", e.getNick());
  }

  @Test(timeout = 4000)
  public void test22_constructorNulls_thenSetBoth() throws Throwable {
      AddressBookEntry e = new AddressBookEntry(null, null);
      assertNull(e.getNick());
      assertNull(e.getAddress());
      e.setNick("n");
      e.setAddress("a");
      assertEquals("n", e.getNick());
      assertEquals("a", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test23_setIdEmptyThenNonEmpty() throws Throwable {
      AddressBookEntry e = new AddressBookEntry();
      e.setId("");
      assertEquals("", e.getId());
      e.setId("X-1");
      assertEquals("X-1", e.getId());
  }

  @Test(timeout = 4000)
  public void test24_unicodeEmojiValues() throws Throwable {
      AddressBookEntry e = new AddressBookEntry("😀", "📧");
      assertEquals("😀", e.getNick());
      assertEquals("📧", e.getAddress());
      e.setNick("🧪");
      e.setAddress("✉️");
      assertEquals("🧪", e.getNick());
      assertEquals("✉️", e.getAddress());
  }

  @Test(timeout = 4000)
  public void test25_longId_isStoredCompletely() throws Throwable {
      String longId = new String(new char[300]).replace('\0', 'I');
      AddressBookEntry e = new AddressBookEntry();
      e.setId(longId);
      assertEquals(300, e.getId().length());
  }

  @Test(timeout = 4000)
  public void test26_multipleSequentialMutations_keepLatestValues() throws Throwable {
      AddressBookEntry e = new AddressBookEntry();
      e.setNick("n1");
      e.setAddress("a1");
      e.setNick("n2");
      e.setAddress("a2");
      e.setNick("n3");
      e.setAddress("a3");
      assertEquals("n3", e.getNick());
      assertEquals("a3", e.getAddress());
  }

}
