/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 23:30:11 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model;

import org.junit.Test;
import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.EmailMessage;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.IrisFolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class EmailMessage_ESTest extends EmailMessage_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست */
  private void delay() {
      try { Thread.sleep(500L); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", "W[A\"", "", "U<MBU|e^80K*ZUA1a%", "", "");
      assertEquals("W[A\"", emailMessage0.getTo());

      emailMessage0.setTo((String) null);
      emailMessage0.getTo();
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", emailMessage0.getFrom());
      assertEquals("", emailMessage0.getCc());
      assertEquals("", emailMessage0.getSubject());
      assertEquals("", emailMessage0.getMessage());
      assertEquals("U<MBU|e^80K*ZUA1a%", emailMessage0.getBcc());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("%IyWR0p", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", "g3x X\"k");
      String string0 = emailMessage0.getTo();
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", emailMessage0.getSubject());
      assertEquals("%IyWR0p", string0);
      assertNotNull(string0);
      assertEquals("g3x X\"k", emailMessage0.getMessage());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      String string0 = emailMessage0.getSubject();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      String string0 = emailMessage0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", "W[A\"", "", "U<MBU|e^80K*ZUA1a%", "", "");
      String string0 = emailMessage0.getMessage();
      assertEquals("W[A\"", emailMessage0.getTo());
      assertEquals("", string0);
      assertEquals("", emailMessage0.getSubject());
      assertEquals("U<MBU|e^80K*ZUA1a%", emailMessage0.getBcc());
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", emailMessage0.getFrom());
      assertEquals("", emailMessage0.getCc());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      String string0 = emailMessage0.getFrom();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("%IyWR0p", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", "g3x X\"k");
      emailMessage0.setFrom("%IyWR0p");
      emailMessage0.getFrom();
      assertEquals("%IyWR0p", emailMessage0.getTo());
      assertEquals("g3x X\"k", emailMessage0.getMessage());
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", emailMessage0.getSubject());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      IrisFolder irisFolder0 = new IrisFolder((String) null);
      emailMessage0.setFolder(irisFolder0);
      IrisFolder irisFolder1 = emailMessage0.getFolder();
      assertSame(irisFolder1, irisFolder0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("", "", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage");
      emailMessage0.getDate();
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", emailMessage0.getSubject());
      assertEquals("", emailMessage0.getFrom());
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", emailMessage0.getMessage());
      assertEquals("", emailMessage0.getTo());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("", "", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage");
      String string0 = emailMessage0.getCc();
      assertEquals("", emailMessage0.getTo());
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", emailMessage0.getMessage());
      assertEquals("", emailMessage0.getFrom());
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", emailMessage0.getSubject());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      assertEquals("", emailMessage0.getCc());

      emailMessage0.setCc("wP LLUp~&F");
      emailMessage0.getCc();
      assertEquals("", emailMessage0.getSubject());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      String string0 = emailMessage0.getBcc();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", "W[A\"", "", "U<MBU|e^80K*ZUA1a%", "", "");
      String string0 = emailMessage0.getBcc();
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.FolderContent", emailMessage0.getFrom());
      assertEquals("", emailMessage0.getCc());
      assertEquals("W[A\"", emailMessage0.getTo());
      assertEquals("", emailMessage0.getMessage());
      assertEquals("U<MBU|e^80K*ZUA1a%", string0);
      assertEquals("", emailMessage0.getSubject());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage("%IyWR0p", "irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", "g3x X\"k");
      String string0 = emailMessage0.getSubject();
      assertEquals("%IyWR0p", emailMessage0.getTo());
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", string0);
      assertEquals("g3x X\"k", emailMessage0.getMessage());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      emailMessage0.getDate();
      assertEquals("", emailMessage0.getFrom());
      assertEquals("", emailMessage0.getCc());
      assertEquals("", emailMessage0.getTo());
      assertEquals("~<:zgw|wy", emailMessage0.getMessage());
      assertEquals("", emailMessage0.getBcc());
      assertEquals("", emailMessage0.getSubject());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      String string0 = emailMessage0.getFrom();
      assertEquals("", emailMessage0.getSubject());
      assertEquals("", emailMessage0.getBcc());
      assertEquals("", emailMessage0.getTo());
      assertEquals("~<:zgw|wy", emailMessage0.getMessage());
      assertEquals("", emailMessage0.getCc());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate(0L);
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", mockDate0, irisFolder0);
      assertNull(emailMessage0.getId());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      IrisFolder irisFolder0 = emailMessage0.getFolder();
      assertNull(irisFolder0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      String string0 = emailMessage0.getMessage();
      assertEquals("~<:zgw|wy", string0);
      assertEquals("", emailMessage0.getTo());
      assertEquals("", emailMessage0.getCc());
      assertEquals("", emailMessage0.getFrom());
      assertEquals("", emailMessage0.getSubject());
      assertEquals("", emailMessage0.getBcc());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      String string0 = emailMessage0.getCc();
      assertEquals("~<:zgw|wy", emailMessage0.getMessage());
      assertEquals("", emailMessage0.getFrom());
      assertEquals("", emailMessage0.getTo());
      assertEquals("", string0);
      assertEquals("", emailMessage0.getBcc());
      assertEquals("", emailMessage0.getSubject());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      emailMessage0.setDate(mockDate0);
      assertEquals("", emailMessage0.getFrom());
      assertEquals("", emailMessage0.getCc());
      assertEquals("", emailMessage0.getTo());
      assertEquals("", emailMessage0.getBcc());
      assertEquals("", emailMessage0.getSubject());
      assertEquals("~<:zgw|wy", emailMessage0.getMessage());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      emailMessage0.setMessage("_SJ`<Eo~IEc-4HXkm<");
      assertNull(emailMessage0.getId());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      emailMessage0.setBcc("3d>)_p8Z;P*=e>");
      assertNull(emailMessage0.getId());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      String string0 = emailMessage0.getBcc();
      assertEquals("", emailMessage0.getCc());
      assertEquals("", emailMessage0.getTo());
      assertEquals("", emailMessage0.getFrom());
      assertEquals("", string0);
      assertEquals("~<:zgw|wy", emailMessage0.getMessage());
      assertEquals("", emailMessage0.getSubject());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      delay();
      MockDate mockDate0 = new MockDate();
      IrisFolder irisFolder0 = new IrisFolder("");
      EmailMessage emailMessage0 = new EmailMessage("", "", "", "", "", "~<:zgw|wy", mockDate0, irisFolder0);
      String string0 = emailMessage0.getTo();
      assertEquals("~<:zgw|wy", emailMessage0.getMessage());
      assertEquals("", emailMessage0.getCc());
      assertEquals("", emailMessage0.getBcc());
      assertEquals("", emailMessage0.getSubject());
      assertEquals("", string0);
      assertEquals("", emailMessage0.getFrom());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      emailMessage0.setSubject("");
      String string0 = emailMessage0.getSubject();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      delay();
      EmailMessage emailMessage0 = new EmailMessage();
      String string0 = emailMessage0.toString();
      assertEquals("null - null - null - null", string0);
  }

  @Test(timeout = 4000)
  public void test27_constructor4Args_setsCoreFields_andLeavesOthersNull()  throws Throwable  {
      delay();
      EmailMessage m = new EmailMessage("from@x", "to@y", "subj", "body");
      assertEquals("from@x", m.getFrom());
      assertEquals("to@y",   m.getTo());
      assertEquals("subj",   m.getSubject());
      assertEquals("body",   m.getMessage());
      assertNull(m.getCc());
      assertNull(m.getBcc());
      assertNull(m.getDate());
      assertNull(m.getFolder());
  }

  @Test(timeout = 4000)
  public void test28_constructorAllFields_setsEverything()  throws Throwable  {
      delay();
      MockDate d = new MockDate(123456789L);
      IrisFolder f = new IrisFolder("INBOX");
      EmailMessage m = new EmailMessage("from", "to", "cc", "bcc", "s", "msg", d, f);
      assertEquals("from", m.getFrom());
      assertEquals("to",   m.getTo());
      assertEquals("cc",   m.getCc());
      assertEquals("bcc",  m.getBcc());
      assertEquals("s",    m.getSubject());
      assertEquals("msg",  m.getMessage());
      assertSame(d, m.getDate());
      assertSame(f, m.getFolder());
  }

  @Test(timeout = 4000)
  public void test29_constructor3Args_fromIsNull()  throws Throwable  {
      delay();
      EmailMessage m = new EmailMessage("to-only", "SUB", "BODY");
      assertNull(m.getFrom());
      assertEquals("to-only", m.getTo());
      assertEquals("SUB",     m.getSubject());
      assertEquals("BODY",    m.getMessage());
  }

  @Test(timeout = 4000)
  public void test30_setters_updateValues()  throws Throwable  {
      delay();
      EmailMessage m = new EmailMessage();
      m.setFrom("a@b");
      m.setTo("c@d");
      m.setCc("cc@x");
      m.setBcc("bcc@y");
      m.setSubject("S");
      m.setMessage("M");
      assertEquals("a@b",  m.getFrom());
      assertEquals("c@d",  m.getTo());
      assertEquals("cc@x", m.getCc());
      assertEquals("bcc@y",m.getBcc());
      assertEquals("S",    m.getSubject());
      assertEquals("M",    m.getMessage());
  }

  @Test(timeout = 4000)
  public void test31_date_setNull_thenSetRealDate()  throws Throwable  {
      delay();
      EmailMessage m = new EmailMessage();
      assertNull(m.getDate());
      m.setDate(null);
      assertNull(m.getDate());
      MockDate d = new MockDate();
      m.setDate(d);
      assertSame(d, m.getDate());
  }

  @Test(timeout = 4000)
  public void test32_folder_setNull_thenSetFolder()  throws Throwable  {
      delay();
      EmailMessage m = new EmailMessage();
      assertNull(m.getFolder());
      m.setFolder(null);
      assertNull(m.getFolder());
      IrisFolder f = new IrisFolder("F");
      m.setFolder(f);
      assertSame(f, m.getFolder());
  }

  @Test(timeout = 4000)
  public void test33_constructorWithDateAndFolder_nullDateIsKept()  throws Throwable  {
      delay();
      IrisFolder f = new IrisFolder("Z");
      EmailMessage m = new EmailMessage("from", "to", "sub", "msg", (java.util.Date) null, f);
      assertEquals("from", m.getFrom());
      assertEquals("to",   m.getTo());
      assertEquals("sub",  m.getSubject());
      assertEquals("msg",  m.getMessage());
      assertNull(m.getDate());
      assertSame(f, m.getFolder());
  }

  @Test(timeout = 4000)
  public void test34_ccAndBcc_allowNullAndOverwrite()  throws Throwable  {
      delay();
      EmailMessage m = new EmailMessage();
      assertNull(m.getCc());
      assertNull(m.getBcc());
      m.setCc(null);
      m.setBcc(null);
      assertNull(m.getCc());
      assertNull(m.getBcc());
      m.setCc("C1");
      m.setBcc("B1");
      assertEquals("C1", m.getCc());
      assertEquals("B1", m.getBcc());
  }

  @Test(timeout = 4000)
  public void test35_toString_containsFromSubjectAndDateMarker()  throws Throwable  {
      delay();
      EmailMessage m = new EmailMessage();
      m.setFrom("alice");
      m.setSubject("hello");
      MockDate d = new MockDate(0L);
      m.setDate(d);
      String s = m.toString();
      // قالب: "<id> - <from> - <subject> - <date>"
      assertTrue(s.startsWith("null - "));
      assertTrue(s.contains("alice"));
      assertTrue(s.contains("hello"));
      // از مقایسهٔ دقیق تاریخ خودداری می‌کنیم (وابسته به timezone)، همین که رشته خالی نباشد کافی است
      assertTrue(s.endsWith(m.getDate().toString()));
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test36_setToNull_setsFieldToNull() throws Throwable {
      delay();
      EmailMessage m = new EmailMessage("from", "to", "subj", "msg");
      m.setTo(null);
      assertNull(m.getTo());
  }

  @Test(timeout = 4000)
  public void test37_unicodeFields_preserved() throws Throwable {
      delay();
      EmailMessage m = new EmailMessage();
      String subj = "سلام 🌟";
      String body = "بدنهٔ پیام — تست ایموجی 😊 و حروف فارسی";
      m.setSubject(subj);
      m.setMessage(body);
      assertEquals(subj, m.getSubject());
      assertEquals(body, m.getMessage());
  }

  @Test(timeout = 4000)
  public void test38_longMessage_preservedLength() throws Throwable {
      delay();
      EmailMessage m = new EmailMessage();
      StringBuilder sb = new StringBuilder();
      for (int i = 0; i < 10000; i++) sb.append('x');
      String longMsg = sb.toString();
      m.setMessage(longMsg);
      assertEquals(10000, m.getMessage().length());
      assertSame(longMsg, m.getMessage());
  }

  @Test(timeout = 4000)
  public void test39_toString_updatesAfterFieldChanges() throws Throwable {
      delay();
      EmailMessage m = new EmailMessage();
      String before = m.toString();
      m.setFrom("f");
      m.setSubject("s");
      m.setDate(new MockDate(42L));
      String after = m.toString();
      assertNotEquals(before, after);
      assertTrue(after.contains("f"));
      assertTrue(after.contains("s"));
  }

  @Test(timeout = 4000)
  public void test40_dateReference_mutationVisible() throws Throwable {
      delay();
      EmailMessage m = new EmailMessage();
      MockDate d = new MockDate(100L);
      m.setDate(d);
      d.setTime(200L); // Date mutable
      assertEquals(200L, m.getDate().getTime());
  }

  @Test(timeout = 4000)
  public void test41_constructorWithDateAndFolder_folderNullAllowed() throws Throwable {
      delay();
      MockDate d = new MockDate(777L);
      EmailMessage m = new EmailMessage("from", "to", "sub", "msg", d, (IrisFolder) null);
      assertSame(d, m.getDate());
      assertNull(m.getFolder());
  }

  @Test(timeout = 4000)
  public void test42_ccBcc_emptyStringsPersist() throws Throwable {
      delay();
      EmailMessage m = new EmailMessage();
      m.setCc("");
      m.setBcc("");
      assertEquals("", m.getCc());
      assertEquals("", m.getBcc());
  }
}
