/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 30 22:37:56 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.EmailMessage;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.IrisFolder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class IrisFolder_ESTest extends IrisFolder_ESTest_scaffolding {

  // 0.5s delay before each test
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IrisFolder irisFolder0 = new IrisFolder("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", "uvns");
      assertEquals("uvns", irisFolder0.getName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IrisFolder irisFolder0 = new IrisFolder("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage");
      String string0 = irisFolder0.getName();
      assertNotNull(string0);
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IrisFolder irisFolder0 = new IrisFolder("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage");
      irisFolder0.addElement(irisFolder0);
      irisFolder0.getContents();
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", irisFolder0.getName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IrisFolder irisFolder0 = new IrisFolder("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage");
      irisFolder0.getContents();
      assertEquals("irisdeltaj.simplerelational.br.unb.cic.iris.core.model.EmailMessage", irisFolder0.getName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IrisFolder irisFolder0 = new IrisFolder();
      EmailMessage emailMessage0 = new EmailMessage();
      irisFolder0.addElement(emailMessage0);
      assertEquals("", irisFolder0.getName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      IrisFolder irisFolder0 = new IrisFolder();
      irisFolder0.setName((String) null);
      String string0 = irisFolder0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      IrisFolder irisFolder0 = new IrisFolder();
      String string0 = irisFolder0.getName();
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7_constants_haveExpectedValues() throws Throwable {
      assertEquals("INBOX", IrisFolder.INBOX);
      assertEquals("OUTBOX", IrisFolder.OUTBOX);
  }

  @Test(timeout = 4000)
  public void test8_constructor_idAndName_setsBoth() throws Throwable {
      IrisFolder f = new IrisFolder("ID-7", "Inbox");
      assertEquals("Inbox", f.getName());
      assertEquals("ID-7", f.getId());
  }

  @Test(timeout = 4000)
  public void test9_getContents_isLiveList_andAcceptsExternalAdd() throws Throwable {
      IrisFolder f = new IrisFolder("Mailbox");
      assertEquals(0, f.getContents().size());
      f.getContents().add(new EmailMessage());
      assertEquals(1, f.getContents().size());
  }

  @Test(timeout = 4000)
  public void test10_addElement_acceptsNull_andStoresIt() throws Throwable {
      IrisFolder f = new IrisFolder("X");
      f.addElement(null);
      assertEquals(1, f.getContents().size());
      assertNull(f.getContents().get(0));
  }

  @Test(timeout = 4000)
  public void test11_addElement_preservesInsertionOrder() throws Throwable {
      IrisFolder f = new IrisFolder("Y");
      EmailMessage m1 = new EmailMessage("from1", "to1", "s1", "b1");
      EmailMessage m2 = new EmailMessage("from2", "to2", "s2", "b2");
      f.addElement(m1);
      f.addElement(m2);
      assertEquals(2, f.getContents().size());
      assertSame(m1, f.getContents().get(0));
      assertSame(m2, f.getContents().get(1));
  }

  @Test(timeout = 4000)
  public void test12_setName_canChangeMultipleTimes() throws Throwable {
      IrisFolder f = new IrisFolder();
      assertEquals("", f.getName());
      f.setName("Work");
      assertEquals("Work", f.getName());
      f.setName("");
      assertEquals("", f.getName());
  }

  @Test(timeout = 4000)
  public void test13_addManyElements_scalesLinearly() throws Throwable {
      IrisFolder f = new IrisFolder("Bulk");
      for (int i = 0; i < 50; i++) {
          f.addElement(new EmailMessage("f"+i, "t"+i, "s"+i, "b"+i));
      }
      assertEquals(50, f.getContents().size());
      assertTrue(f.getContents().get(0) instanceof EmailMessage);
      assertTrue(f.getContents().get(49) instanceof EmailMessage);
  }

  // ===== Added tests =====

  @Test(timeout = 4000)
  public void test14_getContents_returnsSameInstanceEachCall() throws Throwable {
      IrisFolder f = new IrisFolder("Stable");
      assertSame(f.getContents(), f.getContents());
  }

  @Test(timeout = 4000)
  public void test15_modifyLiveList_removeReflectsInFolder() throws Throwable {
      IrisFolder f = new IrisFolder("Live");
      f.addElement(new EmailMessage());
      assertEquals(1, f.getContents().size());
      f.getContents().remove(0);
      assertEquals(0, f.getContents().size());
  }

  @Test(timeout = 4000)
  public void test16_addDuplicateElements_allowed() throws Throwable {
      IrisFolder f = new IrisFolder("Dup");
      EmailMessage m = new EmailMessage();
      f.addElement(m);
      f.addElement(m);
      assertEquals(2, f.getContents().size());
      assertSame(m, f.getContents().get(0));
      assertSame(m, f.getContents().get(1));
  }

  @Test(timeout = 4000)
  public void test17_mixedTypes_canBeStored() throws Throwable {
      IrisFolder f = new IrisFolder("Mixed");
      EmailMessage m = new EmailMessage("a","b","s","body");
      IrisFolder child = new IrisFolder("child");
      f.addElement(m);
      f.addElement(child);
      assertEquals(2, f.getContents().size());
      assertTrue(f.getContents().get(0) instanceof EmailMessage);
      assertTrue(f.getContents().get(1) instanceof IrisFolder);
  }

  @Test(timeout = 4000)
  public void test18_defaultConstructor_initialState() throws Throwable {
      IrisFolder f = new IrisFolder();
      assertEquals("", f.getName());
      assertNotNull(f.getContents());
      assertTrue(f.getContents().isEmpty());
  }

  @Test(timeout = 4000)
  public void test19_setName_acceptsUnicode() throws Throwable {
      IrisFolder f = new IrisFolder();
      f.setName("نامه‌ها 📬");
      assertEquals("نامه‌ها 📬", f.getName());
  }
}
