/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 21:05:36 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.EmailMessage;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.IrisFolder;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.Tag;

import java.util.Date;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.Iterator;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class Tag_ESTest extends Tag_ESTest_scaffolding {

  // تاخیر نیم‌ثانیه‌ای قبل از هر تست (با @Test(timeout=4000) سازگار است)
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tag tag0 = new Tag((String) null);
      assertNull(tag0.getName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Tag tag0 = new Tag("i:R@p(bu}U{", "i:R@p(bu}U{");
      String string0 = tag0.getName();
      assertEquals("i:R@p(bu}U{", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Tag tag0 = new Tag("OUTBOX", "-Px");
      assertEquals("-Px", tag0.getName());
      tag0.setName("");
      tag0.getName();
      assertEquals("OUTBOX", tag0.getId());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Tag tag0 = new Tag();
      LinkedHashSet<EmailMessage> linkedHashSet0 = new LinkedHashSet<EmailMessage>();
      tag0.setMessages(linkedHashSet0);
      Set<EmailMessage> set0 = tag0.getMessages();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Tag tag0 = new Tag();
      tag0.setId("~1-@4]7iR>'O");
      String string0 = tag0.getId();
      assertEquals("~1-@4]7iR>'O", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Tag tag0 = new Tag();
      tag0.setId("");
      String string0 = tag0.getId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Tag tag0 = new Tag();
      LinkedHashSet<EmailMessage> linkedHashSet0 = new LinkedHashSet<EmailMessage>();
      tag0.setMessages(linkedHashSet0);
      IrisFolder irisFolder0 = new IrisFolder((String) null);
      EmailMessage emailMessage0 = new EmailMessage((String) null, (String) null, "[>ro2@48=V5", (String) null, "", (String) null, (Date) null, irisFolder0);
      linkedHashSet0.add(emailMessage0);
      Set<EmailMessage> set0 = tag0.getMessages();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Tag tag0 = new Tag();
      String string0 = tag0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Tag tag0 = new Tag();
      Set<EmailMessage> set0 = tag0.getMessages();
      assertNull(set0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Tag tag0 = new Tag();
      String string0 = tag0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10() throws Throwable {
      Tag tag = new Tag("ID-1", "");
      assertEquals("ID-1", tag.getId());
      assertEquals("", tag.getName());
  }

  @Test(timeout = 4000)
  public void test11() throws Throwable {
      Tag tag = new Tag("t1");
      assertEquals("t1", tag.getName());
      tag.setName((String) null);
      assertNull(tag.getName());
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
      Tag tag = new Tag();
      LinkedHashSet<EmailMessage> backing = new LinkedHashSet<EmailMessage>();
      tag.setMessages(backing);
      assertSame(backing, tag.getMessages());

      IrisFolder folder = new IrisFolder("inbox");
      EmailMessage msg = new EmailMessage("a@b.c", "c@d.e", "subj", "body", (Date) null, folder);
      backing.add(msg);
      assertEquals(1, tag.getMessages().size());
      assertTrue(tag.getMessages().contains(msg));
  }

  @Test(timeout = 4000)
  public void test13() throws Throwable {
      Tag tag = new Tag();
      tag.setMessages((Set<EmailMessage>) null);
      assertNull(tag.getMessages());
  }

  @Test(timeout = 4000)
  public void test14() throws Throwable {
      Tag tag = new Tag("news");
      assertNull(tag.getId());
      assertEquals("news", tag.getName());
  }

  @Test(timeout = 4000)
  public void test15() throws Throwable {
      Tag tag = new Tag();
      tag.setId("XYZ");
      tag.setName("hot");
      assertEquals("XYZ", tag.getId());
      assertEquals("hot", tag.getName());
  }

  @Test(timeout = 4000)
  public void test16() throws Throwable {
      Tag tag = new Tag();
      assertNull(tag.getMessages());
      LinkedHashSet<EmailMessage> set = new LinkedHashSet<EmailMessage>();
      tag.setMessages(set);
      assertNotNull(tag.getMessages());
      assertTrue(tag.getMessages().isEmpty());
  }

  @Test(timeout = 4000)
  public void test17() throws Throwable {
      Tag tag = new Tag("ID2", "work");
      LinkedHashSet<EmailMessage> set = new LinkedHashSet<EmailMessage>();
      tag.setMessages(set);

      IrisFolder folder = new IrisFolder("inbox");
      EmailMessage m1 = new EmailMessage("from@ex.com", "to@ex.com", "s", "b", (Date) null, folder);
      EmailMessage m2 = new EmailMessage("from@ex.com", "to@ex.com", "s", "b", (Date) null, folder);

      set.add(m1);
      set.add(m1);
      set.add(m2);

      assertEquals(2, tag.getMessages().size());
      assertTrue(tag.getMessages().contains(m1));
      assertTrue(tag.getMessages().contains(m2));
  }

  // ========================= تست‌های افزوده‌شده =========================

  @Test(timeout = 4000)
  public void test18_defaultConstructor_allFieldsNull() throws Throwable {
      Tag tag = new Tag();
      assertNull(tag.getId());
      assertNull(tag.getName());
      assertNull(tag.getMessages());
  }

  @Test(timeout = 4000)
  public void test19_changeIdAndNameMultipleTimes() throws Throwable {
      Tag tag = new Tag();
      tag.setId("A");
      tag.setName("N1");
      assertEquals("A", tag.getId());
      assertEquals("N1", tag.getName());

      tag.setId("B");
      tag.setName("N2");
      assertEquals("B", tag.getId());
      assertEquals("N2", tag.getName());

      tag.setName(null);
      assertNull(tag.getName());
      assertEquals("B", tag.getId());
  }

  @Test(timeout = 4000)
  public void test20_messages_preserveInsertionOrder_whenLinkedHashSet() throws Throwable {
      Tag tag = new Tag("tid", "tname");
      LinkedHashSet<EmailMessage> s = new LinkedHashSet<EmailMessage>();
      tag.setMessages(s);

      IrisFolder f = new IrisFolder("inb");
      EmailMessage a = new EmailMessage("fa", "ta", "sa", "ba", (Date) null, f);
      EmailMessage b = new EmailMessage("fb", "tb", "sb", "bb", (Date) null, f);
      EmailMessage c = new EmailMessage("fc", "tc", "sc", "bc", (Date) null, f);

      s.add(a);
      s.add(b);
      s.add(c);

      Iterator<EmailMessage> it = tag.getMessages().iterator();
      assertSame(a, it.next());
      assertSame(b, it.next());
      assertSame(c, it.next());
      assertFalse(it.hasNext());
  }

  @Test(timeout = 4000)
  public void test21_messages_acceptsNullElement_inBackingSet() throws Throwable {
      Tag tag = new Tag();
      LinkedHashSet<EmailMessage> s = new LinkedHashSet<EmailMessage>();
      tag.setMessages(s);

      s.add(null);
      assertTrue(tag.getMessages().contains(null));
      assertEquals(1, tag.getMessages().size());
  }

  @Test(timeout = 4000)
  public void test22_replaceMessagesReference_refChangeVisible() throws Throwable {
      Tag tag = new Tag();
      LinkedHashSet<EmailMessage> s1 = new LinkedHashSet<EmailMessage>();
      LinkedHashSet<EmailMessage> s2 = new LinkedHashSet<EmailMessage>();

      tag.setMessages(s1);
      assertSame(s1, tag.getMessages());

      tag.setMessages(s2);
      assertSame(s2, tag.getMessages());
      assertNotSame(s1, tag.getMessages());
  }

  @Test(timeout = 4000)
  public void test23_largeMessagesSet_sizeCorrect() throws Throwable {
      Tag tag = new Tag("bulk", "bulkName");
      LinkedHashSet<EmailMessage> s = new LinkedHashSet<EmailMessage>();
      tag.setMessages(s);

      IrisFolder f = new IrisFolder("F");
      for (int i = 0; i < 200; i++) {
          s.add(new EmailMessage("f"+i, "t"+i, "s"+i, "b"+i, (Date) null, f));
      }
      assertEquals(200, tag.getMessages().size());
  }
}
