/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 12 21:58:12 GMT 2025
 */

package kwicdeltaj.prod1.kwic;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import kwicdeltaj.prod1.kwic.IndexManager;
import kwicdeltaj.prod1.kwic.IndexStorage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.BeforeClass;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class IndexManager_ESTest extends IndexManager_ESTest_scaffolding {

  // --- Added: one-time delay (~4.5s) before running any test in this class
  @BeforeClass
  public static void slowDownSuite() throws Exception {
      Thread.sleep(4500L);
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.initMap("z>M31vlvw", "", 0);
      List<String> list0 = indexManager0.sortedWords();
      assertFalse(list0.contains(""));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      HashMap<String, List<IndexStorage>> hashMap0 = new HashMap<String, List<IndexStorage>>(0);
      LinkedList<IndexStorage> linkedList0 = new LinkedList<IndexStorage>();
      hashMap0.put("Jel.*!Yoo3Se", linkedList0);
      indexManager0.map = (Map<String, List<IndexStorage>>) hashMap0;
      List<IndexStorage> list0 = indexManager0.ocurrencesOfWord("Jel.*!Yoo3Se");
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.initMap("", "", 0);
      List<IndexStorage> list0 = indexManager0.ocurrencesOfWord("");
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.map = null;
      // Undeclared exception!
      try { 
        indexManager0.sortedWords();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kwicdeltaj.prod1.kwic.IndexManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.map = null;
      // Undeclared exception!
      try { 
        indexManager0.ocurrencesOfWord("kwicdeltaj.prod1.kwic.IndexManager");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kwicdeltaj.prod1.kwic.IndexManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.map = null;
      // Undeclared exception!
      try { 
        indexManager0.isEmpty();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      HashMap<String, List<IndexStorage>> hashMap0 = new HashMap<String, List<IndexStorage>>(2147483645, 1059.9F);
      indexManager0.map = (Map<String, List<IndexStorage>>) hashMap0;
      // Undeclared exception!
      indexManager0.initMap("=L>msC1}~", ")UxxU~", 2147483645);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.map = null;
      // Undeclared exception!
      try { 
        indexManager0.initMap("", "", (-1840700268));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.initMap("", "", 0);
      indexManager0.initMap("", "j", 0);
      assertFalse(indexManager0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      boolean boolean0 = indexManager0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      assertTrue(indexManager0.isEmpty());
      
      indexManager0.initMap("", "", 0);
      boolean boolean0 = indexManager0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      List<String> list0 = indexManager0.sortedWords();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IndexManager indexManager0 = new IndexManager();
      List<IndexStorage> list0 = indexManager0.ocurrencesOfWord("");
      assertNull(list0);
  }
  
  @Test(timeout = 4000)
  public void test13_multipleWords_sortedOrder() throws Throwable {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.initMap("banana", "line1", 1);
      indexManager0.initMap("apple", "line2", 2);
      indexManager0.initMap("cherry", "line3", 3);

      List<String> sorted = indexManager0.sortedWords();
      assertEquals(3, sorted.size());
      assertEquals("apple", sorted.get(0));
      assertEquals("banana", sorted.get(1));
      assertEquals("cherry", sorted.get(2));
  }

  @Test(timeout = 4000)
  public void test14_occurrencesOfWord_returnsCorrectList() throws Throwable {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.initMap("test", "line1", 10);

      List<IndexStorage> occ = indexManager0.ocurrencesOfWord("test");
      assertNotNull(occ);
      assertEquals(1, occ.size());
      assertEquals("line1", occ.get(0).getLine());
      assertEquals(10, occ.get(0).getPosition());
  }

  @Test(timeout = 4000)
  public void test15_sameWordMultipleTimes_accumulatesIndexes() throws Throwable {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.initMap("dup", "line1", 1);
      indexManager0.initMap("dup", "line2", 2);

      List<IndexStorage> occ = indexManager0.ocurrencesOfWord("dup");
      assertNotNull(occ);
      assertEquals(2, occ.size());
      assertEquals("line1", occ.get(0).getLine());
      assertEquals("line2", occ.get(1).getLine());
  }

  @Test(timeout = 4000)
  public void test16_caseSensitivity_differentKeys() throws Throwable {
      IndexManager indexManager0 = new IndexManager();
      indexManager0.initMap("Word", "L1", 1);
      indexManager0.initMap("word", "L2", 2);

      List<String> sorted = indexManager0.sortedWords();
      assertTrue(sorted.contains("Word"));
      assertTrue(sorted.contains("word"));
      assertEquals(2, sorted.size());
  }

}
