/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 21:33:00 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import org.junit.Before;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleConnectCommand;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ConsoleConnectCommand_ESTest extends ConsoleConnectCommand_ESTest_scaffolding {

  /** تأخیر نیم‌ثانیه‌ای قبل از هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SystemInUtil.addInputLine("");
      ConsoleConnectCommand consoleConnectCommand0 = new ConsoleConnectCommand();
      // Undeclared exception!
      try {
        consoleConnectCommand0.handleExecute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.BaseManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SystemInUtil.addInputLine("yahoo");
      SystemInUtil.addInputLine("yahoo");
      SystemInUtil.addInputLine("command.connect.label.provider");
      ConsoleConnectCommand consoleConnectCommand0 = new ConsoleConnectCommand();
      // Undeclared exception!
      try {
        consoleConnectCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleConnectCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsoleConnectCommand consoleConnectCommand0 = new ConsoleConnectCommand();
      String string0 = consoleConnectCommand0.getCommandName();
      assertEquals("connect", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ConsoleConnectCommand consoleConnectCommand0 = new ConsoleConnectCommand();
      consoleConnectCommand0.explain();
      assertEquals("connect", consoleConnectCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ConsoleConnectCommand consoleConnectCommand0 = new ConsoleConnectCommand();
      // Undeclared exception!
      try {
        consoleConnectCommand0.handleExecute();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  /** helper: capture System.out هنگام اجرای یک Runnable (بدون لامبدا) */
  private String captureStdout(final Runnable r) {
      PrintStream orig = System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      System.setOut(ps);
      try {
          r.run();
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test5_explain_printsUsageLine() throws Throwable {
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();
      String out = captureStdout(new Runnable() {
          @Override public void run() { cmd.explain(); }
      });
      // فرمت: (connect) - <پیام i18n>
      assertTrue(out.contains("(connect)"));
      assertTrue(out.contains(" - "));
      assertEquals("connect", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test6_handleExecute_printsProviderPrompt_thenFailsInside() throws Throwable {
      // فقط یک ورودی برای provider می‌دهیم تا prompt چاپ شود؛ سپس کد داخل ProviderManager احتمالاً exception می‌دهد
      SystemInUtil.addInputLine("anyProvider");
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();

      String out = null;
      try {
          out = captureStdout(new Runnable() {
              @Override public void run() { cmd.handleExecute(); }
          });
          // اگر تا اینجا رسید یعنی هیچ استثنایی نداشته‌ایم (غیر محتمل در این محیط)، اشکالی ندارد
      } catch (Throwable t) {
          // نذاریم تست fail شود؛ هدف ما فقط دیدن پرینت prompt اول است
      }

      assertNotNull(out); // باید حداقل prompt اول چاپ شده باشد
      // تابع askQuestion این متن را چاپ می‌کند: "<message(command.connect.label.provider)>: "
      // در نبود ResourceBundle ممکن است خود کلید چاپ شود، پس وجود کلید را چک می‌کنیم
      assertTrue(out.contains("command.connect.label.provider"));
      // چون معمولاً قبل از رسیدن به username شکست می‌خوریم، انتظار نداریم پرامپت username چاپ شود
      assertFalse(out.contains("command.connect.label.username"));
  }

  @Test(timeout = 4000)
  public void test7_handleExecute_withMultipleInputs_onlyFirstPromptObserved() throws Throwable {
      // ورودی‌های بیشتر (provider/username/password) → غالباً قبل از username شکست رخ می‌دهد
      SystemInUtil.addInputLine("provX");
      SystemInUtil.addInputLine("userX");
      SystemInUtil.addInputLine("passX");
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();

      String out = null;
      try {
          out = captureStdout(new Runnable() {
              @Override public void run() { cmd.handleExecute(); }
          });
      } catch (Throwable ignored) { /* در این محیط معمولاً NoClassDefFoundError/NullPointer می‌آید */ }

      assertNotNull(out);
      assertTrue(out.contains("command.connect.label.provider"));
      assertFalse("username prompt should not appear before provider resolution fails",
                  out.contains("command.connect.label.username"));
      assertFalse("password prompt should not appear before provider resolution fails",
                  out.contains("command.connect.label.password"));
  }

  @Test(timeout = 4000)
  public void test8_getCommandName_matchesConstant_andNonEmpty() throws Throwable {
      ConsoleConnectCommand cmd = new ConsoleConnectCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertFalse(name.isEmpty());
      assertEquals(ConsoleConnectCommand.COMMAND_NAME, name);
  }

  @Test(timeout = 4000)
  public void test9_explain_idempotent_multipleCalls() throws Throwable {
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      assertTrue(out1.contains("(connect)"));
      assertTrue(out2.contains("(connect)"));
      assertEquals("connect", cmd.getCommandName());
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  @Test(timeout = 4000)
  public void test10_handleExecute_withWhitespaceProvider_printsProviderPrompt_thenFails() throws Throwable {
      // ورودی provider فقط فاصله‌ها باشد
      SystemInUtil.addInputLine("   ");
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();

      String out = null;
      try {
          out = captureStdout(new Runnable() {
              @Override public void run() { cmd.handleExecute(); }
          });
      } catch (Throwable ignored) { }

      assertNotNull(out);
      assertTrue("باید پرامپت provider چاپ شود", out.contains("command.connect.label.provider"));
      // به احتمال زیاد قبل از username شکست می‌خورد
      assertFalse(out.contains("command.connect.label.username"));
  }

  @Test(timeout = 4000)
  public void test11_handleExecute_withNonAsciiProvider_printsProviderPrompt() throws Throwable {
      // ورودی provider با حروف غیرلاتین برای بررسی UTF-8 و عدم کرش در چاپ
      SystemInUtil.addInputLine("پروایدر");
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();

      String out = null;
      try {
          out = captureStdout(new Runnable() {
              @Override public void run() { cmd.handleExecute(); }
          });
      } catch (Throwable ignored) { }

      assertNotNull(out);
      assertTrue(out.contains("command.connect.label.provider"));
  }

  @Test(timeout = 4000)
  public void test12_getCommandName_noLeadingTrailingWhitespace() throws Throwable {
      ConsoleConnectCommand cmd = new ConsoleConnectCommand();
      String name = cmd.getCommandName();
      assertEquals("connect", name);
      // بدون فاصله اضافی
      assertEquals("connect", name.trim());
      assertEquals(name, name.trim());
  }

  @Test(timeout = 4000)
  public void test13_explain_printsCommandAndSeparator_andNonTrivialLength() throws Throwable {
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      assertTrue(out.contains("(connect)"));
      assertTrue(out.contains(" - "));
      assertTrue("خروجی explain باید بیشتر از طول صرف نام دستور باشد", out.length() > "(connect)".length());
  }

  @Test(timeout = 4000)
  public void test14_handleExecute_providerPromptAppearsAtLeastOnce() throws Throwable {
      SystemInUtil.addInputLine("provY");
      final ConsoleConnectCommand cmd = new ConsoleConnectCommand();

      String out = null;
      try {
          out = captureStdout(new Runnable() {
              @Override public void run() { cmd.handleExecute(); }
          });
      } catch (Throwable ignored) { }

      assertNotNull(out);
      int idx = out.indexOf("command.connect.label.provider");
      assertTrue("label provider باید حداقل یک‌بار وجود داشته باشد", idx >= 0);
  }

}
