/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 30 22:59:45 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.i18n;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.junit.Before;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.i18n.MessageBundle;
import java.io.StringReader;
import java.util.MissingResourceException;
import java.util.PropertyResourceBundle;
import java.util.ResourceBundle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MessageBundle_ESTest extends MessageBundle_ESTest_scaffolding {

  // 0.5s delay before each test
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageBundle.message("XbGKM", "");
        fail("Expecting exception: MissingResourceException");
      
      } catch(MissingResourceException e) {
         //
         // Can't find resource for bundle java.util.PropertyResourceBundle, key XbGKM
         //
         verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MessageBundle messageBundle0 = MessageBundle.instance();
      StringReader stringReader0 = new StringReader("a");
      PropertyResourceBundle propertyResourceBundle0 = new PropertyResourceBundle(stringReader0);
      messageBundle0.rb = (ResourceBundle) propertyResourceBundle0;
      Object[] objectArray0 = new Object[6];
      String string0 = messageBundle0.getMessage("a", objectArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        MessageBundle.message("MessageBundle", objectArray0);
        fail("Expecting exception: MissingResourceException");
      
      } catch(MissingResourceException e) {
         //
         // Can't find resource for bundle java.util.PropertyResourceBundle, key MessageBundle
         //
         verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageBundle.message((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PropertyResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageBundle.message((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PropertyResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MessageBundle messageBundle0 = new MessageBundle();
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        messageBundle0.getMessage((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PropertyResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MessageBundle messageBundle0 = MessageBundle.instance();
      // Undeclared exception!
      try { 
        messageBundle0.getMessage("VV", "VV");
        fail("Expecting exception: MissingResourceException");
      
      } catch(MissingResourceException e) {
         //
         // Can't find resource for bundle java.util.PropertyResourceBundle, key VV
         //
         verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MessageBundle messageBundle0 = MessageBundle.instance();
      // Undeclared exception!
      try { 
        messageBundle0.getMessage((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PropertyResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MessageBundle messageBundle0 = new MessageBundle();
      // Undeclared exception!
      try { 
        messageBundle0.getMessage((String) null, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PropertyResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MessageBundle messageBundle0 = MessageBundle.instance();
      // Undeclared exception!
      try { 
        messageBundle0.getMessage("");
        fail("Expecting exception: MissingResourceException");
      
      } catch(MissingResourceException e) {
         //
         // Can't find resource for bundle java.util.PropertyResourceBundle, key 
         //
         verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MessageBundle messageBundle0 = MessageBundle.instance();
      MessageBundle messageBundle1 = MessageBundle.instance();
      assertSame(messageBundle1, messageBundle0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageBundle.message("pUTkPFn@^\";}");
        fail("Expecting exception: MissingResourceException");
      
      } catch(MissingResourceException e) {
         //
         // Can't find resource for bundle java.util.PropertyResourceBundle, key pUTkPFn@^\";}
         //
         verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageBundle.message((String) null, (Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PropertyResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MessageBundle messageBundle0 = MessageBundle.instance();
      Object[] objectArray0 = new Object[6];
      // Undeclared exception!
      try { 
        messageBundle0.getMessage("a", objectArray0);
        fail("Expecting exception: MissingResourceException");
      
      } catch(MissingResourceException e) {
         //
         // Can't find resource for bundle java.util.PropertyResourceBundle, key a
         //
         verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test14_customBundle_singleParamFormatting() throws Throwable {
      // arrange
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new java.io.StringReader("hello=Hello %s"));
      mb.rb = (ResourceBundle) prb;

      // act
      String out = mb.getMessage("hello", "World");

      // assert
      assertEquals("Hello World", out);
  }

  @Test(timeout = 4000)
  public void test15_customBundle_arrayFormatting() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new java.io.StringReader("fmt=%s-%s"));
      mb.rb = (ResourceBundle) prb;

      String out = mb.getMessage("fmt", new Object[]{"A","B"});
      assertEquals("A-B", out);
  }

  @Test(timeout = 4000)
  public void test16_staticMessage_usesSingletonBundle() throws Throwable {
      // backup
      MessageBundle inst = MessageBundle.instance();
      ResourceBundle old = inst.rb;
      try {
          PropertyResourceBundle prb =
              new PropertyResourceBundle(new java.io.StringReader("error=E!"));
          inst.rb = (ResourceBundle) prb;

          String out = MessageBundle.message("error");
          assertEquals("E!", out);
      } finally {
          // restore
          inst.rb = old;
      }
  }

  @Test(timeout = 4000)
  public void test17_instance_isSameAcrossManyCalls() throws Throwable {
      MessageBundle first = MessageBundle.instance();
      for (int i = 0; i < 50; i++) {
          assertSame(first, MessageBundle.instance());
      }
  }

  @Test(timeout = 4000)
  public void test18_instance_isSameAcrossThreads() throws Throwable {
      // Ensure instance created once before threading to avoid noisy failures
      final MessageBundle ref = MessageBundle.instance();

      final Object[] seen = new Object[5];
      Thread[] ts = new Thread[5];
      for (int i = 0; i < ts.length; i++) {
          final int idx = i;
          ts[i] = new Thread(new Runnable() {
              @Override public void run() {
                  seen[idx] = MessageBundle.instance();
              }
          });
          ts[i].start();
      }
      for (Thread t : ts) t.join();

      for (int i = 0; i < seen.length; i++) {
          assertSame(ref, seen[i]);
      }
  }

  // ===== Added tests =====

  @Test(timeout = 4000)
  public void test19_customInstance_missingKey_returnsEmptyString() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new StringReader("hello=world"));
      mb.rb = (ResourceBundle) prb;

      String out = mb.getMessage("missing", new Object[]{"x"});
      assertEquals("", out);
  }

  @Test(timeout = 4000)
  public void test20_customInstance_plainNoPlaceholders() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new StringReader("plain=Just text"));
      mb.rb = (ResourceBundle) prb;

      assertEquals("Just text", mb.getMessage("plain"));
  }

  @Test(timeout = 4000)
  public void test21_customInstance_percentLiteral() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new StringReader("pct=100%% done"));
      mb.rb = (ResourceBundle) prb;

      assertEquals("100% done", mb.getMessage("pct"));
  }

  public void test22_customInstance_numericFormatting() throws Throwable {
	    MessageBundle mb = new MessageBundle();
	    PropertyResourceBundle prb =
	        new PropertyResourceBundle(new StringReader("num=%d"));
	    mb.rb = (ResourceBundle) prb;

	    assertEquals("7", mb.getMessage("num", new Object[]{7}));
	}
  @Test(timeout = 4000)
  public void test23_staticMessage_withArgs_formats() throws Throwable {
      MessageBundle inst = MessageBundle.instance();
      ResourceBundle old = inst.rb;
      try {
          PropertyResourceBundle prb =
              new PropertyResourceBundle(new StringReader("greet=Hi %s %s"));
          inst.rb = (ResourceBundle) prb;

          String out = MessageBundle.message("greet", new Object[]{"A", "B"});
          assertEquals("Hi A B", out);
      } finally {
          inst.rb = old;
      }
  }

  @Test(timeout = 4000)
  public void test24_staticMessage_missingKey_throws() throws Throwable {
      MessageBundle inst = MessageBundle.instance();
      ResourceBundle old = inst.rb;
      try {
          PropertyResourceBundle prb =
              new PropertyResourceBundle(new StringReader("only=exists"));
          inst.rb = (ResourceBundle) prb;

          try {
              MessageBundle.message("nope");
              fail("Expecting exception: MissingResourceException");
          } catch (MissingResourceException e) {
              verifyException("java.util.ResourceBundle", e);
          }
      } finally {
          inst.rb = old;
      }
  }

  @Test(timeout = 4000)
  public void test25_unicodeKeyAndValue_formats() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new StringReader("سلام=درود %s"));
      mb.rb = (ResourceBundle) prb;

      assertEquals("درود دنیا", mb.getMessage("سلام", "دنیا"));
  }

  @Test(timeout = 4000)
  public void test26_illegalFormatConversion_throws() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new StringReader("x=%d"));
      mb.rb = (ResourceBundle) prb;

      try {
          mb.getMessage("x", "not-a-number");
          fail("Expecting exception: IllegalFormatConversionException");
      } catch (java.util.IllegalFormatConversionException e) {
          verifyException("java.util.IllegalFormatConversionException", e);
      }
  }

  @Test(timeout = 4000)
  public void test27_extraArguments_areIgnored() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new StringReader("only=%s"));
      mb.rb = (ResourceBundle) prb;

      assertEquals("A", mb.getMessage("only", new Object[]{"A", "B", "C"}));
  }
  @Test(timeout = 4000)
  public void test28_mixedPercentLiteralAndArg() throws Throwable {
      MessageBundle mb = new MessageBundle();
      PropertyResourceBundle prb =
          new PropertyResourceBundle(new StringReader("mix=%%-%s"));
      mb.rb = (ResourceBundle) prb;

      assertEquals("%-ok", mb.getMessage("mix", "ok"));
  }
}
