/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 12 22:10:23 GMT 2025
 */

package kwicdeltaj.prod1.kwic;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import java.util.NoSuchElementException;
import kwicdeltaj.prod1.kwic.DBLPStorageManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;
import org.junit.BeforeClass;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class DBLPStorageManager_ESTest extends DBLPStorageManager_ESTest_scaffolding {

  // --- Added: one-time delay (~4.5s) before running any test in this class
  @BeforeClass
  public static void slowDownSuite() throws Exception {
      Thread.sleep(4500L);
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SystemInUtil.addInputLine("An error has occurred, check the connection. ");
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      dBLPStorageManager0.init();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst("http://dblp.org/search/publ/api?q=");
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      dBLPStorageManager0.lines = (List<String>) linkedList0;
      String string0 = dBLPStorageManager0.line(0);
      assertEquals("http://dblp.org/search/publ/api?q=", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst("");
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      dBLPStorageManager0.lines = (List<String>) linkedList0;
      String string0 = dBLPStorageManager0.line(0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      dBLPStorageManager0.lines = (List<String>) linkedList0;
      int int0 = dBLPStorageManager0.length();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("5tVWy");
      dBLPStorageManager0.lines = (List<String>) linkedList0;
      int int0 = dBLPStorageManager0.length();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      dBLPStorageManager0.lines = (List<String>) linkedList0;
      // Undeclared exception!
      try { 
        dBLPStorageManager0.line((-1532));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1532, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst("");
      List<String> list0 = linkedList0.subList(1, 1);
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      linkedList0.add("");
      // Undeclared exception!
      try { 
        dBLPStorageManager0.jsonParse(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      // Undeclared exception!
      try { 
        dBLPStorageManager0.jsonParse((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kwicdeltaj.prod2.kwic.DBLPStorageManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      // Undeclared exception!
      try { 
        dBLPStorageManager0.init();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerFirst("title");
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      // Undeclared exception!
      try { 
        dBLPStorageManager0.jsonParse(linkedList0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("5tVWy");
      List<String> list0 = dBLPStorageManager0.jsonParse(linkedList0);
      assertNotNull(list0);
      assertFalse(list0.contains("5tVWy"));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SystemInUtil.addInputLine("http://dblp.org/search/publ/api?q=");
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://dblp.org/search/publ/api?q=http://dblp.org/search/publ/api?q=&format=json");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "http://dblp.org/search/publ/api?q=");
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      dBLPStorageManager0.init();
      assertEquals(0, dBLPStorageManager0.length());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SystemInUtil.addInputLine("http://dblp.org/search/publ/api?q=");
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://dblp.org/search/publ/api?q=http://dblp.org/search/publ/api?q=&format=json");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "title");
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      // Undeclared exception!
      try { 
        dBLPStorageManager0.init();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      // Undeclared exception!
      try { 
        dBLPStorageManager0.line(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kwicdeltaj.prod2.kwic.DBLPStorageManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DBLPStorageManager dBLPStorageManager0 = new DBLPStorageManager();
      // Undeclared exception!
      try { 
        dBLPStorageManager0.length();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("kwicdeltaj.prod2.kwic.DBLPStorageManager", e);
      }
  }
  
  @Test(timeout = 4000)
  public void test15_jsonParse_singleTitle() throws Throwable {
      DBLPStorageManager mgr = new DBLPStorageManager();
      LinkedList<String> lines = new LinkedList<String>();
      lines.add("{ \"title\": \"Alpha\" }");

      List<String> titles = mgr.jsonParse(lines);
      assertEquals(1, titles.size());
      assertEquals("Alpha", titles.get(0));
  }

  @Test(timeout = 4000)
  public void test16_jsonParse_multipleTitles_acrossLines() throws Throwable {
      DBLPStorageManager mgr = new DBLPStorageManager();
      LinkedList<String> lines = new LinkedList<String>();
      lines.add("{ \"title\": \"First\" },");
      lines.add("{ \"notitle\": \"skip\" }");
      lines.add("{ \"title\": \"Second\" }");

      List<String> titles = mgr.jsonParse(lines);
      assertEquals(2, titles.size());
      assertEquals("First", titles.get(0));
      assertEquals("Second", titles.get(1));
  }

  @Test(timeout = 4000)
  public void test17_jsonParse_emptyTitle() throws Throwable {
      DBLPStorageManager mgr = new DBLPStorageManager();
      LinkedList<String> lines = new LinkedList<String>();
      lines.add("{ \"title\": \"\" }");

      List<String> titles = mgr.jsonParse(lines);
      assertEquals(1, titles.size());
      assertEquals("", titles.get(0));
  }

  @Test(timeout = 4000)
  public void test18_init_success_parsesTitles_fromNetworkMock() throws Throwable {
      // کلید ورودی کاربر
      String key = "unit-test";
      SystemInUtil.addInputLine(key);

      // ساخت URL دقیقا مطابق کدی که در init استفاده می‌شود
      EvoSuiteURL url = new EvoSuiteURL("http://dblp.org/search/publ/api?q=" + key + "&format=json");

      // محتوای شبیه‌سازی‌شدهٔ پاسخ (چند خطه تا حلقهٔ readLine را هم تست کند)
      String remoteContent = "{ \"result\": {" +
              "\"hits\": [" +
              "{ \"info\": { \"title\": \"Paper A\" } }," +
              "{ \"info\": { \"title\": \"Paper B\" } }" +
              "]}}";
      // می‌تونیم در دو خط قرارش بدیم تا همچنان هر خط شامل title باشد
      NetworkHandling.createRemoteTextFile(url, "{ \"info\": { \"title\": \"Paper A\" } }\n{ \"info\": { \"title\": \"Paper B\" } }");

      DBLPStorageManager mgr = new DBLPStorageManager();
      mgr.init();

      // jsonParse باید دو عنوان استخراج کرده باشد
      assertEquals(2, mgr.length());
      assertEquals("Paper A", mgr.line(0));
      assertEquals("Paper B", mgr.line(1));
  }

  @Test(timeout = 4000)
  public void test19_jsonParse_nonAsciiTitle_persian() throws Throwable {
      DBLPStorageManager mgr = new DBLPStorageManager();
      LinkedList<String> lines = new LinkedList<String>();
      lines.add("{ \"title\": \"سلام دنیا\" }");

      List<String> titles = mgr.jsonParse(lines);
      assertEquals(1, titles.size());
      assertEquals("سلام دنیا", titles.get(0));
  }

  @Test(timeout = 4000)
  public void test20_lengthAndLine_afterManualAssignParsed() throws Throwable {
      DBLPStorageManager mgr = new DBLPStorageManager();
      LinkedList<String> src = new LinkedList<String>();
      src.add("{ \"title\": \"X\" }");
      src.add("{ \"title\": \"Y\" }");
      List<String> parsed = mgr.jsonParse(src);

      // شبیه‌سازی حالت پس از init
      mgr.lines = parsed;

      assertEquals(2, mgr.length());
      assertEquals("X", mgr.line(0));
      assertEquals("Y", mgr.line(1));
  }

  @Test(timeout = 4000)
  public void test21_jsonParse_emptyList_returnsEmpty() throws Throwable {
      DBLPStorageManager mgr = new DBLPStorageManager();
      List<String> empty = new LinkedList<String>();

      List<String> titles = mgr.jsonParse(empty);
      assertNotNull(titles);
      assertTrue(titles.isEmpty());
  }

  @Test(timeout = 4000)
  public void test22_init_malformedUrl_keyWithSpace_noCrash() throws Throwable {
      // کلیدی که باعث MalformedURLException می‌شود (space در URL)
      SystemInUtil.addInputLine("bad key with space");

      DBLPStorageManager mgr = new DBLPStorageManager();
      // نباید استثناء unchecked پرتاب کند؛ خطا داخل catch هندل می‌شود
      mgr.init();

      // lines ممکن است null بماند، پس فقط نبود کرش مهم است
      // (اگر length() صدا بزنیم، NPE می‌گیریم که مدنظر این تست نیست)
      assertTrue(true);
  }

}
