/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 18:10:24 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.Before;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.EmailProvider;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider.GmailProvider;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider.OutlookProvider; // اضافه شد
import java.util.Properties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class GmailProvider_ESTest extends GmailProvider_ESTest_scaffolding {

  // تاخیر ۰.۵ ثانیه قبل از هر تست
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("connect to outlook accounts", "1^CG@;w@?E>&");
      assertEquals("connect to outlook accounts", gmailProvider0.getUsername());
      assertEquals("1^CG@;w@?E>&", gmailProvider0.getPassword());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      String string0 = gmailProvider0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("z'^2C#TX9xe|\"", "z'^2C#TX9xe|\"");
      gmailProvider0.setUsername("");
      String string0 = gmailProvider0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      String string0 = gmailProvider0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("", "");
      String string0 = gmailProvider0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("z'^2C#TX9xe|\"", "z'^2C#TX9xe|\"");
      String string0 = gmailProvider0.getTransportHost();
      assertEquals("smtp.gmail.com", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      boolean boolean0 = gmailProvider0.isAuthenticationEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("z'^2C#TX9xe|\"", "z'^2C#TX9xe|\"");
      String string0 = gmailProvider0.getStoreHost();
      assertEquals("imap.gmail.com", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      String string0 = gmailProvider0.getName();
      assertEquals("gmail", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("z'^2C#TX9xe|\"", "z'^2C#TX9xe|\"");
      Properties properties0 = gmailProvider0.getProperties();
      assertEquals(9, properties0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      int int0 = gmailProvider0.getStorePort();
      assertEquals(993, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      String string0 = gmailProvider0.getStoreProtocol();
      assertEquals("imap", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("z'^2C#TX9xe|\"", "z'^2C#TX9xe|\"");
      String string0 = gmailProvider0.getUsername();
      assertEquals("z'^2C#TX9xe|\"", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("z'^2C#TX9xe|\"", "z'^2C#TX9xe|\"");
      int int0 = gmailProvider0.getTransportPort();
      assertEquals(587, int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("z'^2C#TX9xe|\"", "z'^2C#TX9xe|\"");
      gmailProvider0.setPassword("");
      assertEquals("smtp", gmailProvider0.getTransportProtocol());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      EmailProvider emailProvider0 = gmailProvider0.clone();
      assertEquals("gmail", emailProvider0.getName());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      String string0 = gmailProvider0.getTransportProtocol();
      assertEquals("smtp", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider("provider.description", "provider.description");
      String string0 = gmailProvider0.getPassword();
      assertEquals("provider.description", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      GmailProvider gmailProvider0 = new GmailProvider();
      String string0 = gmailProvider0.getDescription();
      assertEquals("connect to gmail accounts", string0);
  }

  // ---------- OutlookProvider tests (از قبل موجود) ----------
  @Test(timeout = 4000)
  public void defaultsAndConstants() {
    OutlookProvider p = new OutlookProvider();
    assertEquals("outlook", p.getName());
    assertEquals("connect to outlook accounts", p.getDescription());

    // پروتکل‌ها و هاست‌ها
    assertEquals("smtp", p.getTransportProtocol());
    assertEquals("imaps", p.getStoreProtocol());
    assertEquals("smtp-mail.outlook.com", p.getTransportHost());
    assertEquals("imap-mail.outlook.com", p.getStoreHost());

    // پورت‌ها در این کلاس مشخص نشده‌اند
    assertEquals(-1, p.getTransportPort());
    assertEquals(-1, p.getStorePort());

    // احراز هویت و کرِدنشیال‌های پیش‌فرض
    assertTrue(p.isAuthenticationEnabled());
    assertNull(p.getUsername());
    assertNull(p.getPassword());
  }

  @Test(timeout = 4000)
  public void setAndGetCredentials() {
    OutlookProvider p = new OutlookProvider();
    p.setUsername("user@outlook.com");
    p.setPassword("secret");
    assertEquals("user@outlook.com", p.getUsername());
    assertEquals("secret", p.getPassword());

    OutlookProvider p2 = new OutlookProvider("u2", "p2");
    assertEquals("u2", p2.getUsername());
    assertEquals("p2", p2.getPassword());
  }

  @Test(timeout = 4000)
  public void propertiesArePrepopulated() {
    OutlookProvider p = new OutlookProvider();
    Properties props = p.getProperties();
    assertNotNull(props);

    // کلیدهای تعریف‌شده در بلوک static
    assertEquals("smtp-mail.outlook.com", props.getProperty("mail.smtp.host"));
    assertEquals("true", props.getProperty("mail.smtp.auth"));
    assertEquals("true", props.getProperty("mail.smtp.starttls.enable"));
    assertEquals("imap-mail.outlook.com", props.getProperty("mail.imaps.host"));

    // دقیقا ۴ کلید داریم
    assertEquals(4, props.size());
  }

  @Test(timeout = 4000)
  public void propertiesAreSharedAcrossInstances() {
    OutlookProvider p1 = new OutlookProvider();
    OutlookProvider p2 = new OutlookProvider();

    // چون properties در کلاس static است، هر دو باید یکی باشند
    assertSame(p1.getProperties(), p2.getProperties());

    // تغییر روی یکی، روی دیگری هم دیده می‌شود
    p1.getProperties().setProperty("x", "1");
    assertEquals("1", p2.getProperties().getProperty("x"));

    // تمیزکاری اختیاری
    p2.getProperties().remove("x");
  }

  @Test(timeout = 4000, expected = CloneNotSupportedException.class)
  public void cloneThrowsByDesign() throws Exception {
    // این کلاس Cloneable را پیاده‌سازی نکرده و super.clone() پرتاب استثنا می‌کند
    OutlookProvider p = new OutlookProvider();
    p.clone();
  }

  // ---------- تست‌های افزوده‌شده ----------

  @Test(timeout = 4000)
  public void test19_gmail_propertiesContainExpectedKeysAndValues() {
      GmailProvider g = new GmailProvider();
      Properties props = g.getProperties();
      assertEquals("smtp.gmail.com", props.getProperty("mail.smtp.host"));
      assertEquals("true", props.getProperty("mail.smtp.auth"));
      assertEquals("true", props.getProperty("mail.smtp.starttls.enable"));
      assertEquals("imap.gmail.com", props.getProperty("mail.imap.host"));
  }

  @Test(timeout = 4000)
  public void test20_gmail_clone_copiesCredentialsAndType() throws Exception { // <-- اضافه شد
      GmailProvider g1 = new GmailProvider("u", "p");
      EmailProvider cloned = g1.clone();
      assertNotSame(g1, cloned);
      assertTrue(cloned instanceof GmailProvider);
      assertEquals("gmail", cloned.getName());
      assertEquals("u", ((GmailProvider) cloned).getUsername());
      assertEquals("p", ((GmailProvider) cloned).getPassword());
  }


  @Test(timeout = 4000)
  public void test21_gmail_changeUsernameAndPasswordMultipleTimes() {
      GmailProvider g = new GmailProvider();
      assertNull(g.getUsername());
      assertNull(g.getPassword());
      g.setUsername("a"); g.setPassword("1");
      assertEquals("a", g.getUsername());
      assertEquals("1", g.getPassword());
      g.setUsername(null); g.setPassword(null);
      assertNull(g.getUsername());
      assertNull(g.getPassword());
  }

  @Test(timeout = 4000)
  public void test22_gmail_properties_mutationIsVisibleFromSameInstance() {
      GmailProvider g = new GmailProvider();
      Properties props = g.getProperties();
      props.setProperty("custom.key", "v");
      assertEquals("v", g.getProperties().getProperty("custom.key"));
      // تمیزکاری
      g.getProperties().remove("custom.key");
  }

  @Test(timeout = 4000)
  public void test23_gmail_portsAndProtocols_consistency() {
      GmailProvider g = new GmailProvider();
      assertEquals("smtp", g.getTransportProtocol());
      assertEquals(587, g.getTransportPort());
      assertEquals("imap", g.getStoreProtocol());
      assertEquals(993, g.getStorePort());
  }

  @Test(timeout = 4000)
  public void test24_gmail_getNameAndDescription_areStable() {
      GmailProvider g = new GmailProvider();
      assertEquals("gmail", g.getName());
      assertEquals("connect to gmail accounts", g.getDescription());
      // بعد از تغییر یوزر/پسورد هم ثابت می‌مانند
      g.setUsername("x"); g.setPassword("y");
      assertEquals("gmail", g.getName());
      assertEquals("connect to gmail accounts", g.getDescription());
  }

  @Test(timeout = 4000)
  public void test25_gmail_properties_haveAtLeastMinimalSet() {
      GmailProvider g = new GmailProvider();
      Properties props = g.getProperties();
      // حداقل کلیدهای ضروری
      assertNotNull(props.getProperty("mail.smtp.host"));
      assertNotNull(props.getProperty("mail.smtp.auth"));
      assertNotNull(props.getProperty("mail.smtp.starttls.enable"));
      assertNotNull(props.getProperty("mail.imap.host"));
  }

  @Test(timeout = 4000)
  public void test26_outlook_setNullCredentials_isAccepted() {
      OutlookProvider p = new OutlookProvider();
      p.setUsername(null);
      p.setPassword(null);
      assertNull(p.getUsername());
      assertNull(p.getPassword());
  }

  @Test(timeout = 4000)
  public void test27_outlook_properties_tlsFlagsTrue() {
      OutlookProvider p = new OutlookProvider();
      Properties props = p.getProperties();
      assertEquals("true", props.getProperty("mail.smtp.auth"));
      assertEquals("true", props.getProperty("mail.smtp.starttls.enable"));
  }

  @Test(timeout = 4000)
  public void test28_gmail_clone_mutatingCloneCredentialsDoesNotAffectOriginal() throws Exception { // <-- اضافه شد
      GmailProvider original = new GmailProvider("user1", "pass1");
      GmailProvider clone = (GmailProvider) original.clone();
      clone.setUsername("user2");
      clone.setPassword("pass2");
      assertEquals("user1", original.getUsername());
      assertEquals("pass1", original.getPassword());
      assertEquals("user2", clone.getUsername());
      assertEquals("pass2", clone.getPassword());
  }

  @Test(timeout = 4000)
  public void test29_gmail_properties_independentBetweenInstances() {
      GmailProvider g1 = new GmailProvider();
      GmailProvider g2 = new GmailProvider();
      g1.getProperties().setProperty("k-only-g1", "1");
      assertEquals("1", g1.getProperties().getProperty("k-only-g1"));
      assertNull(g2.getProperties().getProperty("k-only-g1"));
      // تمیزکاری
      g1.getProperties().remove("k-only-g1");
  }

  @Test(timeout = 4000)
  public void test30_outlook_properties_afterMutationRemainAccessible() {
      OutlookProvider p = new OutlookProvider();
      p.getProperties().setProperty("temp.k", "v");
      assertEquals("v", p.getProperties().getProperty("temp.k"));
      // تمیزکاری
      p.getProperties().remove("temp.k");
  }
}
