/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 19:28:08 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.EmailProvider;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider.YahooProvider;
import java.util.Properties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class YahooProvider_ESTest extends YahooProvider_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای قبل از هر تست */
  @Before
  public void halfSecondDelay() throws Exception {
      try { Thread.sleep(500L); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      yahooProvider0.setUsername("provider.password");
      String string0 = yahooProvider0.getUsername();
      assertEquals("provider.password", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      yahooProvider0.setUsername("");
      String string0 = yahooProvider0.getUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider("^}YtI%", "?8]7%kos(eQ;T");
      String string0 = yahooProvider0.getPassword();
      assertEquals("^}YtI%", yahooProvider0.getUsername());
      assertEquals("?8]7%kos(eQ;T", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      yahooProvider0.setPassword("");
      String string0 = yahooProvider0.getPassword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      boolean boolean0 = yahooProvider0.isAuthenticationEnabled();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      int int0 = yahooProvider0.getStorePort();
      assertEquals(993, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getDescription();
      assertEquals("connect to yahoo accounts", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getStoreProtocol();
      assertEquals("imaps", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getTransportHost();
      assertEquals("smtp.mail.yahoo.com", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      EmailProvider emailProvider0 = yahooProvider0.clone();
      assertEquals("connect to yahoo accounts", emailProvider0.getDescription());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getStoreHost();
      assertEquals("imap.mail.yahoo.com", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getName();
      assertEquals("yahoo", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      Properties properties0 = yahooProvider0.getProperties();
      assertFalse(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      String string0 = yahooProvider0.getTransportProtocol();
      assertEquals("smtps", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      YahooProvider yahooProvider0 = new YahooProvider();
      int int0 = yahooProvider0.getTransportPort();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test17_propertiesAreSharedAcrossInstances()  throws Throwable  {
      YahooProvider p1 = new YahooProvider();
      YahooProvider p2 = new YahooProvider();

      Properties props1 = p1.getProperties();
      Properties props2 = p2.getProperties();

      Object old = props1.put("mail.test.shared", "yes");
      try {
        assertEquals("yes", props2.get("mail.test.shared"));
      } finally {
        if (old == null) props1.remove("mail.test.shared"); else props1.put("mail.test.shared", old);
      }
  }

  @Test(timeout = 4000)
  public void test18_cloneCreatesIndependentInstanceForCredentials()  throws Throwable  {
      YahooProvider original = new YahooProvider();
      original.setUsername("user1");
      original.setPassword("pass1");

      EmailProvider cloned = original.clone();
      assertNotSame(original, cloned);
      assertEquals("user1", cloned.getUsername());
      assertEquals("pass1", cloned.getPassword());

      original.setUsername("user2");
      original.setPassword("pass2");
      assertEquals("user1", cloned.getUsername());
      assertEquals("pass1", cloned.getPassword());
  }

  @Test(timeout = 4000)
  public void test19_transportAndStorePropertiesExist()  throws Throwable  {
      YahooProvider yahoo = new YahooProvider();
      Properties props = yahoo.getProperties();

      assertEquals("smtp.mail.yahoo.com", props.get("mail.smtps.host"));
      assertEquals("true", props.get("mail.smtps.auth"));
      assertEquals("imap.mail.yahoo.com", props.get("mail.imaps.host"));
      assertEquals("993", props.get("mail.imaps.port"));

      assertEquals("smtps", yahoo.getTransportProtocol());
      assertEquals("imaps", yahoo.getStoreProtocol());
      assertEquals("smtp.mail.yahoo.com", yahoo.getTransportHost());
      assertEquals("imap.mail.yahoo.com", yahoo.getStoreHost());
  }

  @Test(timeout = 4000)
  public void test20_cloneSharesStaticPropertiesButNotCredentials()  throws Throwable  {
      YahooProvider p1 = new YahooProvider();
      EmailProvider p2 = p1.clone();

      Properties props1 = p1.getProperties();
      Properties props2 = p2.getProperties();

      Object prev = props1.put("mail.shared.key", "v");
      try {
        assertEquals("v", props2.get("mail.shared.key"));
      } finally {
        if (prev == null) props1.remove("mail.shared.key"); else props1.put("mail.shared.key", prev);
      }

      p1.setUsername("u1");
      p1.setPassword("p1");
      assertNull(p2.getUsername());
      assertNull(p2.getPassword());
  }

  @Test(timeout = 4000)
  public void test21_credentialsDefaultNullThenSetBoth()  throws Throwable  {
      YahooProvider p = new YahooProvider();
      assertNull(p.getUsername());
      assertNull(p.getPassword());

      p.setUsername("alice@yahoo.com");
      p.setPassword("secret");
      assertEquals("alice@yahoo.com", p.getUsername());
      assertEquals("secret", p.getPassword());
  }

  @Test(timeout = 4000)
  public void test22_settersDoNotTrimValues()  throws Throwable  {
      YahooProvider p = new YahooProvider();
      p.setUsername("  user  ");
      p.setPassword("  pass  ");
      assertEquals("  user  ", p.getUsername());
      assertEquals("  pass  ", p.getPassword());
  }

  @Test(timeout = 4000)
  public void test23_propertiesAreMutable()  throws Throwable  {
      YahooProvider p = new YahooProvider();
      Properties props = p.getProperties();

      Object old = props.put("custom.key", "123");
      try {
        assertEquals("123", props.get("custom.key"));
      } finally {
        if (old == null) props.remove("custom.key"); else props.put("custom.key", old);
      }
  }

  @Test(timeout = 4000)
  public void test24_modifyCloneDoesNotAffectOriginalCredentials()  throws Throwable  {
      YahooProvider original = new YahooProvider();
      original.setUsername("orig");
      original.setPassword("origP");

      EmailProvider clone = original.clone();
      clone.setUsername("clone");
      clone.setPassword("cloneP");

      assertEquals("orig", original.getUsername());
      assertEquals("origP", original.getPassword());
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test25_setNullCredentials_keptNull() throws Throwable {
      YahooProvider p = new YahooProvider();
      p.setUsername(null);
      p.setPassword(null);
      assertNull(p.getUsername());
      assertNull(p.getPassword());
  }

//----- replacement for test26 -----
@Test(timeout = 4000)
public void test26_portsAreFixed_defaultsAndPropsDoNotChangeGetter() throws Throwable {
   YahooProvider p = new YahooProvider();

   // پیش‌فرض‌ها
   assertEquals(-1, p.getTransportPort());
   assertEquals(993, p.getStorePort());

   // تغییر پراپرتی‌های مرتبط نباید مقدار getterها را تغییر دهد
   Properties props = p.getProperties();
   Object oldImaps = props.put("mail.imaps.port", "1993");
   Object oldSmtps = props.put("mail.smtps.port", "465");
   try {
       assertEquals(-1, p.getTransportPort());
       assertEquals(993, p.getStorePort());
       // ولی خود properties قابل‌تغییر است
       assertEquals("1993", props.get("mail.imaps.port"));
       assertEquals("465", props.get("mail.smtps.port"));
   } finally {
       if (oldImaps == null) props.remove("mail.imaps.port"); else props.put("mail.imaps.port", oldImaps);
       if (oldSmtps == null) props.remove("mail.smtps.port"); else props.put("mail.smtps.port", oldSmtps);
   }
}
@Test(timeout = 4000)
public void test27_nameAndDescription_areFixed() throws Throwable {
    YahooProvider p = new YahooProvider();
    assertEquals("yahoo", p.getName());
    assertEquals("connect to yahoo accounts", p.getDescription());

    // حتی با دستکاری پراپرتی‌های مرتبط، getters ثابت می‌مانند
    Properties props = p.getProperties();
    Object oldDesc = props.put("provider.description", "custom desc");
    try {
        assertEquals("yahoo", p.getName());
        assertEquals("connect to yahoo accounts", p.getDescription());
    } finally {
        if (oldDesc == null) props.remove("provider.description"); else props.put("provider.description", oldDesc);
    }
}
  @Test(timeout = 4000)
  public void test28_cloneKeepsHostsAndProtocols() throws Throwable {
      YahooProvider p = new YahooProvider();
      EmailProvider c = p.clone();
      assertEquals(p.getTransportHost(), c.getTransportHost());
      assertEquals(p.getStoreHost(), c.getStoreHost());
      assertEquals(p.getTransportProtocol(), c.getTransportProtocol());
      assertEquals(p.getStoreProtocol(), c.getStoreProtocol());
  }

  @Test(timeout = 4000)
  public void test29_propertiesHostsMatchGetterValues() throws Throwable {
      YahooProvider p = new YahooProvider();
      Properties props = p.getProperties();
      assertEquals(p.getTransportHost(), props.get("mail.smtps.host"));
      assertEquals(p.getStoreHost(), props.get("mail.imaps.host"));
      assertEquals(String.valueOf(p.getStorePort()), props.get("mail.imaps.port"));
  }

  @Test(timeout = 4000)
  public void test30_cloneSharesPropertiesIdentity_butCredentialsIndependent() throws Throwable {
      YahooProvider p = new YahooProvider();
      p.setUsername("u");
      p.setPassword("pw");
      EmailProvider c = p.clone();

      // همان آبجکت پراپرتی‌ها (استاتیک/مشترک)
      assertSame(p.getProperties(), c.getProperties());

      // اما اعتبارنامه‌ها مستقل‌اند
      assertEquals("u", c.getUsername());
      assertEquals("pw", c.getPassword());
      p.setUsername("u2");
      p.setPassword("pw2");
      assertEquals("pw", c.getPassword());
      assertEquals("u", c.getUsername());
  }

  @Test(timeout = 4000)
  public void test31_authFlag_isAlwaysTrue_evenIfPropsSayFalse() throws Throwable {
      YahooProvider p = new YahooProvider();
      assertTrue(p.isAuthenticationEnabled());

      // تغییر پراپرتی auth نباید فلگ داخلی را عوض کند
      Properties props = p.getProperties();
      Object prev = props.put("mail.smtps.auth", "false");
      try {
          assertTrue(p.isAuthenticationEnabled());
      } finally {
          if (prev == null) props.remove("mail.smtps.auth"); else props.put("mail.smtps.auth", prev);
      }
  }
}
