/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 12 22:03:49 GMT 2025
 */

package kwicdeltaj.prod1.kwic;

import org.junit.Test;
import static org.junit.Assert.*;
import kwicdeltaj.prod1.kwic.StringStorage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.BeforeClass;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class StringStorage_ESTest extends StringStorage_ESTest_scaffolding {

  // --- Added: one-time delay (~4.5s) before running any test in this class
  @BeforeClass
  public static void slowDownSuite() throws Exception {
      Thread.sleep(4500L);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      stringStorage0.setRight("y$]-jbRYk+J1");
      String string0 = stringStorage0.getRight();
      assertEquals("y$]-jbRYk+J1", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      stringStorage0.right = "Y[mD`w@R[KW";
      stringStorage0.right = "";
      String string0 = stringStorage0.getRight();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      stringStorage0.setLeft("q<Hc");
      String string0 = stringStorage0.getLeft();
      assertEquals("q<Hc", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      stringStorage0.setKeyword("y$]-jbRYk+J1");
      String string0 = stringStorage0.getKeyword();
      assertEquals("y$]-jbRYk+J1", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      stringStorage0.setLeft("");
      String string0 = stringStorage0.getLeft();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      String string0 = stringStorage0.getRight();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      String string0 = stringStorage0.getLeft();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      String string0 = stringStorage0.getKeyword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      StringStorage stringStorage0 = new StringStorage();
      stringStorage0.setKeyword("");
      String string0 = stringStorage0.getKeyword();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test9_setAllFields_thenGettersReturnSame() throws Throwable {
      StringStorage ss = new StringStorage();
      ss.setLeft("L");
      ss.setKeyword("K");
      ss.setRight("R");

      assertEquals("L", ss.getLeft());
      assertEquals("K", ss.getKeyword());
      assertEquals("R", ss.getRight());
  }

  @Test(timeout = 4000)
  public void test10_overwriteValues_lastWriteWins() throws Throwable {
      StringStorage ss = new StringStorage();
      ss.setLeft("L1");
      ss.setLeft("L2");
      ss.setKeyword("K1");
      ss.setKeyword("K2");
      ss.setRight("R1");
      ss.setRight("R2");

      assertEquals("L2", ss.getLeft());
      assertEquals("K2", ss.getKeyword());
      assertEquals("R2", ss.getRight());
  }

  @Test(timeout = 4000)
  public void test11_setNullValues_allowedAndReturned() throws Throwable {
      StringStorage ss = new StringStorage();
      ss.setLeft(null);
      ss.setKeyword(null);
      ss.setRight(null);

      assertNull(ss.getLeft());
      assertNull(ss.getKeyword());
      assertNull(ss.getRight());
  }

  @Test(timeout = 4000)
  public void test12_whitespacePreserved() throws Throwable {
      StringStorage ss = new StringStorage();
      ss.setLeft("  lead ");
      ss.setKeyword(" mid  ");
      ss.setRight("\t right\t");

      assertEquals("  lead ", ss.getLeft());
      assertEquals(" mid  ", ss.getKeyword());
      assertEquals("\t right\t", ss.getRight());
  }

  @Test(timeout = 4000)
  public void test13_unicodePersianAndEmoji() throws Throwable {
      StringStorage ss = new StringStorage();
      ss.setLeft("سمتِ چپ");
      ss.setKeyword("کلیدواژه🔑");
      ss.setRight("راست😊");

      assertEquals("سمتِ چپ", ss.getLeft());
      assertEquals("کلیدواژه🔑", ss.getKeyword());
      assertEquals("راست😊", ss.getRight());
  }

  @Test(timeout = 4000)
  public void test14_directFieldMutation_reflectedInGetters() throws Throwable {
      // چون فیلدها package-private هستند، در همین پکیج تست قابل دسترسی‌اند
      StringStorage ss = new StringStorage();
      ss.left = "DirectL";
      ss.keyword = "DirectK";
      ss.right = "DirectR";

      assertEquals("DirectL", ss.getLeft());
      assertEquals("DirectK", ss.getKeyword());
      assertEquals("DirectR", ss.getRight());
  }

}
