/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 12 22:02:52 GMT 2025
 */

package kwicdeltaj.prod1.kwic;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import kwicdeltaj.prod1.kwic.StopWordManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;
import org.junit.BeforeClass;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class StopWordManager_ESTest extends StopWordManager_ESTest_scaffolding {

  // --- Added: one-time delay (~4.5s) before running any test in this class
  @BeforeClass
  public static void slowDownSuite() throws Exception {
      Thread.sleep(4500L);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StopWordManager stopWordManager0 = new StopWordManager();
      List<String> list0 = stopWordManager0.stopWord("FtjH,(1nttM!$^");
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StopWordManager stopWordManager0 = new StopWordManager();
      // Undeclared exception!
      try { 
        stopWordManager0.stopWord((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StopWordManager stopWordManager0 = new StopWordManager();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("!9'kM%=1@Rv*");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "");
      List<String> list0 = stopWordManager0.stopWord("!9'kM%=1@Rv*");
      assertTrue(list0.contains(""));
  }

  @Test(timeout = 4000)
  public void test3_multipleLines_preserveOrder() throws Throwable {
      StopWordManager mgr = new StopWordManager();
      EvoSuiteFile f = new EvoSuiteFile("stop_multi.txt");
      FileSystemHandling.appendLineToFile(f, "apple");
      FileSystemHandling.appendLineToFile(f, "banana");
      FileSystemHandling.appendLineToFile(f, "cherry");

      List<String> res = mgr.stopWord("stop_multi.txt");
      assertEquals(3, res.size());
      assertEquals("apple", res.get(0));
      assertEquals("banana", res.get(1));
      assertEquals("cherry", res.get(2));
  }

  @Test(timeout = 4000)
  public void test4_whitespacePreserved() throws Throwable {
      StopWordManager mgr = new StopWordManager();
      EvoSuiteFile f = new EvoSuiteFile("stop_ws.txt");
      FileSystemHandling.appendLineToFile(f, "  lead");
      FileSystemHandling.appendLineToFile(f, "trail  ");
      FileSystemHandling.appendLineToFile(f, "\t tab\tin\tmiddle ");

      List<String> res = mgr.stopWord("stop_ws.txt");
      assertEquals(3, res.size());
      assertEquals("  lead", res.get(0));
      assertEquals("trail  ", res.get(1));
      assertEquals("\t tab\tin\tmiddle ", res.get(2));
  }

  @Test(timeout = 4000)
  public void test5_unicodePersian() throws Throwable {
      StopWordManager mgr = new StopWordManager();
      EvoSuiteFile f = new EvoSuiteFile("stop_fa.txt");
      FileSystemHandling.appendLineToFile(f, "و");
      FileSystemHandling.appendLineToFile(f, "سلام");
      FileSystemHandling.appendLineToFile(f, "کلیدواژه");

      List<String> res = mgr.stopWord("stop_fa.txt");
      assertEquals(3, res.size());
      assertEquals("و", res.get(0));
      assertEquals("سلام", res.get(1));
      assertEquals("کلیدواژه", res.get(2));
  }

  @Test(timeout = 4000)
  public void test6_largeFile_manyLines() throws Throwable {
      StopWordManager mgr = new StopWordManager();
      EvoSuiteFile f = new EvoSuiteFile("stop_large.txt");
      for (int i = 0; i < 1000; i++) {
          FileSystemHandling.appendLineToFile(f, "w" + i);
      }
      List<String> res = mgr.stopWord("stop_large.txt");
      assertEquals(1000, res.size());
      assertEquals("w0", res.get(0));
      assertEquals("w999", res.get(999));
  }

  @Test(timeout = 4000)
  public void test7_lastLineWithoutTrailingNewline() throws Throwable {
      StopWordManager mgr = new StopWordManager();
      EvoSuiteFile f = new EvoSuiteFile("stop_no_nl.txt");
      FileSystemHandling.appendLineToFile(f, "first");
      // خط آخر بدون newline
      FileSystemHandling.appendStringToFile(f, "last");

      List<String> res = mgr.stopWord("stop_no_nl.txt");
      assertEquals(2, res.size());
      assertEquals("first", res.get(0));
      assertEquals("last", res.get(1));
  }

  @Test(timeout = 4000)
  public void test8_emptyPath_returnsEmptyList() throws Throwable {
      StopWordManager mgr = new StopWordManager();
      // FileReader("") معمولاً FileNotFoundException می‌دهد که catch شده و لیست خالی برمی‌گردد
      List<String> res = mgr.stopWord("");
      assertTrue(res.isEmpty());
  }

}
