/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 01 11:21:08 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleSearchCommand;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ConsoleSearchCommand_ESTest extends ConsoleSearchCommand_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsoleSearchCommand consoleSearchCommand0 = new ConsoleSearchCommand();
      consoleSearchCommand0.handleExecute();
      assertEquals("search", consoleSearchCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConsoleSearchCommand consoleSearchCommand0 = new ConsoleSearchCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      List<String> list0 = linkedList0.subList(0, 0);
      linkedList0.add("search");
      consoleSearchCommand0.setParameters(list0);
      // Undeclared exception!
      try { 
        consoleSearchCommand0.handleExecute();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsoleSearchCommand consoleSearchCommand0 = new ConsoleSearchCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offer("search");
      linkedList0.add("search");
      consoleSearchCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        consoleSearchCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ConsoleSearchCommand consoleSearchCommand0 = new ConsoleSearchCommand();
      consoleSearchCommand0.explain();
      assertEquals("search", consoleSearchCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ConsoleSearchCommand consoleSearchCommand0 = new ConsoleSearchCommand();
      String string0 = consoleSearchCommand0.getCommandName();
      assertEquals("search", string0);
  }
  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // اجرای موفق مسیر تا SystemFacade.search با یک پارامتر ساده → انتظار NoClassDefFoundError
      ConsoleSearchCommand cmd = new ConsoleSearchCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("hello");
      cmd.setParameters(params);

      try {
        cmd.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
        verifyException("irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // چند پارامتر که باید با فاصله به هم چسبیده شوند؛ باز هم در نهایت NoClassDefFoundError
      ConsoleSearchCommand cmd = new ConsoleSearchCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("quick");
      params.add("brown");
      params.add("fox");
      cmd.setParameters(params);

      try {
        cmd.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
        verifyException("irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // وجود null در لیست پارامترها نباید NPE بدهد؛ به رشته "null" کانکت می‌شود و به SystemFacade می‌رسد
      ConsoleSearchCommand cmd = new ConsoleSearchCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("foo");
      params.add((String) null);
      params.add("bar");
      cmd.setParameters(params);

      try {
        cmd.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
        verifyException("irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      // بررسی خروجی explain()
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream old = System.out;
      try {
        System.setOut(ps);
        ConsoleSearchCommand cmd = new ConsoleSearchCommand();
        cmd.explain();
      } finally {
        System.setOut(old);
      }
      String out = baos.toString();
      assertTrue(out.contains("(search"));
      // معمولاً شامل کلید پیام هم هست
      assertTrue(out.contains("command.search.explain"));
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      // getCommandName باید با ثابت کلاس یکی باشد
      ConsoleSearchCommand cmd = new ConsoleSearchCommand();
      assertEquals(ConsoleSearchCommand.COMMAND_SEARCH, cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // ست‌کردن یک لیست غیرقابل‌تغییر به‌عنوان پارامترها
      ConsoleSearchCommand cmd = new ConsoleSearchCommand();
      LinkedList<String> base = new LinkedList<String>();
      base.add("term");
      java.util.List<String> unmod = java.util.Collections.unmodifiableList(base);
      cmd.setParameters(unmod);

      try {
        cmd.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
        verifyException("irisdeltaj.simpleluceneaddressbooktag.br.unb.cic.iris.command.console.ConsoleSearchCommand", e);
      }
  }

}
