/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 01 11:35:22 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.util;

import org.junit.Test;
import org.junit.Before;

import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.util.MessageUtils;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.SequenceInputStream;
import java.util.Enumeration;
import java.util.Vector;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MessageUtils_ESTest extends MessageUtils_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای پیش از اجرای هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Enumeration<DataInputStream> enumeration0 = (Enumeration<DataInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false, true).when(enumeration0).hasMoreElements();
      doReturn((Object) null).when(enumeration0).nextElement();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      // Undeclared exception!
      try { 
        MessageUtils.getStringFromInputStream(sequenceInputStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.SequenceInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageUtils.getMimeType((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationalsecuritysignverify.br.unb.cic.iris.util.MessageUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (-406), 2317);
      // Undeclared exception!
      try { 
        MessageUtils.getStringFromInputStream(byteArrayInputStream0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // Undeclared exception!
      try { 
        MessageUtils.getStringFromInputStream((InputStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      String string0 = MessageUtils.getStringFromInputStream(pipedInputStream0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      String string0 = MessageUtils.getStringFromInputStream(byteArrayInputStream0);
      assertEquals("\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = MessageUtils.getMimeType("6/c-qI");
      assertEquals("6/c-qi", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      String string0 = MessageUtils.getMimeType("");
      assertEquals("unknown", string0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MessageUtils messageUtils0 = new MessageUtils();
  }

  @Test(timeout = 4000)
  public void test9() throws Throwable {
      // باید بخش MIME قبل از سمی‌کالن و به صورت lower-case برگردد
      String mt = MessageUtils.getMimeType("  text/plain ; charset=UTF-8  ");
      assertEquals("text/plain", mt);
  }

  @Test(timeout = 4000)
  public void test10() throws Throwable {
      // حروف بزرگ/مخلوط → خروجی lower-case
      String mt = MessageUtils.getMimeType("TEXT/HTML; CHARSET=UTF-8");
      assertEquals("text/html", mt);
  }

  @Test(timeout = 4000)
  public void test11() throws Throwable {
      // فقط فاصله یا فقط ; → توکنی وجود ندارد → unknown
      assertEquals("unknown", MessageUtils.getMimeType("   "));
      assertEquals("unknown", MessageUtils.getMimeType(";"));
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
      // خطوط باید بدون newline به هم چسبیده شوند (readLine \n را حذف می‌کند)
      String nl = System.getProperty("line.separator");
      String input = "aa" + nl + "bb" + nl + "cc";
      ByteArrayInputStream is = new ByteArrayInputStream(input.getBytes("UTF-8"));
      String out = MessageUtils.getStringFromInputStream(is);
      assertEquals("aabbcc", out);
  }

  @Test(timeout = 4000)
  public void test13() throws Throwable {
      // ورودی صفر بایتی → رشتهٔ خالی
      ByteArrayInputStream is = new ByteArrayInputStream(new byte[0]);
      String out = MessageUtils.getStringFromInputStream(is);
      assertEquals("", out);
  }

  @Test(timeout = 4000)
  public void test14() throws Throwable {
      // استریم که در read() IOException می‌دهد → تابع باید رشتهٔ خالی برگرداند (و استثناء را لاگ کند)
      java.io.InputStream boom = new java.io.InputStream() {
          @Override public int read() throws java.io.IOException { throw new java.io.IOException("boom"); }
      };
      String out = MessageUtils.getStringFromInputStream(boom);
      assertEquals("", out);
  }

  @Test(timeout = 4000)
  public void test15() throws Throwable {
      // بدون پارامتر سمی‌کالن: فقط نوع
      assertEquals("application/json", MessageUtils.getMimeType("application/json"));
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  @Test(timeout = 4000)
  public void test16_getStringFromInputStream_CRLF_isRemoved() throws Throwable {
      String input = "A\r\nB\r\nC";
      ByteArrayInputStream is = new ByteArrayInputStream(input.getBytes("UTF-8"));
      String out = MessageUtils.getStringFromInputStream(is);
      assertEquals("ABC", out);
  }

  @Test(timeout = 4000)
  public void test17_getStringFromInputStream_unicodeConcatenation() throws Throwable {
      String input = "سلام\nدنیا\n🙂";
      ByteArrayInputStream is = new ByteArrayInputStream(input.getBytes("UTF-8"));
      String out = MessageUtils.getStringFromInputStream(is);
      assertEquals("سلامدنیا🙂", out);
  }

  @Test(timeout = 4000)
  public void test18_getStringFromInputStream_sequenceInputStream_concatenates() throws Throwable {
      ByteArrayInputStream a = new ByteArrayInputStream("foo\n".getBytes("UTF-8"));
      ByteArrayInputStream b = new ByteArrayInputStream("bar".getBytes("UTF-8"));
      Vector<InputStream> parts = new Vector<>();
      parts.add(a); parts.add(b);
      SequenceInputStream seq = new SequenceInputStream(parts.elements());
      String out = MessageUtils.getStringFromInputStream(seq);
      assertEquals("foobar", out);
  }


  @Test(timeout = 4000)
  public void test20_getMimeType_multipleParams_tabsNewlines() throws Throwable {
      String mt = MessageUtils.getMimeType("  Application/XML\t;\ncharset=UTF-8 ; version=1.0 ");
      assertEquals("application/xml", mt);
  }

  @Test(timeout = 4000)
  public void test21_getMimeType_trailingSemicolon_isIgnored() throws Throwable {
      String mt = MessageUtils.getMimeType("image/png ; ");
      assertEquals("image/png", mt);
  }

  @Test(timeout = 4000)
  public void test22_getMimeType_quotedParams_keepsBaseType() throws Throwable {
      String mt = MessageUtils.getMimeType("message/rfc822; name=\"mail.eml\"; boundary=\"--abc\"");
      assertEquals("message/rfc822", mt);
  }

  @Test(timeout = 4000)
  public void test23_getMimeType_multipleSemicolonsOnly_unknown() throws Throwable {
      assertEquals("unknown", MessageUtils.getMimeType(";;;   ;"));
  }
}
