/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 21:47:35 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import org.junit.Before;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.lang.reflect.Field;
import java.util.Date;

import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleListMessagesCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ConsoleListMessagesCommand_ESTest extends ConsoleListMessagesCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای قبل از اجرای هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsoleListMessagesCommand consoleListMessagesCommand0 = new ConsoleListMessagesCommand();
      consoleListMessagesCommand0.handleExecute();
      assertEquals("ls", consoleListMessagesCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConsoleListMessagesCommand consoleListMessagesCommand0 = new ConsoleListMessagesCommand();
      String string0 = consoleListMessagesCommand0.getCommandName();
      assertEquals("ls", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsoleListMessagesCommand consoleListMessagesCommand0 = new ConsoleListMessagesCommand();
      consoleListMessagesCommand0.explain();
      assertEquals("ls", consoleListMessagesCommand0.getCommandName());
  }

  /** helper: گرفتن stdout هنگام اجرای یک Runnable (بدون لامبدا) */
  private String captureStdout(final Runnable r) {
      PrintStream orig = System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      System.setOut(ps);
      try {
          r.run();
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test3_explain_printsUsageLine() throws Throwable {
      final ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out.contains("(ls)"));
      assertTrue(out.toLowerCase().contains("list messages"));
      assertEquals("ls", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test4_explain_multipleCalls_consistentOutput() throws Throwable {
      final ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out1.contains("(ls)"));
      assertTrue(out2.contains("(ls)"));
  }

  @Test(timeout = 4000)
  public void test5_handleExecute_noCrash_captureStdout() throws Throwable {
      final ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      String out = null;
      try {
          out = captureStdout(new Runnable() { @Override public void run() {
              try { cmd.handleExecute(); } catch (Throwable t) { /* زیرساخت ممکن است نباشد */ }
          }});
      } catch (Throwable ignored) { }
      assertNotNull(out); // حداقل گرفتن خروجی موفق بوده
      // اگر چیزی چاپ شده باشد، معمولاً با "1 - " شروع می‌شود؛ در غیر این صورت هم تست نباید بشکند
      if (!out.trim().isEmpty()) {
          assertTrue(out.contains(" - "));
      }
  }

  @Test(timeout = 4000)
  public void test6_formatter_containsAtKeyword_whenFormattingEpoch() throws Throwable {
      ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      // دسترسی به فیلد formatter با رفلکشن
      Field f = ConsoleListMessagesCommand.class.getDeclaredField("formatter");
      f.setAccessible(true);
      java.text.DateFormat df = (java.text.DateFormat) f.get(cmd);
      String formatted = df.format(new Date(0L)); // بسته به Locale شکل تاریخ متفاوت است
      assertTrue("formatted should contain 'at'", formatted.contains("at"));
  }

  @Test(timeout = 4000)
  public void test7_getCommandName_nonEmpty_constant() throws Throwable {
      ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertFalse(name.isEmpty());
      assertEquals("ls", name);
  }

  @Test(timeout = 4000)
  public void test8_handleExecute_twice_idempotentNoStateLeak() throws Throwable {
      final ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      // نوبت اول
      try { cmd.handleExecute(); } catch (Throwable ignored) {}
      // نوبت دوم
      try { cmd.handleExecute(); } catch (Throwable ignored) {}
      assertEquals("ls", cmd.getCommandName());
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  @Test(timeout = 4000)
  public void test9_explain_twoInstances_sameOutput() throws Throwable {
      final ConsoleListMessagesCommand a = new ConsoleListMessagesCommand();
      final ConsoleListMessagesCommand b = new ConsoleListMessagesCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { a.explain(); }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { b.explain(); }});
      assertEquals(out1.trim(), out2.trim());
  }

  @Test(timeout = 4000)
  public void test10_explain_startsWithParenCommand() throws Throwable {
      final ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String expectedPrefix = "(" + cmd.getCommandName() + ")";
      assertTrue("Explain output should start with (ls)", out.trim().startsWith(expectedPrefix));
  }

  @Test(timeout = 4000)
  public void test11_handleExecute_stdout_notNull_onSecondRun() throws Throwable {
      final ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      // اجرا و گرفتن خروجی دو بار
      captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertNotNull(out2);
  }

  @Test(timeout = 4000)
  public void test12_getCommandName_trim_lowercase() throws Throwable {
      ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      String name = cmd.getCommandName();
      assertEquals("ls", name);
      assertEquals(name, name.trim());
      assertEquals("ls", name.toLowerCase());
  }

  @Test(timeout = 4000)
  public void test13_formatter_formatsNow_containsTimeSeparator() throws Throwable {
      ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      Field f = ConsoleListMessagesCommand.class.getDeclaredField("formatter");
      f.setAccessible(true);
      java.text.DateFormat df = (java.text.DateFormat) f.get(cmd);
      String formatted = df.format(new Date());
      // معمولاً زمان دارای ':' است؛ اگر Locale متفاوت باشد، صرفاً وجود خروجی غیر تهی را هم چک می‌کنیم
      assertNotNull(formatted);
      assertFalse(formatted.trim().isEmpty());
  }

  @Test(timeout = 4000)
  public void test14_explain_then_handleExecute_stdoutCaptured() throws Throwable {
      final ConsoleListMessagesCommand cmd = new ConsoleListMessagesCommand();
      // ابتدا explain
      captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      // سپس handleExecute
      String out = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertNotNull(out);
  }

}
