/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 01 14:13:43 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.CategoryConsoleCommand;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CategoryConsoleCommand_ESTest extends CategoryConsoleCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای قبل از هر تست */
  @Before
  public void halfSecondDelay() {
      try { Thread.sleep(500L); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("list");
      linkedList0.offerLast("list");
      linkedList0.add("");
      categoryConsoleCommand0.setParameters(linkedList0);
      categoryConsoleCommand0.execute();
      assertEquals("category", categoryConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      // Undeclared exception!
      try {
        categoryConsoleCommand0.handleExecute();
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offerLast("list");
      categoryConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try {
        categoryConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationalcategory/br/unb/cic/iris/persistence/relational/CategoryDAO
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      categoryConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try {
        categoryConsoleCommand0.handleExecute();
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("list");
      linkedList0.offerLast("list");
      categoryConsoleCommand0.setParameters(linkedList0);
      categoryConsoleCommand0.execute();
      assertEquals("category", categoryConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.offer("n9A x]VUQRvbYf@O");
      categoryConsoleCommand0.setParameters(linkedList0);
      try {
        categoryConsoleCommand0.handleExecute();
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // n9A x]VUQRvbYf@O is an invalid command
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      String string0 = categoryConsoleCommand0.getCommandName();
      assertEquals("category", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      CategoryConsoleCommand categoryConsoleCommand0 = new CategoryConsoleCommand();
      categoryConsoleCommand0.explain();
      assertEquals("category", categoryConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      // دستور با حروف بزرگ باید نامعتبر باشد
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("LIST");
      cmd.setParameters(params);

      try {
        cmd.handleExecute();
        fail("Expecting exception: Exception");
      } catch (Exception e) {
        assertEquals("LIST is an invalid command", e.getMessage());
        verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      // category مشخص → مسیر list(category) و انتظار NoClassDefFoundError از CategoryManager/DAO
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add("Work");
      cmd.setParameters(params);

      try {
        cmd.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
        verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // پارامترهای بیشتر از 2 → listAll() و باز هم وابستگی به CategoryManager
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add("A");
      params.add("B");
      cmd.setParameters(params);

      try {
        cmd.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
        verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      // دستور فقط فاصله‌ها → نامعتبر
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("   ");
      cmd.setParameters(params);

      try {
        cmd.handleExecute();
        fail("Expecting exception: Exception");
      } catch (Exception e) {
        assertEquals("   is an invalid command", e.getMessage());
        verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // بررسی فرمت تاریخِ formatter (باید ' at ' در خروجی باشد)
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      String formatted = cmd.formatter.format(new java.util.Date());
      assertTrue(formatted.contains(" at "));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // پارامترها = null → باید NullPointerException بدهد
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      cmd.setParameters(null);

      try {
        cmd.handleExecute();
        fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
        verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test14_mixedCaseCommand_invalid() throws Throwable {
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("List"); // حروف مخلوط → نامعتبر
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          assertEquals("List is an invalid command", e.getMessage());
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test15_listWithEmptySecondParam_reachesManager() throws Throwable {
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add(""); // خالی → همچنان به شاخهٔ list هدایت می‌شود
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test16_handleExecute_twice_sameInvalidCommand() throws Throwable {
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("BAD");
      cmd.setParameters(params);
      try { cmd.handleExecute(); fail("Expected Exception"); } catch (Exception ignored) {}
      // بار دوم نیز باید همان رفتار را داشته باشد
      try { cmd.handleExecute(); fail("Expected Exception"); } catch (Exception e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test17_listWithNullCategory_throwsNPE() throws Throwable {
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add((String) null); // آرگومان دوم null
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.command.console.CategoryConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test18_explain_multipleCalls_noCrash() throws Throwable {
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      cmd.explain();
      cmd.explain();
      assertEquals("category", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test19_parametersMutatedAfterSet_stillExecutesAgainstCurrentList() throws Throwable {
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add("X");
      cmd.setParameters(params);
      // تغییر لیست بعد از set (برخی پیاده‌سازی‌ها رفرنس را نگه می‌دارند)
      params.set(1, "Y");
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test20_listWithWhitespaceCategory_callsManager() throws Throwable {
      CategoryConsoleCommand cmd = new CategoryConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add(" "); // به عنوان نام دسته‌بندیِ whitespace
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }
}
