/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 21:01:49 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.TagConsoleCommand;
import java.security.InvalidParameterException;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TagConsoleCommand_ESTest extends TagConsoleCommand_ESTest_scaffolding {
	@Before
	public void halfSecondDelay() throws Exception {
	    try {
	        Thread.sleep(500L);
	    } catch (InterruptedException ignored) { }
	}
  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      linkedList0.add("add");
      linkedList0.add("");
      linkedList0.add("W]8PXzRRn\"q");
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("list");
      linkedList0.add("list");
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("");
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      linkedList0.add("add");
      linkedList0.add("add");
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // For input string: \"add\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      linkedList0.add("3");
      linkedList0.add("3");
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("list");
      linkedList0.add("list");
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/EmailDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("lIs");
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // lIs is an invalid command
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("list");
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      // Undeclared exception!
      try { 
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      String string0 = tagConsoleCommand0.getCommandName();
      assertEquals("tag", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      tagConsoleCommand0.explain();
      assertEquals("tag", tagConsoleCommand0.getCommandName());
  }
  @Test(timeout = 4000)
  public void test11() throws Throwable {
      // parameters = null  → NPE
      TagConsoleCommand cmd = new TagConsoleCommand();
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
      // دستور نامعتبر با فاصله‌ی انتهایی → به شاخه default می‌رود و EmailException پرتاب می‌شود
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add "); // توجه: space انتهایی
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          // "add " is an invalid command
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test13() throws Throwable {
      // add با فقط یک آرگومانِ عددی → InvalidParameterException
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("1");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: InvalidParameterException");
      } catch (InvalidParameterException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test14() throws Throwable {
      // add با index = 0  → currentMessages احتمالا null است و NPE می‌دهد
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("0");
      params.add("tag1,tag2");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test15() throws Throwable {
      // list با سه آرگومان → listAll صدا می‌خورد و به TagManager وابسته است → NoClassDefFoundError
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("list");
      params.add("myTag");
      params.add("extra");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          // TagDAO/TagManager در محیط تست وجود ندارد
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test16() throws Throwable {
      // list با آرگومان خالی → باز هم به TagManager می‌رسد → NoClassDefFoundError
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("list");
      params.add("");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test17() throws Throwable {
      // add با idx غیرعددی خالی → NumberFormatException
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("");
      params.add("t1");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NumberFormatException");
      } catch (NumberFormatException e) {
          verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test18() throws Throwable {
      // add با idx منفی → قبل از هر چیز به currentMessages (که null است) دسترسی می‌زند → NPE
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("-5");
      params.add("alpha,beta");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }
  @Test(timeout = 4000)
  public void test19() throws Throwable {
      // دستور ناشناخته → Exception با پیام invalid command
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("help");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          // "help is an invalid command"
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test20() throws Throwable {
      // setParameters(null) سپس handle → NPE
      TagConsoleCommand cmd = new TagConsoleCommand();
      cmd.setParameters((LinkedList<String>) null);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test21() throws Throwable {
      // add با ایندکس غیرعددی → NumberFormatException
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("NaN");
      params.add("t1");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NumberFormatException");
      } catch (NumberFormatException e) {
          verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test22() throws Throwable {
      // add با ایندکس خیلی بزرگ → قبل از دسترسی به DAO روی currentMessages کرش می‌کند (NPE)
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add(String.valueOf(Integer.MAX_VALUE));
      params.add("tagA,tagB");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test23() throws Throwable {
      // list با برچسب یونیکد → وابستگی TagManager/DAO وجود ندارد → NoClassDefFoundError
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("list");
      params.add("سلام");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test24() throws Throwable {
      // پایداری نام دستور پس از شکست
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("unknown-cmd");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          // expected
      }
      assertEquals("tag", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test25() throws Throwable {
      // explain چندباره و ثبات نام
      TagConsoleCommand cmd = new TagConsoleCommand();
      cmd.explain();
      cmd.explain();
      assertEquals("tag", cmd.getCommandName());
  }


}
