/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 01 14:16:18 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.CategoryManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CategoryManager_ESTest extends CategoryManager_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای قبل از هر تست (سازگار با timeout=4000ms) */
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CategoryManager categoryManager0 = CategoryManager.instance();
      // Undeclared exception!
      try { 
        categoryManager0.getCategoryDAO();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationalcategory/br/unb/cic/iris/persistence/relational/CategoryDAO
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CategoryManager categoryManager0 = CategoryManager.instance();
      // Undeclared exception!
      try { 
        categoryManager0.listMessagesByCategory("z8z<\u007fM/1U<5l/Xj");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationalcategory/br/unb/cic/iris/persistence/relational/EmailDAO
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CategoryManager categoryManager0 = CategoryManager.instance();
      // Undeclared exception!
      try { 
        categoryManager0.findByName("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationalcategory/br/unb/cic/iris/persistence/relational/CategoryDAO
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CategoryManager categoryManager0 = CategoryManager.instance();
      // Undeclared exception!
      try { 
        categoryManager0.findById("");
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationalcategory/br/unb/cic/iris/persistence/relational/CategoryDAO
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CategoryManager categoryManager0 = CategoryManager.instance();
      // Undeclared exception!
      try { 
        categoryManager0.findAll();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationalcategory/br/unb/cic/iris/persistence/relational/CategoryDAO
         //
         verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // singleton باید یکتا و غیر null باشد
      CategoryManager a = CategoryManager.instance();
      CategoryManager b = CategoryManager.instance();
      assertNotNull(a);
      assertSame(a, b);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // findByName با null نیز به علت وابستگی DAO باید NoClassDefFoundError بدهد
      CategoryManager cm = CategoryManager.instance();
      try {
          cm.findByName((String) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          // CategoryDAO در لایهٔ persistence در دسترس نیست
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // findById با null نیز به همان دلیل شکست می‌خورد
      CategoryManager cm = CategoryManager.instance();
      try {
          cm.findById((String) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      // listMessagesByCategory با null → وابستگی EmailDAO برقرار نیست
      CategoryManager cm = CategoryManager.instance();
      try {
          cm.listMessagesByCategory((String) null);
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      // findAll چند بار پیاپی نیز باید همان خطا را بدهد (پایداری رفتار)
      CategoryManager cm = CategoryManager.instance();
      for (int i = 0; i < 2; i++) {
          try {
              cm.findAll();
              fail("Expecting exception: NoClassDefFoundError");
          } catch (NoClassDefFoundError e) {
              verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
          }
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      // getCategoryDAO چند بار پیاپی نیز همان خطا را برمی‌گرداند
      CategoryManager cm = CategoryManager.instance();
      try {
          cm.getCategoryDAO();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
      try {
          cm.getCategoryDAO();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  // =================== تست‌های اضافه‌شده ===================

  @Test(timeout = 4000)
  public void test11_findByName_multipleInputs_consistentFailure() throws Throwable {
      CategoryManager cm = CategoryManager.instance();
      String[] names = {"inbox", "Work", "", "   ", "🔥"};
      for (String n : names) {
          try {
              cm.findByName(n);
              fail("Expecting exception: NoClassDefFoundError for name=" + n);
          } catch (NoClassDefFoundError e) {
              verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
          }
      }
  }

  @Test(timeout = 4000)
  public void test12_listMessagesByCategory_emptyString_throws() throws Throwable {
      CategoryManager cm = CategoryManager.instance();
      try {
          cm.listMessagesByCategory("");
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test13_toString_notNull() throws Throwable {
      CategoryManager cm = CategoryManager.instance();
      String s = cm.toString(); // حتی اگر پیش‌فرض Object باشد، نباید null باشد
      assertNotNull(s);
      assertFalse(s.isEmpty());
  }

  @Test(timeout = 4000)
  public void test14_instance_isSameAcrossThreads() throws Throwable {
      final CategoryManager[] refs = new CategoryManager[2];
      Thread t1 = new Thread(new Runnable() {
          @Override public void run() { refs[0] = CategoryManager.instance(); }
      });
      Thread t2 = new Thread(new Runnable() {
          @Override public void run() { refs[1] = CategoryManager.instance(); }
      });
      t1.start(); t2.start();
      t1.join();  t2.join();
      assertNotNull(refs[0]);
      assertNotNull(refs[1]);
      assertSame(refs[0], refs[1]);
  }

  @Test(timeout = 4000)
  public void test15_findById_multipleCalls_consistentFailure() throws Throwable {
      CategoryManager cm = CategoryManager.instance();
      String[] ids = {"1", "abc", "", null};
      for (String id : ids) {
          try {
              cm.findById(id);
              fail("Expecting exception: NoClassDefFoundError for id=" + id);
          } catch (NoClassDefFoundError e) {
              verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
          }
      }
  }

  @Test(timeout = 4000)
  public void test16_findAll_multipleTimes_stable() throws Throwable {
      CategoryManager cm = CategoryManager.instance();
      for (int i = 0; i < 3; i++) {
          try {
              cm.findAll();
              fail("Expecting exception: NoClassDefFoundError (iteration " + i + ")");
          } catch (NoClassDefFoundError e) {
              verifyException("irisdeltaj.simplerelationalcategory.br.unb.cic.iris.core.CategoryManager", e);
          }
      }
  }
}
