/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 23:08:51 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command;

import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.AbstractMailCommand;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleListRemoteFoldersCommand;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.DownloadMessagesConsoleCommand;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ReadMessageConsoleCommand;
import java.util.LinkedList;
import java.util.MissingResourceException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AbstractMailCommand_ESTest extends AbstractMailCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای پیش از اجرای هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsoleListRemoteFoldersCommand consoleListRemoteFoldersCommand0 = new ConsoleListRemoteFoldersCommand();
      consoleListRemoteFoldersCommand0.execute();
      assertEquals("lr", consoleListRemoteFoldersCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReadMessageConsoleCommand readMessageConsoleCommand0 = new ReadMessageConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("~&(s4jR]Bx");
      readMessageConsoleCommand0.setParameters(linkedList0);
      readMessageConsoleCommand0.execute();
      assertEquals("read", readMessageConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReadMessageConsoleCommand readMessageConsoleCommand0 = new ReadMessageConsoleCommand();
      readMessageConsoleCommand0.execute();
      assertEquals("read", readMessageConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String string0 = AbstractMailCommand.message("error.validation");
      assertEquals("Validation error", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        AbstractMailCommand.message("`Bqc!0FN{8ee");
        fail("Expecting exception: MissingResourceException");
      
      } catch(MissingResourceException e) {
         //
         // Can't find resource for bundle java.util.PropertyResourceBundle, key `Bqc!0FN{8ee
         //
         verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        AbstractMailCommand.message((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PropertyResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      DownloadMessagesConsoleCommand downloadMessagesConsoleCommand0 = new DownloadMessagesConsoleCommand();
      downloadMessagesConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        downloadMessagesConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.DownloadMessagesConsoleCommand", e);
      }
  }

  /** زیرکلاس موفق برای تست فراخوانی handleExecute و منطق پارامترها */
  private static class DummyOkCmd extends irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.AbstractMailCommand {
      boolean executed;
      int lastParamCount = -1;

      @Override public void explain() { /* no-op */ }
      @Override public String getCommandName() { return "dummy-ok"; }
      @Override protected void handleExecute() {
          executed = true;
          if (parameters != null) lastParamCount = parameters.size();
          java.lang.System.out.print("OK");
      }
      /** اکسپوز کردن validParameters برای تست */
      public boolean callValid() { return validParameters(); }
      public int getLastParamCount() { return lastParamCount; }
  }

  /** زیرکلاسی که RuntimeException می‌اندازد تا شاخه catch(Exception) پوشش داده شود */
  private static class DummyThrowsRuntime extends irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.AbstractMailCommand {
      @Override public void explain() {}
      @Override public String getCommandName() { return "dummy-rt"; }
      @Override protected void handleExecute() { throw new RuntimeException("boom"); }
  }

  /** زیرکلاسی که Error می‌اندازد تا catch(Throwable) پوشش داده شود */
  private static class DummyThrowsError extends irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.AbstractMailCommand {
      @Override public void explain() {}
      @Override public String getCommandName() { return "dummy-err"; }
      @Override protected void handleExecute() { throw new Error("die"); }
  }

  /** helper: گرفتن stdout به‌صورت امن (بدون تداخل با org.evosuite.runtime.System) */
  private String captureStdout(final Runnable r) {
      PrintStream orig = java.lang.System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      java.lang.System.setOut(ps);
      try { r.run(); } finally {
          java.lang.System.setOut(orig);
          ps.flush(); ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  /** helper: گرفتن stderr به‌صورت امن */
  private String captureStderr(final Runnable r) {
      PrintStream orig = java.lang.System.err;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      java.lang.System.setErr(ps);
      try { r.run(); } finally {
          java.lang.System.setErr(orig);
          ps.flush(); ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  /** helper: گرفتن همزمان stdout و stderr */
  private String[] captureOutErr(final Runnable r) {
      PrintStream origOut = java.lang.System.out;
      PrintStream origErr = java.lang.System.err;
      ByteArrayOutputStream bout = new ByteArrayOutputStream();
      ByteArrayOutputStream berr = new ByteArrayOutputStream();
      PrintStream pout = new PrintStream(bout);
      PrintStream perr = new PrintStream(berr);
      java.lang.System.setOut(pout);
      java.lang.System.setErr(perr);
      try { r.run(); } finally {
          java.lang.System.setOut(origOut);
          java.lang.System.setErr(origErr);
          pout.flush(); perr.flush();
          pout.close(); perr.close();
      }
      return new String[] {
          new String(bout.toByteArray(), StandardCharsets.UTF_8),
          new String(berr.toByteArray(), StandardCharsets.UTF_8)
      };
  }

  @Test(timeout = 4000)
  public void test7_execute_invokesHandle_andPrintsOK_andSeesParams() throws Throwable {
      final DummyOkCmd cmd = new DummyOkCmd();
      java.util.LinkedList<String> p = new java.util.LinkedList<String>();
      p.add("a"); p.add("b");
      cmd.setParameters(p);

      String out = captureStdout(new Runnable() { @Override public void run() { cmd.execute(); } });
      assertTrue(out.contains("OK"));
      assertTrue(cmd.executed);
      assertEquals(2, cmd.getLastParamCount());
      assertTrue(cmd.callValid());
  }

  @Test(timeout = 4000)
  public void test8_validParameters_false_whenNullOrEmpty() throws Throwable {
      DummyOkCmd cmd = new DummyOkCmd();
      // بدون پارامتر
      assertFalse(cmd.callValid());
      // پارامتر خالی
      java.util.LinkedList<String> empty = new java.util.LinkedList<String>();
      cmd.setParameters(empty);
      assertFalse(cmd.callValid());
  }

  @Test(timeout = 4000)
  public void test9_execute_catchesRuntimeException_andPrintsStackOnStderr() throws Throwable {
      final DummyThrowsRuntime cmd = new DummyThrowsRuntime();
      String err = captureStderr(new Runnable() { @Override public void run() { cmd.execute(); } });
      // باید استک‌تریس RuntimeException ثبت شده باشد
      assertTrue(err.contains("RuntimeException"));
      assertTrue(err.contains("boom"));
  }

  @Test(timeout = 4000)
  public void test10_execute_catchesError_andPrintsStackOnStderr() throws Throwable {
      final DummyThrowsError cmd = new DummyThrowsError();
      String err = captureStderr(new Runnable() { @Override public void run() { cmd.execute(); } });
      // باید استک‌تریس Error ثبت شده باشد
      assertTrue(err.contains("java.lang.Error"));
      assertTrue(err.contains("die"));
  }

  @Test(timeout = 4000)
  public void test11_message_knownKey_notNull() throws Throwable {
      // کلید عمومی‌تر تا وابستگی کمتری به متن دقیق داشته باشیم
      String s = irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.AbstractMailCommand.message("error");
      assertNotNull(s);
      assertTrue(s.length() > 0);
  }

  @Test(timeout = 4000)
  public void test12_setParameters_referenceIsUsedLater() throws Throwable {
      final DummyOkCmd cmd = new DummyOkCmd();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("x");
      cmd.setParameters(params);
      // بعد از set دوباره تغییر می‌دیم تا مطمئن بشیم رفرنس نگه داشته می‌شه
      params.add("y");

      String out = captureStdout(new Runnable() { @Override public void run() { cmd.execute(); } });
      assertTrue(out.contains("OK"));
      assertEquals(2, cmd.getLastParamCount());
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  /** زیرکلاسی که قبل از پرتاب استثنا روی stdout چاپ می‌کند */
  private static class DummyPrintThenThrow extends irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.AbstractMailCommand {
      @Override public void explain() {}
      @Override public String getCommandName() { return "dummy-ptt"; }
      @Override protected void handleExecute() {
          java.lang.System.out.print("BEFORE");
          throw new RuntimeException("x");
      }
  }



  @Test(timeout = 4000)
  public void test15_execute_printThenThrow_stdoutAndStderrSeparated() throws Throwable {
      final DummyPrintThenThrow cmd = new DummyPrintThenThrow();
      String[] oe = captureOutErr(new Runnable() { @Override public void run() { cmd.execute(); } });
      String out = oe[0];
      String err = oe[1];
      assertTrue(out.contains("BEFORE"));
      assertTrue(err.contains("RuntimeException"));
      assertTrue(err.contains("x"));
      // stdout نباید استک‌تریس داشته باشد
      assertFalse(out.contains("Exception"));
  }

  @Test(timeout = 4000)
  public void test16_message_emptyKey_throwsMissingResourceException() throws Throwable {
      try {
          AbstractMailCommand.message("");
          fail("Expecting MissingResourceException for empty key");
      } catch (MissingResourceException e) {
          verifyException("java.util.ResourceBundle", e);
      }
  }

  @Test(timeout = 4000)
  public void test17_execute_Error_goesToStderr_notStdout() throws Throwable {
      final DummyThrowsError cmd = new DummyThrowsError();
      String[] oe = captureOutErr(new Runnable() { @Override public void run() { cmd.execute(); } });
      String out = oe[0];
      String err = oe[1];
      assertTrue(err.contains("java.lang.Error"));
      assertTrue(err.contains("die"));
      assertFalse(out.toLowerCase().contains("error"));
  }

  @Test(timeout = 4000)
  public void test18_execute_twice_okCommand_printsOKEachTime() throws Throwable {
      final DummyOkCmd cmd = new DummyOkCmd();
      cmd.setParameters(new java.util.LinkedList<String>());
      // بار اول
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.execute(); } });
      // بار دوم
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.execute(); } });
      assertTrue(out1.contains("OK"));
      assertTrue(out2.contains("OK"));
      assertTrue(cmd.executed);
  }

  @Test(timeout = 4000)
  public void test19_dummyOk_getCommandName_constantAndTrimmed() throws Throwable {
      DummyOkCmd cmd = new DummyOkCmd();
      String name = cmd.getCommandName();
      assertEquals("dummy-ok", name);
      assertEquals(name, name.trim());
      assertFalse(name.contains(" "));
  }

}
