/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 21:52:32 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleListProvidersCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class ConsoleListProvidersCommand_ESTest extends ConsoleListProvidersCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست */
  private void delay() {
      try { Thread.sleep(500L); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      delay();
      ConsoleListProvidersCommand consoleListProvidersCommand0 = new ConsoleListProvidersCommand();
      consoleListProvidersCommand0.handleExecute();
      assertEquals("lp", consoleListProvidersCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      delay();
      ConsoleListProvidersCommand consoleListProvidersCommand0 = new ConsoleListProvidersCommand();
      consoleListProvidersCommand0.explain();
      assertEquals("lp", consoleListProvidersCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      delay();
      ConsoleListProvidersCommand consoleListProvidersCommand0 = new ConsoleListProvidersCommand();
      String string0 = consoleListProvidersCommand0.getCommandName();
      assertEquals("lp", string0);
  }

  /** helper: گرفتن خروجی System.out با Runnable ناشناس (Java 8) */
  private String captureStdout(final Runnable r) {
      PrintStream orig = System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      System.setOut(ps);
      try {
          r.run();
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test3_explain_printsUsageAndKey() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      // فرمت کلی: (lp) - <پیام i18n>
      assertTrue(out.contains("(lp)"));
      // اگر ResourceBundle موجود نباشد، خود کلید i18n چاپ می‌شود:
      assertTrue(out.contains("command.list.providers.explain"));
      assertEquals("lp", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test4_explain_multipleCalls_consistent() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out1.contains("(lp)"));
      assertTrue(out2.contains("(lp)"));
      assertTrue(out1.contains("command.list.providers.explain"));
      assertTrue(out2.contains("command.list.providers.explain"));
  }

  @Test(timeout = 4000)
  public void test5_handleExecute_capturesStdout_noCrashInTest() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String out = null;
      try {
          out = captureStdout(new Runnable() {
              @Override public void run() {
                  try { cmd.handleExecute(); } catch (Throwable t) { /* ممکن است محیط provider نداشته باشد */ }
              }
          });
      } catch (Throwable ignored) { }
      assertNotNull(out);
      // اگر Provider موجود باشد، انتظار خطوط "name - description" داریم:
      if (!out.trim().isEmpty()) {
          assertTrue("Expected provider lines to contain hyphen delimiter", out.contains(" - "));
      }
  }

  @Test(timeout = 4000)
  public void test6_handleExecute_twice_idempotent_commandNameStable() throws Throwable {
      delay();
      ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      try { cmd.handleExecute(); } catch (Throwable ignored) {}
      try { cmd.handleExecute(); } catch (Throwable ignored) {}
      assertEquals("lp", cmd.getCommandName());
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test7_explain_then_handleExecute_noCrash_andNameStable() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String outExplain = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String outExec = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      assertTrue(outExplain.contains("(lp)"));
      assertNotNull(outExec);
      assertEquals("lp", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test8_multipleInstances_independent() throws Throwable {
      delay();
      final ConsoleListProvidersCommand c1 = new ConsoleListProvidersCommand();
      final ConsoleListProvidersCommand c2 = new ConsoleListProvidersCommand();
      assertNotSame(c1, c2);
      captureStdout(new Runnable() { @Override public void run() { c1.explain(); }});
      captureStdout(new Runnable() { @Override public void run() { try { c2.handleExecute(); } catch (Throwable ignored) {} }});
      assertEquals("lp", c1.getCommandName());
      assertEquals("lp", c2.getCommandName());
  }

  @Test(timeout = 4000)
  public void test9_explain_outputDoesNotContainNullOrException() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String lower = out.toLowerCase();
      assertFalse(lower.contains("null"));
      assertFalse(lower.contains("exception"));
  }

  @Test(timeout = 4000)
  public void test10_getCommandName_nonBlankAndLowercase() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertTrue(name.trim().length() > 0);
      assertEquals("lp", name);
      assertTrue(name.equalsIgnoreCase("LP"));
  }

  @Test(timeout = 4000)
  public void test11_handleExecute_doesNotAlterCommandName() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String before = cmd.getCommandName();
      captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      String after = cmd.getCommandName();
      assertEquals(before, after);
      assertEquals("lp", after);
  }

  @Test(timeout = 4000)
  public void test12_handleExecute_outputLinesHaveHyphenWhenNotEmpty() throws Throwable {
      delay();
      final ConsoleListProvidersCommand cmd = new ConsoleListProvidersCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { try { cmd.handleExecute(); } catch (Throwable ignored) {} }});
      if (!out.trim().isEmpty()) {
          String[] lines = out.split("\\r?\\n");
          for (String line : lines) {
              if (!line.trim().isEmpty()) {
                  assertTrue("Each provider line should contain ' - '", line.contains(" - "));
              }
          }
      }
  }
}
