/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 21:10:13 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ChangeFolderConsoleCommand;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleCommandManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class ConsoleCommandManager_ESTest extends ConsoleCommandManager_ESTest_scaffolding {

  // --- Per-test delay: 0.5 second (500 ms) to slow tests but stay well under @Test(timeout=4000)
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsoleCommandManager.run("&Y2a");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConsoleCommandManager consoleCommandManager0 = ConsoleCommandManager.singleton();
      consoleCommandManager0.runCommand("connect to outlook accounts");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsoleCommandManager consoleCommandManager0 = ConsoleCommandManager.singleton();
      consoleCommandManager0.runCommand("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChangeFolderConsoleCommand changeFolderConsoleCommand0 = new ChangeFolderConsoleCommand();
      ConsoleCommandManager consoleCommandManager0 = ConsoleCommandManager.singleton();
      consoleCommandManager0.handleAddCommand(changeFolderConsoleCommand0);
      assertEquals("cd", changeFolderConsoleCommand0.getCommandName());
  }

  /** helper: capture System.out و System.err در حین اجرای یک Runnable (بدون لامبدا) */
  private static class OutErr {
      final String out, err;
      OutErr(String o, String e) { this.out = o; this.err = e; }
  }
  private OutErr captureOutErr(final Runnable r) {
      PrintStream origOut = System.out;
      PrintStream origErr = System.err;
      ByteArrayOutputStream bout = new ByteArrayOutputStream();
      ByteArrayOutputStream berr = new ByteArrayOutputStream();
      PrintStream pout = new PrintStream(bout);
      PrintStream perr = new PrintStream(berr);
      System.setOut(pout);
      System.setErr(perr);
      try {
          r.run();
      } finally {
          System.setOut(origOut);
          System.setErr(origErr);
          pout.flush(); perr.flush();
          pout.close(); perr.close();
      }
      return new OutErr(new String(bout.toByteArray(), StandardCharsets.UTF_8),
                        new String(berr.toByteArray(), StandardCharsets.UTF_8));
  }

  @Test(timeout = 4000)
  public void test4_singleton_sameInstance() throws Throwable {
      ConsoleCommandManager a = ConsoleCommandManager.singleton();
      ConsoleCommandManager b = ConsoleCommandManager.singleton();
      assertSame(a, b);
  }

  @Test(timeout = 4000)
  public void test5_runCommand_blankString_noEffect_noThrow() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand(""); // باید هیچ کاری نکند و exception ندهد
          }
      });
      assertTrue(oe.out.trim().isEmpty());
      assertTrue(oe.err.trim().isEmpty());
  }

  @Test(timeout = 4000)
  public void test6_runCommand_whitespaceOnly_noEffect_noThrow() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand("   "); // فضای خالی
          }
      });
      assertTrue(oe.out.trim().isEmpty());
  }

  @Test(timeout = 4000)
  public void test7_runCommand_unknownCommand_noThrow_errorGetsLogged() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand("unknownCmd arg1 arg2");
          }
      });
      assertNotNull(oe.err); // لاگ خطا روی stderr
  }

  @Test(timeout = 4000)
  public void test8_runCommand_cdWithOneParam_noThrow_errorIsCaughtInside() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand("cd Inbox");
          }
      });
      assertNotNull(oe.err); // هر خطایی هندل می‌شود
  }

  @Test(timeout = 4000)
  public void test9_runCommand_cdWithMultipleParams_noThrow() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand("cd Inbox ExtraParam");
          }
      });
      assertNotNull(oe.err);
  }

  @Test(timeout = 4000)
  public void test10_staticRun_delegates_noThrow() throws Throwable {
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              ConsoleCommandManager.run("cd Inbox");
          }
      });
      assertNotNull(oe.err);
  }

  // ==================== Added extra tests (with 0.5s delay via @Before) ====================

  @Test(timeout = 4000)
  public void test11_runCommand_caseSensitive_unknownUppercaseCD() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand("CD Inbox"); // اگر case-sensitive باشد ناشناخته است
          }
      });
      assertNotNull(oe.err); // لاگ می‌شود، نباید استثناء به بیرون بیاید
  }

  @Test(timeout = 4000)
  public void test12_runCommand_withTabsAndSpaces_noThrow() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand("cd\t  Sent\tItems");
          }
      });
      assertNotNull(oe.err); // هرگونه خطا لاگ می‌شود
  }

  @Test(timeout = 4000)
  public void test13_handleAddCommand_twice_sameCommandName_noThrow() throws Throwable {
      ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      ChangeFolderConsoleCommand c1 = new ChangeFolderConsoleCommand();
      ChangeFolderConsoleCommand c2 = new ChangeFolderConsoleCommand();
      // اضافه‌کردن چندباره نباید باعث کرش شود (بسته به پیاده‌سازی ممکن است override شود)
      mgr.handleAddCommand(c1);
      mgr.handleAddCommand(c2);
      assertEquals("cd", c1.getCommandName());
      assertEquals("cd", c2.getCommandName());
  }

  @Test(timeout = 4000)
  public void test14_run_multipleCommands_sequence_noThrow() throws Throwable {
      final ConsoleCommandManager mgr = ConsoleCommandManager.singleton();
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              mgr.runCommand("cd Inbox");
              mgr.runCommand("unknown");
              mgr.runCommand("cd Sent");
          }
      });
      // باید اجرا شود و فقط لاگ خطاها روی stderr بیاید
      assertNotNull(oe.err);
  }

  @Test(timeout = 4000)
  public void test15_singleton_multithread_sameInstance() throws Throwable {
      final ConsoleCommandManager[] arr = new ConsoleCommandManager[2];
      Thread t1 = new Thread(new Runnable() { @Override public void run() { arr[0] = ConsoleCommandManager.singleton(); }});
      Thread t2 = new Thread(new Runnable() { @Override public void run() { arr[1] = ConsoleCommandManager.singleton(); }});
      t1.start(); t2.start();
      t1.join();  t2.join();
      assertSame(arr[0], arr[1]);
  }

  @Test(timeout = 4000)
  public void test16_staticRun_emptyString_noOutputNoThrow() throws Throwable {
      OutErr oe = captureOutErr(new Runnable() {
          @Override public void run() {
              ConsoleCommandManager.run("");
          }
      });
      assertTrue(oe.out.trim().isEmpty());
      assertTrue(oe.err.trim().isEmpty());
  }
}
