/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 23:17:37 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.exception;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.exception.DBException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class DBException_ESTest extends DBException_ESTest_scaffolding {

  // تاخیر نیم‌ثانیه‌ای قبل از اجرای هر تست (با timeout=4000 سازگار است)
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test0() throws Throwable {
      MockException mockException0 = new MockException();
      DBException dBException0 = new DBException("", mockException0);
      assertNotNull(dBException0);
  }

  @Test(timeout = 4000)
  public void test1_messageAndCause_areSet() throws Throwable {
      Exception cause = new Exception("boom");
      DBException ex = new DBException("db fail", cause);

      assertEquals("db fail", ex.getMessage());
      assertSame(cause, ex.getCause());

      String s = ex.toString();
      assertTrue(s.contains("DBException"));
      assertTrue(s.contains("db fail"));
  }

  @Test(timeout = 4000)
  public void test2_nullCause_allowed() throws Throwable {
      DBException ex = new DBException("x", (Exception) null);
      assertEquals("x", ex.getMessage());
      assertNull(ex.getCause());
  }

  @Test(timeout = 4000)
  public void test3_nullMessage_withCause() throws Throwable {
      Exception cause = new Exception("root");
      DBException ex = new DBException((String) null, cause);

      assertNull(ex.getMessage());
      assertSame(cause, ex.getCause());

      String s = ex.toString();
      assertTrue(s.contains("DBException"));
  }

  @Test(timeout = 4000)
  public void test4_fillInStackTrace_populates() throws Throwable {
      DBException ex = new DBException("m", new Exception("c"));
      ex.fillInStackTrace();
      StackTraceElement[] st = ex.getStackTrace();

      assertNotNull(st);
      assertTrue(st.length > 0);
  }

  @Test(timeout = 4000)
  public void test5_equals_basicObjectSemantics() throws Throwable {
      DBException a = new DBException("m", new Exception("c"));
      DBException b = new DBException("m", new Exception("c"));

      assertTrue(a.equals(a));       // بازتابی
      assertFalse(a.equals(b));      // دو شیء متمایز
      assertFalse(a.equals(null));   // نابرابری با null
  }

  @Test(timeout = 4000)
  public void test6_getLocalizedMessage_notNull_whenMessageProvided() throws Throwable {
      DBException ex = new DBException("oops", new Exception());
      assertNotNull(ex.getLocalizedMessage()); // معمولاً همان getMessage
  }

  // =================== تست‌های افزوده‌شده ===================

  @Test(timeout = 4000)
  public void test7_nullMessage_and_nullCause_allowed() throws Throwable {
      DBException ex = new DBException((String) null, (Exception) null);
      assertNull(ex.getMessage());
      assertNull(ex.getCause());
      assertTrue(ex.toString().contains("DBException"));
  }

  @Test(timeout = 4000)
  public void test8_addSuppressed_single() throws Throwable {
      DBException ex = new DBException("m", new Exception("c"));
      ex.addSuppressed(new RuntimeException("s"));
      Throwable[] sup = ex.getSuppressed();
      assertNotNull(sup);
      assertEquals(1, sup.length);
      assertEquals("s", sup[0].getMessage());
  }

  @Test(timeout = 4000)
  public void test9_causeChaining_preserved() throws Throwable {
      Exception inner = new Exception("inner");
      Exception outer = new Exception("outer", inner);
      DBException ex = new DBException("top", outer);

      assertSame(outer, ex.getCause());
      assertSame(inner, ex.getCause().getCause());
  }

  @Test(timeout = 4000)
  public void test10_emptyMessage_preserved() throws Throwable {
      DBException ex = new DBException("", new Exception("c"));
      assertEquals("", ex.getMessage());
      assertTrue(ex.toString().contains("DBException"));
  }

  @Test(timeout = 4000)
  public void test11_hashCode_isCallable() throws Throwable {
      DBException ex = new DBException("m", new Exception("c"));
      int h = ex.hashCode(); // فقط نباید خطا دهد
      // هر intای پذیرفتنی است؛ این بررسی فقط برای فراخوانی بدون استثناء است
      assertTrue(h == ex.hashCode()); // پایداری ضمنی در طول اجرا
  }

  @Test(timeout = 4000)
  public void test12_getLocalizedMessage_nullWhenMessageNull() throws Throwable {
      DBException ex = new DBException((String) null, new Exception("c"));
      // در Throwable، وقتی message=null باشد، localizedMessage هم معمولاً null است
      assertNull(ex.getLocalizedMessage());
  }
}
