/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 01 11:02:15 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model;

import org.junit.Test;
import static org.junit.Assert.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.EmailMessage;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.core.model.Tag;
import java.util.LinkedHashSet;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Tag_ESTest extends Tag_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tag tag0 = new Tag("v");
      assertEquals("v", tag0.getName());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Tag tag0 = new Tag();
      String string0 = tag0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Tag tag0 = new Tag();
      LinkedHashSet<EmailMessage> linkedHashSet0 = new LinkedHashSet<EmailMessage>();
      EmailMessage emailMessage0 = new EmailMessage((String) null, "i6g~;M;V\"&Q$=~J_L", "&~I", "&~I");
      linkedHashSet0.add(emailMessage0);
      tag0.setMessages(linkedHashSet0);
      Set<EmailMessage> set0 = tag0.getMessages();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Tag tag0 = new Tag();
      String string0 = tag0.getId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Tag tag0 = new Tag("7", "");
      assertEquals("", tag0.getName());
      
      tag0.setName("irisdeltaj.simplelucenetag.br.unb.cic.iris.core.model.FolderContent");
      tag0.getName();
      assertEquals("7", tag0.getId());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Tag tag0 = new Tag("7", "");
      assertEquals("7", tag0.getId());
      
      tag0.setId("");
      tag0.getId();
      assertEquals("", tag0.getName());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Tag tag0 = new Tag("7", "");
      String string0 = tag0.getName();
      assertEquals("", string0);
      assertEquals("7", tag0.getId());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Tag tag0 = new Tag("7", "");
      String string0 = tag0.getId();
      assertEquals("7", string0);
      assertEquals("", tag0.getName());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Tag tag0 = new Tag("7", "");
      LinkedHashSet<EmailMessage> linkedHashSet0 = new LinkedHashSet<EmailMessage>();
      tag0.setMessages(linkedHashSet0);
      tag0.getMessages();
      assertEquals("7", tag0.getId());
      assertEquals("", tag0.getName());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Tag tag0 = new Tag();
      Set<EmailMessage> set0 = tag0.getMessages();
      assertNull(set0);
  }
  @Test(timeout = 4000)
  public void test10() throws Throwable {
      Tag tag = new Tag("news");
      assertEquals("news", tag.getName());
      assertNull(tag.getId());
      // در سازنده‌ی تک‌پارامتری مجموعهٔ پیام‌ها مقداردهی نمی‌شود
      assertNull(tag.getMessages());
  }

  @Test(timeout = 4000)
  public void test11() throws Throwable {
      Tag tag = new Tag();
      // صراحتاً null بدهیم و مطمئن شویم همان را برمی‌گرداند
      tag.setMessages((Set<EmailMessage>) null);
      assertNull(tag.getMessages());
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
      Tag tag = new Tag();
      assertNull(tag.getId());

      tag.setId("42");
      assertEquals("42", tag.getId());

      tag.setId(null);
      assertNull(tag.getId());
  }

  @Test(timeout = 4000)
  public void test13() throws Throwable {
      Tag tag = new Tag();
      String unicodeName = "برچسب‌آزمایشی";
      tag.setName(unicodeName);
      assertEquals(unicodeName, tag.getName());
  }

  @Test(timeout = 4000)
  public void test14() throws Throwable {
      Tag tag = new Tag();
      LinkedHashSet<EmailMessage> set = new LinkedHashSet<EmailMessage>();
      tag.setMessages(set);
      assertSame(set, tag.getMessages());
      assertTrue(tag.getMessages().isEmpty());

      // افزودن پس از setMessages باید در خروجی منعکس شود (ارجاع نگه داشته می‌شود)
      EmailMessage m = new EmailMessage((String) null, "subj", "from@ex.com", "to@ex.com");
      set.add(m);
      assertEquals(1, tag.getMessages().size());
      assertTrue(tag.getMessages().contains(m));
  }

  @Test(timeout = 4000)
  public void test15() throws Throwable {
      Tag tag = new Tag();
      LinkedHashSet<EmailMessage> first = new LinkedHashSet<EmailMessage>();
      LinkedHashSet<EmailMessage> second = new LinkedHashSet<EmailMessage>();

      EmailMessage m1 = new EmailMessage((String) null, "s1", "a@ex.com", "b@ex.com");
      EmailMessage m2 = new EmailMessage((String) null, "s2", "c@ex.com", "d@ex.com");

      first.add(m1);
      second.add(m2);

      tag.setMessages(first);
      assertSame(first, tag.getMessages());
      assertTrue(tag.getMessages().contains(m1));
      assertFalse(tag.getMessages().contains(m2));

      // جایگزینی کامل مجموعه
      tag.setMessages(second);
      assertSame(second, tag.getMessages());
      assertFalse(tag.getMessages().contains(m1));
      assertTrue(tag.getMessages().contains(m2));
  }

  @Test(timeout = 4000)
  public void test16() throws Throwable {
      Tag tag = new Tag();
      tag.setId("id-1");
      tag.setName("n1");

      LinkedHashSet<EmailMessage> msgs = new LinkedHashSet<EmailMessage>();
      tag.setMessages(msgs);

      // تغییرات بعدی باید در گترها دیده شوند
      tag.setName("n2");
      assertEquals("id-1", tag.getId());
      assertEquals("n2", tag.getName());
      assertSame(msgs, tag.getMessages());
  }

}
