/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 20:41:05 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import org.junit.Before;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.AddressBookConsoleCommand;
import java.security.InvalidParameterException;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AddressBookConsoleCommand_ESTest extends AddressBookConsoleCommand_ESTest_scaffolding {
	@Before
	public void halfSecondDelay() throws Exception {
	    try { Thread.sleep(500L); } catch (InterruptedException ignored) { }
	}

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("add");
      linkedList0.add("add");
      linkedList0.add("add");
      linkedList0.add("D(\"&$\"BpzX>bmo");
      addressBookConsoleCommand0.setParameters(linkedList0);
      addressBookConsoleCommand0.execute();
      assertEquals("ab", addressBookConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("delete");
      linkedList0.add("delete");
      linkedList0.add("D(\"&$\"BpzX>bmo");
      addressBookConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      addressBookConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("add");
      linkedList0.add("add");
      linkedList0.add("add");
      addressBookConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // invalid email
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("delete");
      linkedList0.add("delete");
      addressBookConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         //  is an invalid command
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("add");
      addressBookConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("list");
      addressBookConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("delete");
      addressBookConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      
      } catch(InvalidParameterException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      addressBookConsoleCommand0.explain();
      assertEquals("ab", addressBookConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      String string0 = addressBookConsoleCommand0.getCommandName();
      assertEquals("ab", string0);
  }
  @Test(timeout = 4000)
  public void test12_add_withValidEmail_invokesFacade_throwsNoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("john");
      params.add("john.doe@example.com");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test13_add_withUppercaseEmail_validPattern_thenNoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("UserName");
      params.add("User@Example.COM");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test14_add_withTwoArgs_onlyName_InvalidParameterException() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("onlyName");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: InvalidParameterException");
      } catch (InvalidParameterException e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test15_add_withInvalidEmail_throwsEmailUncheckedException() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("bad");
      params.add("user@com"); // دامنه بدون TLD معتبر
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: RuntimeException");
      } catch (RuntimeException e) { // EmailUncheckedException
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test16_list_withExtraArg_stillCallsFacade_NoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add("ignored");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test17_unknownSubcommand_throwsEmailExceptionWithMessage() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("foo");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          assertTrue(e.getMessage().contains("foo is an invalid command"));
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test18_delete_withValidArgs_invokesFacade_NoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("delete");
      params.add("john");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test19_execute_wrapsUncheckedExceptions_doesNotThrow() throws Throwable {
      // سه آرگومان اما ایمیل نامعتبر => EmailUncheckedException داخل execute چاپ می‌شود و خطا پرتاب نمی‌شود
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("n1");
      params.add("bad-email");
      cmd.setParameters(params);
      cmd.execute(); // نباید استثنای بیرونی بده
      assertEquals("ab", cmd.getCommandName());
  }
  @Test(timeout = 4000)
  public void test20_unknownCommand_invalid() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("help");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          assertTrue(e.getMessage().contains("invalid command"));
          assertTrue(e.getMessage().contains("help"));
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test21_setParametersNull_thenHandle_NPE() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      cmd.setParameters((java.util.LinkedList<String>) null);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test22_add_withTrailingSpace_inCommand_invalid() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add ");                // فاصلهٔ انتهایی
      params.add("name");
      params.add("name@example.com");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          assertTrue(e.getMessage().contains("invalid command"));
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test23_add_withEmptyEmail_runtimeInvalidEmail() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("someone");
      params.add(""); // ایمیل خالی
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: RuntimeException");
      } catch (RuntimeException e) {
          // EmailUncheckedException به صورت RuntimeException
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test24_delete_withExtraArgs_invalidParameter() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("delete");
      params.add("john");
      params.add("extra");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: InvalidParameterException");
      } catch (InvalidParameterException e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test25_list_withManyArgs_noClassDefFound() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add("a");
      params.add("b");
      params.add("c");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test26_execute_handlesInvalidParameter_withoutThrow() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("delete"); // آرگومان کم؛ handleExecute معمولاً InvalidParameterException می‌دهد
      cmd.setParameters(params);
      // execute باید استثناهای unchecked را بگیرد و نریزد بیرون
      cmd.execute();
      assertEquals("ab", cmd.getCommandName());
  }


}
