/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 20:41:05 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.AddressBookConsoleCommand;
import java.security.InvalidParameterException;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class AddressBookConsoleCommand_ESTest extends AddressBookConsoleCommand_ESTest_scaffolding {

  // --- Per-test delay: 0.5 second (500 ms) ---
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("add");
      linkedList0.add("add");
      linkedList0.add("add");
      linkedList0.add("D(\"&$\"BpzX>bm\u007Fo");
      addressBookConsoleCommand0.setParameters(linkedList0);
      addressBookConsoleCommand0.execute();
      assertEquals("ab", addressBookConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("delete");
      linkedList0.add("delete");
      linkedList0.add("D(\"&$\"BpzX>bm\u007Fo");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      } catch(InvalidParameterException e) {
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: NullPointerException");
      } catch(NullPointerException e) {
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: IndexOutOfBoundsException");
      } catch(IndexOutOfBoundsException e) {
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("add");
      linkedList0.add("add");
      linkedList0.add("add");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: RuntimeException");
      } catch(RuntimeException e) {
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("delete");
      linkedList0.add("delete");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: Exception");
      } catch(Exception e) {
         assertTrue(e.getMessage().contains(" is an invalid command"));
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("add");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      } catch(InvalidParameterException e) {
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("list");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.addLast("delete");
      addressBookConsoleCommand0.setParameters(linkedList0);
      try {
        addressBookConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");
      } catch(InvalidParameterException e) {
         verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      addressBookConsoleCommand0.explain();
      assertEquals("ab", addressBookConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AddressBookConsoleCommand addressBookConsoleCommand0 = new AddressBookConsoleCommand();
      String string0 = addressBookConsoleCommand0.getCommandName();
      assertEquals("ab", string0);
  }

  @Test(timeout = 4000)
  public void test12_add_withValidEmail_invokesFacade_throwsNoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("john");
      params.add("john.doe@example.com");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test13_add_withUppercaseEmail_validPattern_thenNoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("UserName");
      params.add("User@Example.COM");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test14_add_withTwoArgs_onlyName_InvalidParameterException() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("onlyName");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: InvalidParameterException");
      } catch (InvalidParameterException e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test15_add_withInvalidEmail_throwsEmailUncheckedException() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("bad");
      params.add("user@com");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: RuntimeException");
      } catch (RuntimeException e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test16_list_withExtraArg_stillCallsFacade_NoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("list");
      params.add("ignored");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test17_unknownSubcommand_throwsEmailExceptionWithMessage() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("foo");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          assertTrue(e.getMessage().contains("foo is an invalid command"));
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test18_delete_withValidArgs_invokesFacade_NoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("delete");
      params.add("john");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test19_execute_wrapsUncheckedExceptions_doesNotThrow() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("add");
      params.add("n1");
      params.add("bad-email");
      cmd.setParameters(params);
      cmd.execute();
      assertEquals("ab", cmd.getCommandName());
  }

  // ==================== Added extra tests ====================

  @Test(timeout = 4000)
  public void test20_add_nameWithSpace_validEmail_NoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      LinkedList<String> params = new LinkedList<>();
      params.add("add");
      params.add("John Doe");
      params.add("john.doe+test@example.co.uk");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test21_add_tooManyArgs_InvalidParameterException() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      LinkedList<String> params = new LinkedList<>();
      params.add("add");
      params.add("john");
      params.add("john@example.com");
      params.add("extra");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: InvalidParameterException");
      } catch (InvalidParameterException e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test22_delete_blankName_NoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      LinkedList<String> params = new LinkedList<>();
      params.add("delete");
      params.add("");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test23_list_mixedCase_isInvalidCommand_Exception() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      LinkedList<String> params = new LinkedList<>();
      params.add("LiSt");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          assertTrue(e.getMessage().contains("LiSt is an invalid command"));
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test24_add_emailWithPlusAndDash_valid_NoClassDefFoundError() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      LinkedList<String> params = new LinkedList<>();
      params.add("add");
      params.add("u");
      params.add("first-last+alias@sub.example-domain.org");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test25_delete_uppercaseCommand_invalidCommand_Exception() throws Throwable {
      AddressBookConsoleCommand cmd = new AddressBookConsoleCommand();
      LinkedList<String> params = new LinkedList<>();
      params.add("DELETE");
      params.add("john");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          assertTrue(e.getMessage().contains("DELETE is an invalid command"));
          verifyException("irisdeltaj.simplerelationaladdressbook.br.unb.cic.iris.command.console.AddressBookConsoleCommand", e);
      }
  }

}
