/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 01 12:07:18 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleSendSecuritySignEncryptMessageCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ConsoleSendSecuritySignEncryptMessageCommand_ESTest extends ConsoleSendSecuritySignEncryptMessageCommand_ESTest_scaffolding {

  /** تأخیر نیم‌ثانیه‌ای پیش از اجرای هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsoleSendSecuritySignEncryptMessageCommand consoleSendSecuritySignEncryptMessageCommand0 = new ConsoleSendSecuritySignEncryptMessageCommand();
      // Undeclared exception!
      try { 
        consoleSendSecuritySignEncryptMessageCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleSendSecuritySignEncryptMessageCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConsoleSendSecuritySignEncryptMessageCommand consoleSendSecuritySignEncryptMessageCommand0 = new ConsoleSendSecuritySignEncryptMessageCommand();
      consoleSendSecuritySignEncryptMessageCommand0.explain();
      assertEquals("send_sign_encrypt", consoleSendSecuritySignEncryptMessageCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsoleSendSecuritySignEncryptMessageCommand consoleSendSecuritySignEncryptMessageCommand0 = new ConsoleSendSecuritySignEncryptMessageCommand();
      String string0 = consoleSendSecuritySignEncryptMessageCommand0.getCommandName();
      assertEquals("send_sign_encrypt", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      // explain باید نام دستور و کلید پیام را چاپ کند
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream old = System.out;
      try {
          System.setOut(ps);
          ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
          cmd.explain();
      } finally {
          System.setOut(old);
      }
      String out = baos.toString();
      assertTrue(out.contains("(send_sign_encrypt)"));
      assertTrue(out.contains("command.sendse.explain"));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // ورودی کامل فراهم می‌کنیم؛ به خاطر وابستگی‌ها انتظار NoClassDefFoundError داریم
      String nl = System.getProperty("line.separator");
      String input =
              "to@example.com" + nl +   // to
              "cc@example.com" + nl +   // cc
              "bcc@example.com" + nl +  // bcc
              "subject" + nl +          // subject
              "content";                // content
      java.io.InputStream oldIn = System.in;
      try {
          System.setIn(new java.io.ByteArrayInputStream(input.getBytes("UTF-8")));
          ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
          try {
              cmd.handleExecute();
              fail("Expecting exception: NoClassDefFoundError");
          } catch (NoClassDefFoundError e) {
              verifyException("irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleSendSecuritySignEncryptMessageCommand", e);
          }
      } finally {
          System.setIn(oldIn);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      // حتی با ورودی خالی نیز قبل از ساخت کامل پیام به SystemFacade می‌رسد → NoClassDefFoundError
      java.io.InputStream oldIn = System.in;
      try {
          System.setIn(new java.io.ByteArrayInputStream(new byte[0]));
          ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
          try {
              cmd.handleExecute();
              fail("Expecting exception: NoClassDefFoundError");
          } catch (NoClassDefFoundError e) {
              verifyException("irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleSendSecuritySignEncryptMessageCommand", e);
          }
      } finally {
          System.setIn(oldIn);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // متد private static askQuestion باید کلید پیام و دونقطه چاپ کند
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream old = System.out;
      try {
          System.setOut(ps);
          java.lang.reflect.Method m = ConsoleSendSecuritySignEncryptMessageCommand.class
                  .getDeclaredMethod("askQuestion", String.class);
          m.setAccessible(true);
          m.invoke(null, "command.send.label.to");
      } finally {
          System.setOut(old);
      }
      String out = baos.toString();
      assertTrue(out.contains("command.send.label.to"));
      assertTrue(out.contains(":"));
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // متد private static read باید مقدار ورودی را برگرداند و پرامپت را چاپ کند
      String nl = System.getProperty("line.separator");
      String input = "value-line" + nl;
      java.util.Scanner sc = new java.util.Scanner(new java.io.ByteArrayInputStream(input.getBytes("UTF-8")));

      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream old = System.out;
      try {
          System.setOut(ps);
          java.lang.reflect.Method m = ConsoleSendSecuritySignEncryptMessageCommand.class
                  .getDeclaredMethod("read", java.util.Scanner.class, String.class);
          m.setAccessible(true);
          Object ret = m.invoke(null, sc, "command.send.label.subject");
          assertEquals("value-line", ret);
      } finally {
          System.setOut(old);
      }
      String out = baos.toString();
      assertTrue(out.contains("command.send.label.subject"));
      assertTrue(out.contains(":"));
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      // ثابت کلاس باید با خروجی getCommandName برابر باشد
      ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
      assertEquals(ConsoleSendSecuritySignEncryptMessageCommand.COMMAND_SEND, cmd.getCommandName());
  }

  /** Helper گرفتن stdout با Runnable ناشناس */
  private String captureStdout(final Runnable r) {
      java.io.PrintStream orig = System.out;
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      System.setOut(ps);
      try {
          r.run();
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), java.nio.charset.StandardCharsets.UTF_8);
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  @Test(timeout = 4000)
  public void test9_explain_multipleCalls_consistentOutput() throws Throwable {
      final ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      assertEquals(out1.trim(), out2.trim());
      assertTrue(out1.contains("(send_sign_encrypt)"));
  }

  @Test(timeout = 4000)
  public void test10_getCommandName_trimmed_lowercase_andConstant() throws Throwable {
      ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
      String name = cmd.getCommandName();
      assertEquals("send_sign_encrypt", name);
      assertEquals(name, name.trim());
      assertEquals(ConsoleSendSecuritySignEncryptMessageCommand.COMMAND_SEND, name);
  }

  @Test(timeout = 4000)
  public void test11_read_withEmptyLine_returnsEmptyString_andPrintsPrompt() throws Throwable {
      String nl = System.getProperty("line.separator");
      String input = nl; // خط خالی
      java.util.Scanner sc = new java.util.Scanner(new java.io.ByteArrayInputStream(input.getBytes("UTF-8")));

      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream old = System.out;
      try {
          System.setOut(ps);
          java.lang.reflect.Method m = ConsoleSendSecuritySignEncryptMessageCommand.class
                  .getDeclaredMethod("read", java.util.Scanner.class, String.class);
          m.setAccessible(true);
          Object ret = m.invoke(null, sc, "command.send.label.cc");
          assertEquals("", ret);
      } finally {
          System.setOut(old);
      }
      String out = baos.toString();
      assertTrue(out.contains("command.send.label.cc"));
      assertTrue(out.contains(":"));
  }

  @Test(timeout = 4000)
  public void test12_askQuestion_printsKey_followedByColonSpace() throws Throwable {
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream old = System.out;
      try {
          System.setOut(ps);
          java.lang.reflect.Method m = ConsoleSendSecuritySignEncryptMessageCommand.class
                  .getDeclaredMethod("askQuestion", String.class);
          m.setAccessible(true);
          m.invoke(null, "command.send.label.bcc");
      } finally {
          System.setOut(old);
      }
      String out = baos.toString();
      assertTrue(out.contains("command.send.label.bcc"));
      assertTrue("Expect ': ' after key", out.contains(": "));
  }

  @Test(timeout = 4000)
  public void test13_handleExecute_partialInput_printsNextPrompt_thenThrows() throws Throwable {
      // فقط مقدار to را می‌دهیم؛ انتظار داریم پرامپت cc هم قبل از Exception چاپ شود
      String nl = System.getProperty("line.separator");
      String input = "to@ex.com" + nl; // فقط to
      java.io.InputStream oldIn = System.in;
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream oldOut = System.out;

      try {
          System.setIn(new java.io.ByteArrayInputStream(input.getBytes("UTF-8")));
          System.setOut(ps);
          ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
          try {
              cmd.handleExecute();
              // بسته به رفتار Scanner ممکن است به NoSuchElementException برسیم؛ لازم نیست fail کنیم
          } catch (Throwable ignored) { }
      } finally {
          System.setIn(oldIn);
          System.setOut(oldOut);
      }

      String out = baos.toString();
      assertTrue(out.contains("command.send.label.to"));
      assertTrue("cc prompt should be printed before read fails", out.contains("command.send.label.cc"));
  }

  @Test(timeout = 4000)
  public void test14_handleExecute_fullInput_printsAllPrompts_thenFailsInside() throws Throwable {
      String nl = System.getProperty("line.separator");
      String input =
              "to@example.com" + nl +
              "cc@example.com" + nl +
              "bcc@example.com" + nl +
              "subject" + nl +
              "content";
      java.io.InputStream oldIn = System.in;
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream oldOut = System.out;

      try {
          System.setIn(new java.io.ByteArrayInputStream(input.getBytes("UTF-8")));
          System.setOut(ps);
          ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
          try {
              cmd.handleExecute();
              fail("Expecting NoClassDefFoundError due to mail classes");
          } catch (Throwable ignored) { /* NoClassDefFoundError یا مشابه */ }
      } finally {
          System.setIn(oldIn);
          System.setOut(oldOut);
      }

      String out = baos.toString();
      assertTrue(out.contains("command.send.label.to"));
      assertTrue(out.contains("command.send.label.cc"));
      assertTrue(out.contains("command.send.label.bcc"));
      assertTrue(out.contains("command.send.label.subject"));
      assertTrue(out.contains("command.send.label.content"));
  }

  @Test(timeout = 4000)
  public void test15_explain_containsSeparatorDash() throws Throwable {
      final ConsoleSendSecuritySignEncryptMessageCommand cmd = new ConsoleSendSecuritySignEncryptMessageCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); }});
      // الگوی مشترک: "(command) - <message>"
      assertTrue(out.contains("(send_sign_encrypt)"));
      assertTrue("Explain should contain separator ' - '", out.contains(" - "));
  }

}
