/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 21:01:49 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.TagConsoleCommand;
import java.security.InvalidParameterException;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class TagConsoleCommand_ESTest extends TagConsoleCommand_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای برای هر تست */
  private void delay() {
      try { Thread.sleep(500L); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
  }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      linkedList0.add("add");
      linkedList0.add("");
      linkedList0.add("W]8PXzRRn\"q");
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");

      } catch(InvalidParameterException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("list");
      linkedList0.add("list");
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("");
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      linkedList0.add("add");
      linkedList0.add("add");
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NumberFormatException");

      } catch(NumberFormatException e) {
         //
         // For input string: \"add\"
         //
         verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: IndexOutOfBoundsException");

      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      linkedList0.add("3");
      linkedList0.add("3");
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("list");
      linkedList0.add("list");
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/EmailDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("lIs");
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: Exception");

      } catch(Exception e) {
         //
         // lIs is an invalid command
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("list");
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");

      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelationaltag/br/unb/cic/iris/persistence/relational/TagDAO
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      tagConsoleCommand0.setParameters(linkedList0);
      linkedList0.add("add");
      // Undeclared exception!
      try {
        tagConsoleCommand0.handleExecute();
        fail("Expecting exception: InvalidParameterException");

      } catch(InvalidParameterException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      String string0 = tagConsoleCommand0.getCommandName();
      assertEquals("tag", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      delay();
      TagConsoleCommand tagConsoleCommand0 = new TagConsoleCommand();
      tagConsoleCommand0.explain();
      assertEquals("tag", tagConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test11() throws Throwable {
      delay();
      // parameters = null  → NPE
      TagConsoleCommand cmd = new TagConsoleCommand();
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
      delay();
      // دستور نامعتبر با فاصله‌ی انتهایی → به شاخه default می‌رود و EmailException پرتاب می‌شود
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add "); // توجه: space انتهایی
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          // "add " is an invalid command
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test13() throws Throwable {
      delay();
      // add با فقط یک آرگومانِ عددی → InvalidParameterException
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("1");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: InvalidParameterException");
      } catch (InvalidParameterException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test14() throws Throwable {
      delay();
      // add با index = 0  → currentMessages احتمالا null است و NPE می‌دهد
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("0");
      params.add("tag1,tag2");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test15() throws Throwable {
      delay();
      // list با سه آرگومان → listAll صدا می‌خورد و به TagManager وابسته است → NoClassDefFoundError
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("list");
      params.add("myTag");
      params.add("extra");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          // TagDAO/TagManager در محیط تست وجود ندارد
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test16() throws Throwable {
      delay();
      // list با آرگومان خالی → باز هم به TagManager می‌رسد → NoClassDefFoundError
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("list");
      params.add("");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.core.TagManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test17() throws Throwable {
      delay();
      // add با idx غیرعددی خالی → NumberFormatException
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("");
      params.add("t1");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NumberFormatException");
      } catch (NumberFormatException e) {
          verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test18() throws Throwable {
      delay();
      // add با idx منفی → قبل از هر چیز به currentMessages (که null است) دسترسی می‌زند → NPE
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("-5");
      params.add("alpha,beta");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NullPointerException");
      } catch (NullPointerException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  // ======================= تست‌های اضافه‌شده =======================

  @Test(timeout = 4000)
  public void test19_explain_capturesOutput_ifAny() throws Throwable {
      delay();
      final TagConsoleCommand cmd = new TagConsoleCommand();
      // گرفتن خروجی، ولی assert سخت‌گیرانه روی i18n انجام نمی‌دهیم
      java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
      java.io.PrintStream ps = new java.io.PrintStream(baos);
      java.io.PrintStream old = System.out;
      try {
          System.setOut(ps);
          cmd.explain();
      } finally {
          System.setOut(old);
      }
      assertEquals("tag", cmd.getCommandName());
      // اگر چیزی چاپ شد، حداقل نباید شامل کلمه‌ی exception باشد
      String out = baos.toString().toLowerCase();
      if (!out.trim().isEmpty()) {
          assertFalse(out.contains("exception"));
      }
  }

  @Test(timeout = 4000)
  public void test20_invalidCommand_remove_throws() throws Throwable {
      delay();
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("remove"); // نامعتبر
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test21_add_numericButEmptyTags_throwsInvalidParameter() throws Throwable {
      delay();
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("3");
      params.add(""); // رشته‌ی تگ خالی
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: InvalidParameterException");
      } catch (InvalidParameterException e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test22_add_nonNumericIndex_NumberFormat() throws Throwable {
      delay();
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("add");
      params.add("x");     // غیر عددی
      params.add("t1");
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: NumberFormatException");
      } catch (NumberFormatException e) {
          verifyException("java.lang.NumberFormatException", e);
      }
  }

  @Test(timeout = 4000)
  public void test23_getCommandName_caseInsensitive() throws Throwable {
      delay();
      TagConsoleCommand cmd = new TagConsoleCommand();
      assertEquals("tag", cmd.getCommandName());
      assertTrue(cmd.getCommandName().equalsIgnoreCase("TAG"));
  }

  @Test(timeout = 4000)
  public void test24_list_withTrailingSpace_invalid() throws Throwable {
      delay();
      TagConsoleCommand cmd = new TagConsoleCommand();
      LinkedList<String> params = new LinkedList<String>();
      params.add("list "); // فاصله‌ی انتهایی → نامعتبر
      cmd.setParameters(params);
      try {
          cmd.handleExecute();
          fail("Expecting exception: Exception");
      } catch (Exception e) {
          verifyException("irisdeltaj.simplerelationaltag.br.unb.cic.iris.command.console.TagConsoleCommand", e);
      }
  }
}
