/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 20:57:45 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ChangeFolderConsoleCommand;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class ChangeFolderConsoleCommand_ESTest extends ChangeFolderConsoleCommand_ESTest_scaffolding {

  // --- Per-test delay: 0.5 second (500 ms) so it won't conflict with @Test(timeout = 4000)
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChangeFolderConsoleCommand changeFolderConsoleCommand0 = new ChangeFolderConsoleCommand();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("");
      changeFolderConsoleCommand0.setParameters(linkedList0);
      // Undeclared exception!
      try { 
        changeFolderConsoleCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
         //
         // irisdeltaj/simplerelational/br/unb/cic/iris/persistence/relational/FolderDAO
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChangeFolderConsoleCommand changeFolderConsoleCommand0 = new ChangeFolderConsoleCommand();
      changeFolderConsoleCommand0.handleExecute();
      assertEquals("cd", changeFolderConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChangeFolderConsoleCommand changeFolderConsoleCommand0 = new ChangeFolderConsoleCommand();
      changeFolderConsoleCommand0.explain();
      assertEquals("cd", changeFolderConsoleCommand0.getCommandName());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChangeFolderConsoleCommand changeFolderConsoleCommand0 = new ChangeFolderConsoleCommand();
      String string0 = changeFolderConsoleCommand0.getCommandName();
      assertEquals("cd", string0);
  }

  /** helper: capture System.out while running r (بدون لامبدا) */
  private String captureStdout(Runnable r) {
      PrintStream orig = System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      System.setOut(ps);
      try {
          r.run();
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test4_explain_printsUsage() throws Throwable {
      final ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      String out = captureStdout(new Runnable() {
          @Override public void run() { cmd.explain(); }
      });
      assertTrue(out.contains("(cd <id_folder>) - change current folder)"));
      assertEquals("cd", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test5_handleExecute_withEmptyParameters_doesNothing() throws Throwable {
      final ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>(); // empty
      cmd.setParameters(params);

      String out = captureStdout(new Runnable() {
          @Override public void run() {
              try {
                  cmd.handleExecute();
              } catch (Throwable t) {
                  fail("Should not throw, but got: " + t);
              }
          }
      });

      // هیچ خروجی‌ای انتظار نمی‌رود چون validParameters احتمالاً false است
      assertTrue(out.trim().isEmpty());
  }

  @Test(timeout = 4000)
  public void test6_handleExecute_withSingleParam_callsFolderManager_leadsToNoClassDefFoundError() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("Inbox");
      cmd.setParameters(params);

      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError due to missing FolderDAO/infra");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test7_handleExecute_withTwoParams_stillAttemptsChange_throwsNoClassDefFoundError() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("Inbox");
      params.add("Extra");
      cmd.setParameters(params);

      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test8_handleExecute_withNullParameters_doesNothing() throws Throwable {
      final ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      cmd.setParameters(null); // مشابه حالت پیش‌فرض

      String out = captureStdout(new Runnable() {
          @Override public void run() {
              try {
                  cmd.handleExecute();
              } catch (Throwable t) {
                  fail("Should not throw with null parameters, but got: " + t);
              }
          }
      });

      assertTrue(out.trim().isEmpty());
      assertEquals("cd", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test9_handleExecute_withWhitespaceParam_consideredValid_thenFailsAtFolderManager() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      java.util.LinkedList<String> params = new java.util.LinkedList<String>();
      params.add("   "); // فضای خالی
      cmd.setParameters(params);

      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError because FolderManager is not wired");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test10_getCommandName_notEmpty() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertFalse(name.isEmpty());
      assertEquals("cd", name);
  }

  // ==================== Added extra tests ====================

  @Test(timeout = 4000)
  public void test11_explain_twice_idempotentOutput() throws Throwable {
      final ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out1.contains("(cd <id_folder>)"));
      assertEquals(out1, out2);
      assertEquals("cd", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test12_handleExecute_numericFolderId_NoClassDefFoundError() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      LinkedList<String> p = new LinkedList<>();
      p.add("12345");
      cmd.setParameters(p);
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test13_handleExecute_unicodeFolderId_NoClassDefFoundError() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      LinkedList<String> p = new LinkedList<>();
      p.add("پرونده‌ها");
      cmd.setParameters(p);
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test14_handleExecute_largeParamList_stillTriggersManager_NoClassDefFoundError() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      LinkedList<String> p = new LinkedList<>();
      // مقدار اول به‌عنوان id پوشه استفاده می‌شود، بقیه نادیده گرفته می‌شوند
      p.add("Inbox");
      for (int i = 0; i < 50; i++) p.add("extra" + i);
      cmd.setParameters(p);
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test15_explain_outputHasNoNulls() throws Throwable {
      final ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertFalse(out.toLowerCase().contains("null"));
      assertTrue(out.contains("cd"));
  }

  @Test(timeout = 4000)
  public void test16_handleExecute_trimmedFolderId_NoClassDefFoundError() throws Throwable {
      ChangeFolderConsoleCommand cmd = new ChangeFolderConsoleCommand();
      LinkedList<String> p = new LinkedList<>();
      p.add("   Sent   ");
      cmd.setParameters(p);
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.FolderManager", e);
      }
  }
}
