/*
 * This file was automatically generated by EvoSuite
 * Fri Aug 29 21:56:42 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console;

import org.junit.Test;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;

import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.command.console.ConsoleListRemoteFoldersCommand;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(
    mockJVMNonDeterminism = true,
    useVFS = true,
    useVNET = true,
    resetStaticState = true,
    separateClassLoader = true
)
public class ConsoleListRemoteFoldersCommand_ESTest extends ConsoleListRemoteFoldersCommand_ESTest_scaffolding {

  // --- Per-test delay: 0.5 second (500 ms), safe under @Test(timeout = 4000)
  @Before
  public void halfSecondDelay() throws Exception {
      Thread.sleep(500L);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsoleListRemoteFoldersCommand consoleListRemoteFoldersCommand0 = new ConsoleListRemoteFoldersCommand();
      // Undeclared exception!
      try { 
        consoleListRemoteFoldersCommand0.handleExecute();
        fail("Expecting exception: NoClassDefFoundError");
      } catch(NoClassDefFoundError e) {
         //
         // javax/mail/search/SearchTerm
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleListRemoteFoldersCommand", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConsoleListRemoteFoldersCommand consoleListRemoteFoldersCommand0 = new ConsoleListRemoteFoldersCommand();
      String string0 = consoleListRemoteFoldersCommand0.getCommandName();
      assertEquals("lr", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsoleListRemoteFoldersCommand consoleListRemoteFoldersCommand0 = new ConsoleListRemoteFoldersCommand();
      consoleListRemoteFoldersCommand0.explain();
      assertEquals("lr", consoleListRemoteFoldersCommand0.getCommandName());
  }

  /** helper: گرفتن خروجی System.out بدون لامبدا (سازگار با Java 8) */
  private String captureStdout(final Runnable r) {
      PrintStream orig = System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      System.setOut(ps);
      try {
          r.run();
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }
      return new String(baos.toByteArray(), StandardCharsets.UTF_8);
  }

  @Test(timeout = 4000)
  public void test3_explain_printsUsageAndText() throws Throwable {
      final ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out.contains("(lr)"));
      assertTrue(out.contains("List remote folders"));
      assertEquals("lr", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test4_explain_multipleCalls_consistent() throws Throwable {
      final ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      String out1 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      String out2 = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out1.contains("(lr)"));
      assertTrue(out2.contains("(lr)"));
      assertTrue(out1.contains("List remote folders"));
      assertTrue(out2.contains("List remote folders"));
  }

  @Test(timeout = 4000)
  public void test5_handleExecute_throwsEarly_noStdoutPrinted() throws Throwable {
      ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();

      PrintStream orig = System.out;
      ByteArrayOutputStream baos = new ByteArrayOutputStream();
      PrintStream ps = new PrintStream(baos);
      System.setOut(ps);

      Throwable thrown = null;
      try {
          cmd.handleExecute();
      } catch (Throwable t) {
          thrown = t;
      } finally {
          System.setOut(orig);
          ps.flush();
          ps.close();
      }

      assertNotNull("Expected error due to missing mail infrastructure", thrown);
      assertTrue(thrown instanceof NoClassDefFoundError);
      verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleListRemoteFoldersCommand",
                      (NoClassDefFoundError) thrown);

      String out = new String(baos.toByteArray(), StandardCharsets.UTF_8);
      assertTrue(out.trim().isEmpty());
  }

  @Test(timeout = 4000)
  public void test6_handleExecute_twice_stillFails_consistently() throws Throwable {
      ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      try {
          cmd.handleExecute();
          fail("Expected NoClassDefFoundError on first call");
      } catch (NoClassDefFoundError expected) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleListRemoteFoldersCommand", expected);
      }
      try {
          cmd.handleExecute();
          fail("Expected NoClassDefFoundError on second call as well");
      } catch (NoClassDefFoundError expected) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleListRemoteFoldersCommand", expected);
      }
  }

  @Test(timeout = 4000)
  public void test7_getCommandName_nonEmpty_constant() throws Throwable {
      ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      String name = cmd.getCommandName();
      assertNotNull(name);
      assertFalse(name.isEmpty());
      assertEquals("lr", name);
  }

  // ==================== Added extra tests (each inherits the 0.5s delay via @Before) ====================

  @Test(timeout = 4000)
  public void test8_explain_outputHasNoNullLiteral() throws Throwable {
      final ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertFalse(out.toLowerCase().contains("null"));
      assertTrue(out.contains("(lr)"));
  }

  @Test(timeout = 4000)
  public void test9_explain_containsClosingParenOrLineBreak() throws Throwable {
      final ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out.contains(")")); // پیام راهنما کامل است
  }

  @Test(timeout = 4000)
  public void test10_explain_isStableAcrossCalls_notEmpty() throws Throwable {
      final ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      String a = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } }).trim();
      String b = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } }).trim();
      assertFalse(a.isEmpty());
      assertEquals(a, b);
  }

  @Test(timeout = 4000)
  public void test11_handleExecute_preservesCommandNameAfterFailure() throws Throwable {
      ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      try {
          cmd.handleExecute();
          fail("Expecting NoClassDefFoundError");
      } catch (NoClassDefFoundError e) {
          verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.command.console.ConsoleListRemoteFoldersCommand", e);
      }
      assertEquals("lr", cmd.getCommandName());
  }

  @Test(timeout = 4000)
  public void test12_explain_unicodeSafe_noCrash() throws Throwable {
      // این دستور متن انگلیسی چاپ می‌کند؛ فقط مطمئن شویم چاپ یونیکد مشکلی ندارد
      final ConsoleListRemoteFoldersCommand cmd = new ConsoleListRemoteFoldersCommand();
      String out = captureStdout(new Runnable() { @Override public void run() { cmd.explain(); } });
      assertTrue(out.contains("(lr)"));
      assertTrue(out.contains("List remote folders"));
  }
}
