/*
 * This file was automatically generated by EvoSuite
 * Sun Aug 31 19:21:04 GMT 2025
 */

package irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.EmailProvider;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider.ProviderManager;
import irisdeltaj.simplerelationalsecuritycomplete.br.unb.cic.iris.mail.provider.YahooProvider;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.junit.Before;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ProviderManager_ESTest extends ProviderManager_ESTest_scaffolding {

  /** تاخیر نیم‌ثانیه‌ای قبل از اجرای هر تست */
  @Before
  public void delay() throws Exception {
      Thread.sleep(500);
  }

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      EmailProvider emailProvider0 = providerManager0.getProvider("outlook");
      assertNull(emailProvider0.getUsername());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      // Undeclared exception!
      try { 
        providerManager0.getProvider("}pxVEw~,.i]Rq2");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.core.BaseManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      // Undeclared exception!
      try { 
        providerManager0.addProvider((EmailProvider) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("irisdeltaj.simplerelational.br.unb.cic.iris.mail.provider.ProviderManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      YahooProvider yahooProvider0 = new YahooProvider("@|GV/Bc!{\u007f=$b`B,z", "@|GV/Bc!{\u007f=$b`B,z");
      providerManager0.addProvider(yahooProvider0);
      assertEquals((-1), yahooProvider0.getTransportPort());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      providerManager0.doAddProviders_original3();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      providerManager0.doAddProviders_original0();
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      providerManager0.doAddProviders_original2();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      List<EmailProvider> list0 = providerManager0.getProviders();
      assertEquals(6, list0.size());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      EmailProvider emailProvider0 = providerManager0.getProvider("yahoo");
      assertTrue(emailProvider0.isAuthenticationEnabled());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ProviderManager providerManager0 = ProviderManager.instance();
      providerManager0.doAddProviders();
  }

  @Test(timeout = 4000)
  public void test10_addProviderWithTrimmedName()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      int before = mgr.getProviders().size();

      // زیرکلاس ناشناس از GmailProvider که name را با فاصله برمی‌گرداند
      GmailProvider custom = new GmailProvider() {
        @Override public String getName() { return "  custom  "; }
      };
      mgr.addProvider(custom);

      assertSame(custom, mgr.getProvider("custom"));
      assertEquals(before + 1, mgr.getProviders().size());
  }

  @Test(timeout = 4000)
  public void test11_duplicateNameOverridesMapping()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      int before = mgr.getProviders().size();

      OutlookProvider p1 = new OutlookProvider();
      p1.setUsername("A");
      mgr.addProvider(p1);

      OutlookProvider p2 = new OutlookProvider();
      p2.setUsername("B");
      mgr.addProvider(p2);

      EmailProvider got = mgr.getProvider("outlook");
      assertSame(p2, got); // باید آخرین provider با همین نام برگرده
      assertEquals(before + 2, mgr.getProviders().size()); // هر دو به لیست اضافه شده‌اند
  }

  @Test(timeout = 4000)
  public void test12_providersListIsUnmodifiable()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      List<EmailProvider> list = mgr.getProviders();
      try {
        list.clear();
        fail("Expected UnsupportedOperationException");
      } catch (UnsupportedOperationException expected) {
        // OK
      }
  }

  @Test(timeout = 4000)
  public void test13_caseSensitivityOnLookup()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      try {
        mgr.getProvider("OutLook"); // حروف متفاوت
        fail("Expected NullPointerException");
      } catch (NullPointerException expected) {
        // OK - BaseManager.get روی key نامعتبر NPE می‌دهد
      }
  }

  @Test(timeout = 4000)
  public void test14_doAddProviders_original0_NoChangeInSize()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      int before = mgr.getProviders().size();
      mgr.doAddProviders_original0(); // هیچ کاری نمی‌کند
      int after = mgr.getProviders().size();
      assertEquals(before, after);
  }

  @Test(timeout = 4000)
  public void test15_getProviderReturnsSameReferenceOnRepeatedCalls()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      EmailProvider p1 = mgr.getProvider("gmail");
      EmailProvider p2 = mgr.getProvider("gmail");
      assertSame(p1, p2);
  }

  @Test(timeout = 4000)
  public void test16_addUniqueCustomNameAndVerifyRetrieval()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      GmailProvider custom = new GmailProvider() {
        @Override public String getName() { return "mygmail"; }
      };
      mgr.addProvider(custom);

      EmailProvider got = mgr.getProvider("mygmail");
      assertSame(custom, got);
      // چند ویژگی کلیدی همچنان باید مقادیر Gmail را داشته باشند
      assertEquals("smtp.gmail.com", got.getTransportHost());
      assertEquals("imap.gmail.com", got.getStoreHost());
  }

  @Test(timeout = 4000)
  public void test17_addProviderWithNullNameThrowsNPE()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      // زیرکلاس از OutlookProvider با getName برابر null
      OutlookProvider bad = new OutlookProvider() {
        @Override public String getName() { return null; }
      };
      try {
        mgr.addProvider(bad); // trim روی null → NPE
        fail("Expected NullPointerException");
      } catch (NullPointerException expected) {
        // OK
      }
  }

  // -----------------------
  // تست‌های اضافه‌شده
  // -----------------------

  @Test(timeout = 4000)
  public void test18_instanceSingleton_idempotent()  throws Throwable  {
      ProviderManager a = ProviderManager.instance();
      ProviderManager b = ProviderManager.instance();
      assertSame("ProviderManager.instance() should return the same reference", a, b);
  }

  @Test(timeout = 4000)
  public void test19_getProvider_null_throwsNPE()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      try {
          mgr.getProvider((String) null);
          fail("Expected NullPointerException");
      } catch (NullPointerException expected) {
          // OK
      }
  }

  @Test(timeout = 4000)
  public void test20_getProvider_withSpacesNotTrimmedOnLookup()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      // یک provider با نام trim‌شده اضافه می‌کنیم
      GmailProvider zed = new GmailProvider() {
        @Override public String getName() { return "  zed  "; }
      };
      mgr.addProvider(zed);

      // lookup با نام trim‌شده باید کار کند
      assertSame(zed, mgr.getProvider("zed"));

      // lookup با فاصله‌ها نباید کار کند (چون getProvider ورودی را trim نمی‌کند)
      try {
          mgr.getProvider("  zed  ");
          fail("Expected NullPointerException for spaced key");
      } catch (NullPointerException expected) {
          // OK
      }
  }

  @Test(timeout = 4000)
  public void test21_addedProviderReference_isMutableThroughManager()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      OutlookProvider op = new OutlookProvider() {
        @Override public String getName() { return "mut"; }
      };
      mgr.addProvider(op);

      op.setUsername("U1");
      assertEquals("U1", mgr.getProvider("mut").getUsername());

      op.setUsername("U2");
      assertEquals("U2", mgr.getProvider("mut").getUsername());
  }

  @Test(timeout = 4000)
  public void test22_addUppercaseName_keepsLowercaseOriginal()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      // provider پیش‌فرض gmail را می‌گیریم
      EmailProvider originalGmail = mgr.getProvider("gmail");

      // یک provider جدید با نام GMAIL اضافه می‌کنیم
      GmailProvider upper = new GmailProvider() {
        @Override public String getName() { return "GMAIL"; }
      };
      mgr.addProvider(upper);

      // lookup با حروف بزرگ باید آبجکت جدید را بدهد
      assertSame(upper, mgr.getProvider("GMAIL"));
      // lookup با حروف کوچک باید provider اصلی بماند (case-sensitive)
      assertSame(originalGmail, mgr.getProvider("gmail"));
      assertNotSame("Uppercase and lowercase entries should be distinct keys", upper, originalGmail);
  }

  @Test(timeout = 4000)
  public void test23_caseSensitivity_yahooUppercaseFails()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      try {
          mgr.getProvider("YAHOO");
          fail("Expected NullPointerException");
      } catch (NullPointerException expected) {
          // OK
      }
  }

  @Test(timeout = 4000)
  public void test24_providers_countAtLeastThreeBuiltins()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      assertTrue("Should have at least a few built-in providers",
              mgr.getProviders().size() >= 3);
  }

  @Test(timeout = 4000)
  public void test25_addedProvider_isContainedInList()  throws Throwable  {
      ProviderManager mgr = ProviderManager.instance();
      GmailProvider custom = new GmailProvider() {
        @Override public String getName() { return "inlist"; }
      };
      mgr.addProvider(custom);
      assertTrue(mgr.getProviders().contains(custom));
      assertSame(custom, mgr.getProvider("inlist"));
  }

}
